### ISSUE TITLE
Missing 'data' folder in nerfstudio/nerfstudio causes error.

### ISSUE THREAD

**Issue by synsin0** [OPEN-AIR-SUN/mars#1]
Thanks for your great work, may you examine if there is a 'data' folder under nerfstudio/nerfstudio that is not uploaded?

**Comment by xBeho1der** [comment]
Thanks for your feedback!

**Comment by xBeho1der** [comment]
Thank you for your support and for bringing this issue to our attention. We appreciate your feedback on the project!  We have verified the repository and uploaded the 'data' folder.

**Comment by xBeho1der** [comment]
> Thanks for your great work, may you examine if there is a 'data' folder under nerfstudio/nerfstudio that is not uploaded?

Thank you for your support and for bringing this issue to our attention. We appreciate your feedback on the project! We have verified the repository and uploaded the 'data' folder.
