### ISSUE TITLE
question about render result and viewer usage

### ISSUE THREAD

**Issue by baekhyun77** [OPEN-AIR-SUN/mars#101]
Hello, thank you for your work. I trained using the weights you provided and tried to export a video：
```
python scripts/cicai_render.py --load-config outputs/kitti-recon-65-120/mars-kitti-car-depth-recon/2023-10-30_212654/config.yml --output-format video
```
 but I only got a 13-second video that I cannot open. May I ask what could be the reason for this?
![问题mp4](https://github.com/OPEN-AIR-SUN/mars/assets/57160154/10a16fd9-2400-4c77-940a-e9f11b851a23)

Furthermore, when I tried to open and view it using NerfStudio, the interface looked strange, and there was no scene displayed.
![错误](https://github.com/OPEN-AIR-SUN/mars/assets/57160154/7ce072f0-a849-4502-8f10-e191226b2d82)
I am a beginner in this field, and there may be some configuration issues that I am not aware of.

**Comment by xBeho1der** [comment]
Hi! @baekhyun77 Sorry for the late response.

1. I used the same script and config for rendering, and it can be opened in VSCode. However, I found that the default software on Windows seems unable to open it. You can try using a different video software like VLC Media Player.

2. You can refer to [here](https://github.com/OPEN-AIR-SUN/mars/issues/54#issuecomment-1695690699) about how to obtain the scene in viewer.

**Comment by wuzirui** [comment]
I personally recommend render images and composes video afterwards, rather than directly render videos.

**Comment by baekhyun77** [comment]
Thank you for your answers. I also opened the video using VSCode.
