### ISSUE TITLE
masks in vkitti dataparser 

### ISSUE THREAD

**Issue by Francis777** [OPEN-AIR-SUN/mars#102]
Hello! I'm wondering why we're using instance as masks in the vkitti dataparser as shown below? As we don't need to mask out dynamic agents in MARS, this seems confusing to me. Thanks!   https://github.com/OPEN-AIR-SUN/mars/blob/5d7567504220f9a8a09aa20a199954f481a26484/mars/data/mars_vkitti_dataparser.py#L666

**Comment by xBeho1der** [comment]
Hi! @Francis777 

We use masks for semantic and sky region loss computation. You can find more details in our code (`mars/models/scene_graph.py`) .

![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/f2945c7b-92a5-4e17-af47-bee87ccb5903)

**Comment by Francis777** [comment]
Thanks! But the code you're referring to seems to be using the semantic metadata rather than the masks given to `mask_filenames`? As comparison you don't do that in the kitti dataparser, so I'm wondering why there's the difference? https://github.com/OPEN-AIR-SUN/mars/blob/5d7567504220f9a8a09aa20a199954f481a26484/mars/data/mars_kitti_dataparser.py#L1307

**Comment by xBeho1der** [comment]
This seems to be a legacy issue. The `mask_filenames` is not used in our code.

Due to the initial use of the vkitti dataset when adding semantic-related code, there is a difference between these dataparsers.

**Comment by wuzirui** [comment]
The mask_filenames is part of the nerfstudio functionality, which is used to mask out unwanted regions, and is not supposed to happen in our setting.

**Comment by Francis777** [comment]
Cool, thanks for clarifying!

**Comment by Nplace-su** [comment]
@wuzirui Hi, I want to make sure that I can still use mask_filenames if I need to mask out unwanted regions of images, right? I 
 mean is this functionality of nerfstudio conflict with MARS?

**Comment by wuzirui** [comment]
Hi @Nplace-su, this is untested in mars. If you encounter any problems, feel free to bring that to us!

**Comment by Nplace-su** [comment]
> Hi @Nplace-su, this is untested in mars. If you encounter any problems, feel free to bring that to us!

Sure, I will try it.

**Comment by Nplace-su** [comment]
> @wuzirui Hi, I want to make sure that I can still use mask_filenames if I need to mask out unwanted regions of images, right? I mean is this functionality of nerfstudio conflict with MARS?

After a few experiments, I think the mask functionality of nerfstudio can be safely used in MARS.  get_data() of mars_dataset.py needs some editing to make sure the mask files are read, as well as some small changes in dataparser.

**Comment by wuzirui** [comment]
Thanks for letting us know! Also, you are very welcomed to create a pr if you like :)

**Comment by Nplace-su** [comment]
> Thanks for letting us know! Also, you are very welcomed to create a pr if you like :)

I'd like to do so, however, my local codes diverged too much from this repo... so it's not very convenient for me to test my change on master branch.
Maybe I will do this if I have time running the latest code on my personal computer.  :D
