### ISSUE TITLE
Rendering only one car and add another car to the scene

### ISSUE THREAD

**Issue by ChaofengWu0** [OPEN-AIR-SUN/mars#105]
Thank you for your wonderful work!

I'm wondering whether the project supports removing all cars from the scene and only remaining one car I wanted in the scene.And after this, is it possible to add another car into the scene and make it moves following a new trajectory I designed?

I mean,let's make a suppose. The number of car in the original dataset is more than 2, and I want the output of render has only one car, if which is possible, I want to add another car and make it move as I want. Is it feasible?

**Comment by Nplace-su** [comment]
The first question is easy, you can just play with the poses in cacai_render.py so you can move or delete any car.
Adding a car from the same scene is not hard. I have not tried but modifying cacai_render.py should also work.
Adding another car (not from this scene) is not supported AFAIK.

**Comment by wuzirui** [comment]
Thanks @Nplace-su! Adding cars is not supported now, but we have tried it ourselves. You may need to modify the forward pass code and add your customized object model.

**Comment by xBeho1der** [comment]
Thanks @Nplace-su!

To move a car in the scene, you can refer to #35, #40, #28.

To remove a car from the scene, you can modify as below in `cicai_render.py`, where `track_id` refers to the car to be deleted.
```python
                track_ids = batch_obj_dyn[..., 4]
                track_ids[:,:,track_id] = -1
```

To add a car from the same scene, you need to modify the `batch_obj_dyn`,  set the pose, rotation, and correcorresponding track id.

**Comment by ChaofengWu0** [comment]
Thank you all for your replys!

**Comment by wuzirui** [comment]
![image](https://github.com/OPEN-AIR-SUN/mars/assets/7344146/42fdd4f8-a7b8-424a-b290-170a67ad6075)
An example of inserting KITTI cars into VKITTI scenes, FYI. Still, this is not recommended since the lighting conditions vary largely, so hard to make it realistic.

**Comment by Lynchrocket** [comment]
> realistic.

What is the shape of `batch_obj_dyn` and what is the meaning of its dimensions? And what is `track_id`? Is it `object ID` as pointed in the picture?
![image](https://github.com/OPEN-AIR-SUN/mars/assets/77106522/6bc60ba4-0c97-4b7d-a30a-eddeac372b2d)

**Comment by xBeho1der** [comment]
Hi! @Lynchrocket 

1. shape of `batch_obj_dyn` in `cicai_render.py`.
```python
                batch_obj_dyn = camera_ray_bundle.metadata["object_rays_info"].view(
                    camera_ray_bundle.metadata["object_rays_info"].shape[0],
                    camera_ray_bundle.metadata["object_rays_info"].shape[1],
                    pipeline.model.config.max_num_obj,
                    pipeline.model.config.ray_add_input_rows * 3,
                )
 ```
 
 2. The last dimension of `batch_obj_dyn` has a size of 6, representing x, y, z, yaw, object id, and 0 respectively.

**Comment by Lynchrocket** [comment]
> Hi! @Lynchrocket
> 
> 1. shape of `batch_obj_dyn` in `cicai_render.py`.
> 
> ```python
>                 batch_obj_dyn = camera_ray_bundle.metadata["object_rays_info"].view(
>                     camera_ray_bundle.metadata["object_rays_info"].shape[0],
>                     camera_ray_bundle.metadata["object_rays_info"].shape[1],
>                     pipeline.model.config.max_num_obj,
>                     pipeline.model.config.ray_add_input_rows * 3,
>                 )
> ```
> 
> 2. The last dimension of `batch_obj_dyn` has a size of 6, representing x, y, z, yaw, object id, and 0 respectively.

Thank you very much! I get it.

**Comment by win4cs** [comment]
> Thanks @Nplace-su!
> 
> To move a car in the scene, you can refer to #35, #40, #28.
> 
> To remove a car from the scene, you can modify as below in `cicai_render.py`, where `track_id` refers to the car to be deleted.
> 
> ```python
>                 track_ids = batch_obj_dyn[..., 4]
>                 track_ids[:,:,track_id] = -1
> ```
> 
> To add a car from the same scene, you need to modify the `batch_obj_dyn`, set the pose, rotation, and correcorresponding track id.

got exception "index out of range in" at                
outputs = pipeline.model.get_outputs_for_camera_ray_bundle_render(camera_ray_bundle)

track_ids[:,:,track_id] = 0 seem works

**Comment by xBeho1der** [comment]
Hi! @win4cs You are right. Sorry for the misleading info.

**Comment by ChaofengWu0** [comment]
> ![image](https://private-user-images.githubusercontent.com/7344146/283052793-42fdd4f8-a7b8-424a-b290-170a67ad6075.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMTk1MDgsIm5iZiI6MTcwNTIxOTIwOCwicGF0aCI6Ii83MzQ0MTQ2LzI4MzA1Mjc5My00MmZkZDRmOC1hN2I4LTQyNGEtYjI5MC0xNzBhNjdhZDYwNzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMDgwMDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2NhMzdhMDI0OTA4MzRmMjJiNzZlYzg3YmZjY2EyOTVhNjUwMzFmMTcyMDNmMDlmNDhjNTA4ZGU3NDliMGFlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fL8-y85syUHZ3DMhYsKd0g0brds6gIbt-5VFT0obRl8) An example of inserting KITTI cars into VKITTI scenes, FYI. Still, this is not recommended since the lighting conditions vary largely, so hard to make it realistic.

Hi! Thanks for your reply. And could you please tell me what should I do and which files to modify to insert a vkitti car into the kitti scene or insert a customized car into the kitti scene?
