### ISSUE TITLE
How to expand the model？

### ISSUE THREAD

**Issue by flyinghippof** [OPEN-AIR-SUN/mars#106]
hi，I'm very happy to see such an excellent job.
I found severe blur on my own dataset，I think it may be due to the image resolution and scene relative to size of model。
so i want to expand the size of model.
I haven't found any experience in expanding the model，Can you give some suggestions, such as NerfactoModelConfig.

**Comment by wuzirui** [comment]
Hi！ Could you give us some more information about your experiments?

**Comment by flyinghippof** [comment]
thanks for your reply.
The results I rendered are as follows：
![image](https://github.com/OPEN-AIR-SUN/mars/assets/72117809/b8b8bbd1-81b9-49d9-8ded-1f3d4b673f18)
I train on my own dataset, use default VKITTI_NVS_NSG_Car_Depth config

**Comment by wuzirui** [comment]
1. the foreground objects seem not to have been fully converged. maybe run more steps?
2. for background, I recommend first test your sequence on nerfacto till you have a satisfying result, and then use the same configs in mars

**Comment by Yurri-hub** [comment]
Hi! How to get the latent code of your own dataset?
