### ISSUE TITLE
How to use multi GPU acceleration

### ISSUE THREAD

**Issue by flyinghippof** [OPEN-AIR-SUN/mars#107]
hi, I found that the multi GPU training feature has been updated few weeks ago。
https://github.com/OPEN-AIR-SUN/mars/blob/26669179c35f2e35c8f89bd3e9c07bf91632fa43/nerfstudio/nerfstudio/configs/experiment_config.py#L54
I simply configured the MachineConfig as:
```
machine=MachineConfig(num_gpus=torch.cuda.device_count()),
```
It does run on multiple GPUs, but the training time has not decreased.
I would like to ask how to use it correctly。

**Comment by Nplace-su** [comment]
The training time depends on the training steps you set, so simply changing 1 gpu to N gpus will not decrease training time?
You can refer to the doc of Nerfstudio: https://docs.nerf.studio/quickstart/first_nerf.html#multi-gpu-training

**Comment by flyinghippof** [comment]
thanks for all your reply，i will have a try！！
