### ISSUE TITLE
reconstruction result with pretrained model looks strange

### ISSUE THREAD

**Issue by hemp110** [OPEN-AIR-SUN/mars#109]
Hi, below are the render results with pretrained model (outputs/kitti-recon-65-120/mars-kitti-car-depth-recon/2023-10-30_212654/nerfstudio_models/step-000400000.ckpt), they are different with the results you posted. 
There are shadows on the road in the background, and background pixels in object_rgb (red box). 
Could you give some instructions?
![image](https://github.com/OPEN-AIR-SUN/mars/assets/17939760/ce934934-6fa9-42c1-8107-c7b122cab67d)

**Comment by hemp110** [comment]
Besides, I'm training the scene (kitti-0006) from scrach, the rgb results seems to have the same problem, and the depth prediction is also abnormal. 
https://wandb.ai/hemp110/nerfstudio-project/runs/iydafnkm?workspace=user-hemp110
![image](https://github.com/OPEN-AIR-SUN/mars/assets/17939760/e4308723-a3ff-465b-a2db-7835c63de2ec)

**Comment by xBeho1der** [comment]
Hi! @hemp110 

1. The posted visualization result was not rendered with the checkpoint on the master branch now. Maybe training a longer sequence will help. Below is the background rgb from a longer sequence.

![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/d2218906-1d4e-4a75-8f81-3727d83e76d8)

2. For depth prediction, #92 might help. For the monocular depth supervision visualization, ground truth depth and predicted truth are not of identical scale, clipping operation probably should not be applied.

**Comment by hemp110** [comment]
> Hi, below are the render results with pretrained model (outputs/kitti-recon-65-120/mars-kitti-car-depth-recon/2023-10-30_212654/nerfstudio_models/step-000400000.ckpt), they are different with the results you posted. There are shadows on the road in the background, and background pixels in object_rgb (red box). Could you give some instructions? ![image](https://private-user-images.githubusercontent.com/17939760/285401769-ce934934-6fa9-42c1-8107-c7b122cab67d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTQ5MjEsIm5iZiI6MTcwMDk5NDYyMSwicGF0aCI6Ii8xNzkzOTc2MC8yODU0MDE3NjktY2U5MzQ5MzQtNmZhOS00MmMxLTgxMDctYzdiMTIyY2FiNjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDEwMzAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5OWNjMGVmYzE2MThlY2Q2OTI4MmQzYjE1NGNmOWYzMGExNDVhYjU5MzhkMjRkNTJiZDNlOTQzYTdkN2Y3MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uAwWrXuQimBxV5sRAwRvgGuO8dDUJXSWktgDDmBpLV0)

@xBeho1der  thanks for your replay, but the result in first post is rendered with checkpoint on the master branch. I downloaded it just 3 or 4 days ago.
When rendering, I met errors in loading checkpoint
```
RuntimeError: Error(s) in loading state_dict for SceneGraphModel:
        Missing key(s) in state_dict: "background_model.lpips.net.scaling_layer.shift", "background_model.lpips.net.scaling_layer.scale", "object_models.object_class_0.lpips.net.scaling_layer.shift", "object_models.object_class_0.lpips.net.scaling_layer.scale", "object_models.object_class_2.lpips.net.scaling_layer.shift", "object_models.object_class_2.lpips.net.scaling_layer.scale", "lpips.net.scaling_layer.shift", "lpips.net.scaling_layer.scale".
```
But I didn't find any similar issues in this repo. After searching in web, i fixed it by modifying `lpips.py`
<img width="847" alt="image" src="https://github.com/OPEN-AIR-SUN/mars/assets/17939760/abafd92c-b739-4144-9988-8800c15af7ea">
Is my problem related with my modification?

**Comment by hemp110** [comment]
I tried another pretrained model in the repo (kitti-nvs-75) by running
```
python scripts/cicai_render.py --load-config outputs/kitti-nvs-75/mars-kitti-car-depth-nvs/2023-10-31_111111/config.yml --rendered_output_names rgb depth background background_depth objects_rgb objects_depth --output-format images --output-path outputs/kitti-nvs-75/mars-kitti-car-depth-nvs/2023-10-31_111111/rendered_images
```
the rendered results have the same problem.
![00000](https://github.com/OPEN-AIR-SUN/mars/assets/17939760/d08e2a03-f6d5-43f4-9b4c-031b6a729f54)

**Comment by xBeho1der** [comment]
> > Hi, below are the render results with pretrained model (outputs/kitti-recon-65-120/mars-kitti-car-depth-recon/2023-10-30_212654/nerfstudio_models/step-000400000.ckpt), they are different with the results you posted. There are shadows on the road in the background, and background pixels in object_rgb (red box). Could you give some instructions? ![image](https://private-user-images.githubusercontent.com/17939760/285401769-ce934934-6fa9-42c1-8107-c7b122cab67d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTQ5MjEsIm5iZiI6MTcwMDk5NDYyMSwicGF0aCI6Ii8xNzkzOTc2MC8yODU0MDE3NjktY2U5MzQ5MzQtNmZhOS00MmMxLTgxMDctYzdiMTIyY2FiNjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDEwMzAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5OWNjMGVmYzE2MThlY2Q2OTI4MmQzYjE1NGNmOWYzMGExNDVhYjU5MzhkMjRkNTJiZDNlOTQzYTdkN2Y3MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uAwWrXuQimBxV5sRAwRvgGuO8dDUJXSWktgDDmBpLV0)
> 
> @xBeho1der thanks for your replay, but the result in first post is rendered with checkpoint on the master branch. I downloaded it just 3 or 4 days ago, and render with command
> 
> ```
> python scripts/cicai_render.py --load-config outputs/kitti-recon-65-120/mars-kitti-car-depth-recon/2023-10-30_212654/config.yml --rendered_output_names rgb depth background background_depth objects_rgb objects_depth --output-format images --output-path outputs/kitti-recon-65-120/mars-kitti-car-depth-recon/2023-10-30_212654/rendered_images
> ```
> 
> In `config.yml ` I only modified `data`, `car_nerf_state_dict_path` and `car_object_latents_path` to my path. When rendering, I met errors in loading checkpoint
> 
> ```
> RuntimeError: Error(s) in loading state_dict for SceneGraphModel:
>         Missing key(s) in state_dict: "background_model.lpips.net.scaling_layer.shift", "background_model.lpips.net.scaling_layer.scale", "object_models.object_class_0.lpips.net.scaling_layer.shift", "object_models.object_class_0.lpips.net.scaling_layer.scale", "object_models.object_class_2.lpips.net.scaling_layer.shift", "object_models.object_class_2.lpips.net.scaling_layer.scale", "lpips.net.scaling_layer.shift", "lpips.net.scaling_layer.scale".
> ```
> 
> But I didn't find any similar issues in this repo. After searching in web, i fixed it by modifying `lpips.py` <img alt="image" width="847" src="https://private-user-images.githubusercontent.com/17939760/285645059-abafd92c-b739-4144-9988-8800c15af7ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyODQyNzIsIm5iZiI6MTcwMTI4Mzk3MiwicGF0aCI6Ii8xNzkzOTc2MC8yODU2NDUwNTktYWJhZmQ5MmMtYjczOS00MTQ0LTk5ODgtODgwMGMxNWFmN2VhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE4NTI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5Y2FiYjQ0ODZmNzdhYzZiMDY2YTU2MTJlZjBhMDBmMTUxYTY0OWM3YWE3MzE4MWY5N2I5ODBlZDM4ZTU2MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5VQxZZU9OjfRQA8_3GGeQ784bqDn5uijB35AfkCYZMo"> Is my problem related with my modification?

Hi! @hemp110 

Your operation and modification seem to be fine. I use the same checkpoint and command to render but I haven't encountered this problem.

**Comment by hemp110** [comment]
> Besides, I'm training the scene (kitti-0006) from scrach, the rgb results seems to have the same problem, and the depth prediction is also abnormal. https://wandb.ai/hemp110/nerfstudio-project/runs/iydafnkm?workspace=user-hemp110 ![image](https://private-user-images.githubusercontent.com/17939760/285421598-e4308723-a3ff-465b-a2db-7835c63de2ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NTY1MjEsIm5iZiI6MTcwMTY1NjIyMSwicGF0aCI6Ii8xNzkzOTc2MC8yODU0MjE1OTgtZTQzMDg3MjMtYTNmZi00NjViLWEyZGItNzgzNWM2M2RlMmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDAyMTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxODIwYjYzMGNhODU3NjgwZTg2MTFhZThlYjBlMDFkY2I2NTNkNjA2MzdiZWJiOGE0ZmRmMmQ4MTE1YWVlNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.69KncybzYp30h86TmvvAyv4wqRke3p-fUZlMnjc075I)

@wuzirui as in this post, I trained from scratch with the same setting (CUDA 11.4). The key figures, such as train/eval loss, eval psnr/ssim/lpips are basically the same as the wandb you provided. However, the rendered images suffer from the shadow problem.
This is [the wandb you provided](https://wandb.ai/wuzirui-research/nerfstudio-project/reports/kitti-recon--Vmlldzo1ODQ5MTkz?accessToken=qs180hh208l93q41b3llnc5c0x6657j52r7qgikz3nb0xcbx65lfpkt40n1836k8)
![image](https://github.com/OPEN-AIR-SUN/mars/assets/17939760/8a2e87b1-1ab1-41da-a92a-f21a6672c27f)
![image](https://github.com/OPEN-AIR-SUN/mars/assets/17939760/b63c2b36-7763-4837-835f-a48e1afe39da)
This is [my wandb](https://wandb.ai/hemp110/nerfstudio-project/runs/iydafnkm?workspace=user-hemp110)
![image](https://github.com/OPEN-AIR-SUN/mars/assets/17939760/3cd9159a-e4f2-4a31-88fe-5d2af60db378)
![image](https://github.com/OPEN-AIR-SUN/mars/assets/17939760/ceb2b287-27ba-4c2e-99f2-a558f1abc356)
![image](https://github.com/OPEN-AIR-SUN/mars/assets/17939760/18d12b47-a52a-45f2-9f18-1f344743ade2)
