### ISSUE TITLE
KITTI 0002 BUG

### ISSUE THREAD

**Issue by jelleopard** [OPEN-AIR-SUN/mars#11]
When I run the scrip : ns-train nsg-kitti-car-depth-recon --data /*/kitti/training/image_02/0006, It's working fine.

I have generated the depth completion and /*/mars/data/kitti/panoptic_maps/train files, but  I didn't have /*/mars/data/kitti/panoptic_maps/colors/000*.txt
However，I run the scrip : ns-train nsg-kitti-car-depth-recon --data /*/kitti/training/image_02/0002
The error occur, I need you help thanks

Printing profiling stats, from longest to shortest duration in seconds
Trainer.train_iteration: 2.1515              
NSGPipeline.get_train_loss_dict: 2.1508              
Traceback (most recent call last):
  File "/home/*/anaconda3/envs/SUDS/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/*/mars/nerfstudio/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/*/mars/nerfstudio/nerfstudio/scripts/train.py", line 248, in main
    launch(
  File "/home/*/mars/nerfstudio/nerfstudio/scripts/train.py", line 187, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/*/mars/nerfstudio/nerfstudio/scripts/train.py", line 102, in train_loop
    trainer.train()
  File "/home/*/mars/nerfstudio/nerfstudio/engine/trainer.py", line 242, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/home/*/mars/nerfstudio/nerfstudio/utils/profiler.py", line 91, in inner
    out = func(*args, **kwargs)
  File "/home/*/mars/nerfstudio/nerfstudio/engine/trainer.py", line 446, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "/home/*/mars/nerfstudio/nerfstudio/utils/profiler.py", line 91, in inner
    out = func(*args, **kwargs)
  File "/home/*/mars/nsg/nsg_pipeline.py", line 134, in get_train_loss_dict
    model_outputs = self.model(ray_bundle)
  File "/home/*/anaconda3/envs/SUDS/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/*/mars/nerfstudio/nerfstudio/models/base_model.py", line 140, in forward
    return self.get_outputs(ray_bundle)
  File "/home/*/mars/nsg/models/scene_graph.py", line 443, in get_outputs
    result = model.inference_without_render(ray_obj)
  File "/home/*/mars/nsg/models/car_nerf.py", line 228, in inference_without_render
    self.car_latents[int(obj_id)].view(1, -1).to(obj_id.device),
KeyError: 3

**Comment by xBeho1der** [comment]
> When I run the scrip : ns-train nsg-kitti-car-depth-recon --data /*/kitti/training/image_02/0006, It's working fine.
> 
> I have generated the depth completion and /_/mars/data/kitti/panoptic_maps/train files, but I didn't have /_/mars/data/kitti/panoptic_maps/colors/000*.txt However，I run the scrip : ns-train nsg-kitti-car-depth-recon --data /*/kitti/training/image_02/0002 The error occur, I need you help thanks
> 
> Printing profiling stats, from longest to shortest duration in seconds Trainer.train_iteration: 2.1515 NSGPipeline.get_train_loss_dict: 2.1508 Traceback (most recent call last): File "/home/_/anaconda3/envs/SUDS/bin/ns-train", line 8, in sys.exit(entrypoint()) File "/home/_/mars/nerfstudio/nerfstudio/scripts/train.py", line 262, in entrypoint main( File "/home/_/mars/nerfstudio/nerfstudio/scripts/train.py", line 248, in main launch( File "/home/_/mars/nerfstudio/nerfstudio/scripts/train.py", line 187, in launch main_func(local_rank=0, world_size=world_size, config=config) File "/home/_/mars/nerfstudio/nerfstudio/scripts/train.py", line 102, in train_loop trainer.train() File "/home/_/mars/nerfstudio/nerfstudio/engine/trainer.py", line 242, in train loss, loss_dict, metrics_dict = self.train_iteration(step) File "/home/_/mars/nerfstudio/nerfstudio/utils/profiler.py", line 91, in inner out = func(_args, **kwargs) File "/home/_/mars/nerfstudio/nerfstudio/engine/trainer.py", line 446, in train_iteration _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step) File "/home/_/mars/nerfstudio/nerfstudio/utils/profiler.py", line 91, in inner out = func(_args, **kwargs) File "/home/_/mars/nsg/nsg_pipeline.py", line 134, in get_train_loss_dict model_outputs = self.model(ray_bundle) File "/home/_/anaconda3/envs/SUDS/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(_input, **kwargs) File "/home/_/mars/nerfstudio/nerfstudio/models/base_model.py", line 140, in forward return self.get_outputs(ray_bundle) File "/home/_/mars/nsg/models/scene_graph.py", line 443, in get_outputs result = model.inference_without_render(ray_obj) File "/home/*/mars/nsg/models/car_nerf.py", line 228, in inference_without_render self.car_latents[int(obj_id)].view(1, -1).to(obj_id.device), KeyError: 3

Hi! Thanks for your feedback. For this error, you may check the `car_object_latents_path` and `car_nerf_state_dict_path` in your experiment config, make sure that you use the corresponding latent codes for the sequence you train with.

**Comment by xBeho1der** [comment]
> 

Hi!
1. If you don't want to use our category-level object model, you should ensure `use_car_latents=False` and your `object_model_template` **is not** `CarNeRFModelConfig`.
2. If you train with KITTI 0002, you need to use `latent_codes02.pt` for `car_object_latents_path`  instead of `latent_codes06.pt`.

**Comment by xBeho1der** [comment]
> When I set the use_car_latents=False, Also have error.
> 
> KITTI_Recon_NSG_Car_Depth = MethodSpecification( config=TrainerConfig( method_name="nsg-kitti-car-depth-recon", steps_per_eval_image=STEPS_PER_EVAL_IMAGE, steps_per_eval_all_images=STEPS_PER_EVAL_ALL_IMAGES, steps_per_save=STEPS_PER_SAVE, max_num_iterations=MAX_NUM_ITERATIONS, save_only_latest_checkpoint=False, mixed_precision=False, use_grad_scaler=True, log_gradients=True, pipeline=NSGPipelineConfig( datamanager=NSGkittiDataManagerConfig( dataparser=NSGkittiDataParserConfig( use_car_latents=False, use_depth=True, car_object_latents_path=Path( "/home/3/mars/latents/KITTI-MOT/car-object-latents/latent_codes06.pt" ), split_setting="reconstruction", car_nerf_state_dict_path=Path("/home/3/mars/latents/KITTI-MOT/car-nerf-state-dict/epoch_670.ckpt"), ), train_num_rays_per_batch=4096, eval_num_rays_per_batch=4096, camera_optimizer=CameraOptimizerConfig(mode="off"), ), model=SceneGraphModelConfig( background_model=NerfactoModelConfig(), object_model_template=CarNeRFModelConfig(_target=CarNeRF), object_representation="class-wise", object_ray_sample_strategy="remove-bg", ), ), optimizers={ "background_model": { "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15), "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000), }, "learnable_global": { "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15), "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000), }, "object_model": { "optimizer": RAdamOptimizerConfig(lr=5e-3, eps=1e-15), "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000), }, }, # viewer=ViewerConfig(num_rays_per_chunk=1 << 15), vis="wandb", ), description="Neural Scene Graph implementation with vanilla-NeRF model for backgruond and object models.", )
> 
> Traceback (most recent call last): File "/home/8/anaconda3/envs/SUDS/bin/ns-train", line 8, in sys.exit(entrypoint()) File "/home/8/mars/nerfstudio/nerfstudio/scripts/train.py", line 262, in entrypoint main( File "/home/8/mars/nerfstudio/nerfstudio/scripts/train.py", line 248, in main launch( File "/home/8/mars/nerfstudio/nerfstudio/scripts/train.py", line 187, in launch main_func(local_rank=0, world_size=world_size, config=config) File "/home/8/mars/nerfstudio/nerfstudio/scripts/train.py", line 101, in train_loop trainer.setup() File "/home/8/mars/nerfstudio/nerfstudio/engine/trainer.py", line 151, in setup self.pipeline = self.config.pipeline.setup( File "/home/8/mars/nerfstudio/nerfstudio/configs/base_config.py", line 58, in setup return self._target(self, **kwargs) File "/home/8/mars/nsg/nsg_pipeline.py", line 92, in **init** self._model = config.model.setup( File "/home/8/mars/nerfstudio/nerfstudio/configs/base_config.py", line 58, in setup return self._target(self, **kwargs) File "/home/8/mars/nerfstudio/nerfstudio/models/base_model.py", line 82, in **init** self.populate_modules() # populate the modules File "/home/8/mars/nsg/models/scene_graph.py", line 205, in populate_modules object_models = { File "/home/8/mars/nsg/models/scene_graph.py", line 206, in key: self.config.object_model_template.setup( File "/home/8/mars/nerfstudio/nerfstudio/configs/base_config.py", line 58, in setup return self._target(self, **kwargs) File "/home/8/mars/nerfstudio/nerfstudio/models/base_model.py", line 82, in **init** self.populate_modules() # populate the modules File "/home/8/mars/nsg/models/car_nerf.py", line 98, in populate_modules for idx, _ in self.car_latents.items(): AttributeError: 'NoneType' object has no attribute 'items'

Hi!
1. If you don't want to use our category-level object model, you should ensure `use_car_latents=False` and your `object_model_template` **is not** `CarNeRFModelConfig`.
2. If you train with KITTI 0002, you need to use `latent_codes02.pt` for `car_object_latents_path`  instead of `latent_codes06.pt`.

**Comment by jelleopard** [comment]
Thanks for you reply. I tested your metioned methed on kitti 0002, but it also have errors.

I've generated panoptic_maps graphs according to this script mars/scripts/panoptic_map_generator.py. but, the file( mars/data/kitti/panoptic_maps/colors/0006.txt) is only for scene 0006, how do you generate 0002 and 0001. What is the purpose of this file？

launch.json: 
{
      "name": "KITTI_Recon_NSG_Car_Depth",
      "type": "python",
      "request": "launch",
      "program": "nerfstudio/nerfstudio/scripts/train.py",
      "console": "integratedTerminal",
      "args": [
        "nsg-kitti-car-depth-recon",
        "--experiment_name",
        "NSG KITTI-0002",
        "--data",
        "/home/*/mars/data/kitti/training/image_02/0002",
      ]
    },
cicai_configs.py
KITTI_Recon_NSG_Car_Depth = MethodSpecification(
    config=TrainerConfig(
        method_name="nsg-kitti-car-depth-recon",
        steps_per_eval_image=STEPS_PER_EVAL_IMAGE,
        steps_per_eval_all_images=STEPS_PER_EVAL_ALL_IMAGES,
        steps_per_save=STEPS_PER_SAVE,
        max_num_iterations=MAX_NUM_ITERATIONS,
        save_only_latest_checkpoint=False,
        mixed_precision=False,
        use_grad_scaler=True,
        log_gradients=True,
        pipeline=NSGPipelineConfig(
            datamanager=NSGkittiDataManagerConfig(
                dataparser=NSGkittiDataParserConfig(
                    use_car_latents=True,
                    use_depth=True,
                    car_object_latents_path=Path(
                        "/home/*/mars/latents/KITTI-MOT/car-object-latents/latent_codes02.pt"
                    ),
                    split_setting="reconstruction",
                    car_nerf_state_dict_path=Path("/home/*/mars/latents/KITTI-MOT/car-nerf-state-dict/epoch_670.ckpt"),
                ),
                train_num_rays_per_batch=4096,
                eval_num_rays_per_batch=4096,
                camera_optimizer=CameraOptimizerConfig(mode="off"),
            ),
            model=SceneGraphModelConfig(
                background_model=NerfactoModelConfig(),
                object_model_template=CarNeRFModelConfig(_target=CarNeRF),
                object_representation="class-wise",
                object_ray_sample_strategy="remove-bg",
            ),
        ),
        optimizers={
            "background_model": {
                "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
            "learnable_global": {
                "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
            "object_model": {
                "optimizer": RAdamOptimizerConfig(lr=5e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
        },
        # viewer=ViewerConfig(num_rays_per_chunk=1 << 15),
        vis="wandb",
    ),
    description="Neural Scene Graph implementation with vanilla-NeRF model for backgruond and object models.",
)


error:
Traceback (most recent call last):
  File "/home/sunpenghui/anaconda3/envs/SUDS/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/sunpenghui/mars/nerfstudio/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/sunpenghui/mars/nerfstudio/nerfstudio/scripts/train.py", line 248, in main
    launch(
  File "/home/sunpenghui/mars/nerfstudio/nerfstudio/scripts/train.py", line 187, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/sunpenghui/mars/nerfstudio/nerfstudio/scripts/train.py", line 102, in train_loop
    trainer.train()
  File "/home/sunpenghui/mars/nerfstudio/nerfstudio/engine/trainer.py", line 242, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/home/sunpenghui/mars/nerfstudio/nerfstudio/utils/profiler.py", line 91, in inner
    out = func(*args, **kwargs)
  File "/home/sunpenghui/mars/nerfstudio/nerfstudio/engine/trainer.py", line 446, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "/home/sunpenghui/mars/nerfstudio/nerfstudio/utils/profiler.py", line 91, in inner
    out = func(*args, **kwargs)
  File "/home/sunpenghui/mars/nsg/nsg_pipeline.py", line 134, in get_train_loss_dict
    model_outputs = self.model(ray_bundle)
  File "/home/sunpenghui/anaconda3/envs/SUDS/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sunpenghui/mars/nerfstudio/nerfstudio/models/base_model.py", line 140, in forward
    return self.get_outputs(ray_bundle)
  File "/home/sunpenghui/mars/nsg/models/scene_graph.py", line 443, in get_outputs
    result = model.inference_without_render(ray_obj)
  File "/home/sunpenghui/mars/nsg/models/car_nerf.py", line 228, in inference_without_render
    self.car_latents[int(obj_id)].view(1, -1).to(obj_id.device),
KeyError: 3

**Comment by jelleopard** [comment]
> 

Thank you very much.
There is only one file under the directory of car-nerf-state-dict.
mars/latents/KITTI-MOT/car-nerf-state-dict/epoch_670.ckpt
Are 0002 and 0001 used differently? If not can you provide the required documentation?

**Comment by xBeho1der** [comment]
> > 
> 
> Thank you very much. There is only one file under the directory of car-nerf-state-dict. mars/latents/KITTI-MOT/car-nerf-state-dict/epoch_670.ckpt Are 0002 and 0001 used differently? If not can you provide the required documentation?

We use the same checkpoint for all sequences in one dataset. Concretely, we use `epoch_670.ckpt` for KITTI-MOT.

**Comment by xBeho1der** [comment]
1. Please refer to `0006.txt` and `scripts/panoptic_map_generator`, you can easily generate colormap for different sequences. We provide our own `panoptic_maps` as a demo. For more information, please refer to #2.
![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/afd269f4-11d4-4436-a6a8-c4ab9f10e51e)

> Thanks for you reply. I tested your metioned methed on kitti 0002, but it also have errors.
> 
> I've generated panoptic_maps graphs according to this script mars/scripts/panoptic_map_generator.py. but, the file( mars/data/kitti/panoptic_maps/colors/0006.txt) is only for scene 0006, how do you generate 0002 and 0001. What is the purpose of this file？
> 
> launch.json: { "name": "KITTI_Recon_NSG_Car_Depth", "type": "python", "request": "launch", "program": "nerfstudio/nerfstudio/scripts/train.py", "console": "integratedTerminal", "args": [ "nsg-kitti-car-depth-recon", "--experiment_name", "NSG KITTI-0002", "--data", "/home/_/mars/data/kitti/training/image_02/0002", ] }, cicai_configs.py KITTI_Recon_NSG_Car_Depth = MethodSpecification( config=TrainerConfig( method_name="nsg-kitti-car-depth-recon", steps_per_eval_image=STEPS_PER_EVAL_IMAGE, steps_per_eval_all_images=STEPS_PER_EVAL_ALL_IMAGES, steps_per_save=STEPS_PER_SAVE, max_num_iterations=MAX_NUM_ITERATIONS, save_only_latest_checkpoint=False, mixed_precision=False, use_grad_scaler=True, log_gradients=True, pipeline=NSGPipelineConfig( datamanager=NSGkittiDataManagerConfig( dataparser=NSGkittiDataParserConfig( use_car_latents=True, use_depth=True, car_object_latents_path=Path( "/home/_/mars/latents/KITTI-MOT/car-object-latents/latent_codes02.pt" ), split_setting="reconstruction", car_nerf_state_dict_path=Path("/home/*/mars/latents/KITTI-MOT/car-nerf-state-dict/epoch_670.ckpt"), ), train_num_rays_per_batch=4096, eval_num_rays_per_batch=4096, camera_optimizer=CameraOptimizerConfig(mode="off"), ), model=SceneGraphModelConfig( background_model=NerfactoModelConfig(), object_model_template=CarNeRFModelConfig(_target=CarNeRF), object_representation="class-wise", object_ray_sample_strategy="remove-bg", ), ), optimizers={ "background_model": { "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15), "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000), }, "learnable_global": { "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15), "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000), }, "object_model": { "optimizer": RAdamOptimizerConfig(lr=5e-3, eps=1e-15), "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000), }, }, # viewer=ViewerConfig(num_rays_per_chunk=1 << 15), vis="wandb", ), description="Neural Scene Graph implementation with vanilla-NeRF model for backgruond and object models.", )
> 
> error: Traceback (most recent call last): File "/home/sunpenghui/anaconda3/envs/SUDS/bin/ns-train", line 8, in sys.exit(entrypoint()) File "/home/sunpenghui/mars/nerfstudio/nerfstudio/scripts/train.py", line 262, in entrypoint main( File "/home/sunpenghui/mars/nerfstudio/nerfstudio/scripts/train.py", line 248, in main launch( File "/home/sunpenghui/mars/nerfstudio/nerfstudio/scripts/train.py", line 187, in launch main_func(local_rank=0, world_size=world_size, config=config) File "/home/sunpenghui/mars/nerfstudio/nerfstudio/scripts/train.py", line 102, in train_loop trainer.train() File "/home/sunpenghui/mars/nerfstudio/nerfstudio/engine/trainer.py", line 242, in train loss, loss_dict, metrics_dict = self.train_iteration(step) File "/home/sunpenghui/mars/nerfstudio/nerfstudio/utils/profiler.py", line 91, in inner out = func(*args, **kwargs) File "/home/sunpenghui/mars/nerfstudio/nerfstudio/engine/trainer.py", line 446, in train_iteration _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step) File "/home/sunpenghui/mars/nerfstudio/nerfstudio/utils/profiler.py", line 91, in inner out = func(*args, **kwargs) File "/home/sunpenghui/mars/nsg/nsg_pipeline.py", line 134, in get_train_loss_dict model_outputs = self.model(ray_bundle) File "/home/sunpenghui/anaconda3/envs/SUDS/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "/home/sunpenghui/mars/nerfstudio/nerfstudio/models/base_model.py", line 140, in forward return self.get_outputs(ray_bundle) File "/home/sunpenghui/mars/nsg/models/scene_graph.py", line 443, in get_outputs result = model.inference_without_render(ray_obj) File "/home/sunpenghui/mars/nsg/models/car_nerf.py", line 228, in inference_without_render self.car_latents[int(obj_id)].view(1, -1).to(obj_id.device), KeyError: 3

**Comment by jelleopard** [comment]
Are your experimental results for KITTI-0006 scenarios only? First Frame = 5 Last Frame = 260 used?
<html>
<body>


PSNR | SSIM
-- | --
KITTI-MOT | 0006 | 5 | 260 | Reconstruction | 29.06 | 0.885


</body>
</html>
