### ISSUE TITLE
Why the PSNR is different

### ISSUE THREAD

**Issue by AIBUWAN** [OPEN-AIR-SUN/mars#110]
In the paper, KITTI-75% is 24.23, but in KITTI-MOT 75% is 27.32. What is the difference between these two types of assessments?
![2023-11-27-19:36](https://github.com/OPEN-AIR-SUN/mars/assets/107452659/0a6427a4-1d8c-42c2-bdd4-f35ed2a083e3)
![2023-11-27-19:35](https://github.com/OPEN-AIR-SUN/mars/assets/107452659/67475fbb-037b-4727-9e3d-09291cee7fbd)

**Comment by xBeho1der** [comment]
Hi! @AIBUWAN 

There are no differences between these two types of assessments. However, there may be slight differences in the configurations.

The results in the paper are based on the previous version of our code. The current version on the github page contains the latest results, which were run with the update code.
