### ISSUE TITLE
Older versions of nerfstudio are not supported？

### ISSUE THREAD

**Issue by why529913** [OPEN-AIR-SUN/mars#111]
******/mars-master$ ns-train mars-vkitti-car-depth-recon --data /data/vkitti/Scene06/clone
╭─ Parsing error ─────────────────────────────────────╮
│ Argument                                            │
│ {nerfacto,depth-nerfacto,instant-ngp,instant-ngp-bo │
│ unded,mipnerf,semantic-nerfw,vanilla-nerf,tensorf,d │
│ nerf,phototourism,nerfplayer-nerfacto,nerfplayer-ng │
│ p}: invalid choice: 'mars-vkitti-car-depth-recon'   │
│ (choose from 'nerfacto', 'depth-nerfacto',          │
│ 'instant-ngp', 'instant-ngp-bounded', 'mipnerf',    │
│ 'semantic-nerfw', 'vanilla-nerf', 'tensorf',        │
│ 'dnerf', 'phototourism', 'nerfplayer-nerfacto',     │
│ 'nerfplayer-ngp')                                   │
│ ─────────────────────────────────────────────────── │
│ For full helptext, run ns-train --help    

nerfstudio == 0.1.18
Older versions of nerfstudio are not supported？

**Comment by wuzirui** [comment]
We haven't tested on older versions, I think we might have used some of the new features in nerfstudio, so maybe needs to change a little bit if you want to downgrade the nerfstudio version.
