### ISSUE TITLE
Error: latents not exist？

### ISSUE THREAD

**Issue by why529913** [OPEN-AIR-SUN/mars#112]
Saving config to:                                                                    experiment_config.py:136
           outputs/clone/mars-vkitti-car-depth-recon/2023-12-02_131648/config.yml                                       
           Saving checkpoints to:                                                                         trainer.py:135
           outputs/clone/mars-vkitti-car-depth-recon/2023-12-02_131648/nerfstudio_models                                
Loading poses from: data/vkitti/Scene06/clone/pose.txt
Loading bbox from: data/vkitti/Scene06/clone/bbox.txt
Loading info from: data/vkitti/Scene06/clone/info.txt
[array([0.]), array([1.]), array([2.]), array([7.]), array([8.]), array([3.]), array([9.]), array([4.]), array([5.]), array([12.]), array([6.]), array([10.]), array([11.]), array([13.])] in this scene
Error: latents not exist

question： Why did I change the latens path under mars/cicai_configs.py, when I ran the script（ns-train mars-vkitti-car-depth-recon --data ./data/vkitti/Scene06/clone）, the config was still the same 
                “”“
                use_car_latents=True,
                car_object_latents_path=PosixPath('/DATA_EDS/liuty/ckpts/pretrain/car_nerf/vkitti/latents/latent_codes06
.pt'),
                car_nerf_state_dict_path=PosixPath('/DATA_EDS/liuty/ckpts/pretrain/car_nerf/vkitti/epoch_805.ckpt'),
              ”“”

**Comment by xBeho1der** [comment]
Hi @why529913 

Maybe you can try specific config like:

```
--pipeline.datamanager.dataparser.car-nerf-state-dict-path /DATA_EDS/liuty/ckpts/pretrain/car_nerf/epoch_670.ckpt --pipeline.datamanager.dataparser.car-object-latents-path /DATA_EDS/liuty/ckpts/pretrain/car_nerf/kitti_mot/latents/latent_codes06.pt
```

Or you can install mars-nerfstudio locally, then you can modify the config in mars repo.

```
cd path/to/mars/repo
pip uninstall mars-nerfstudio
pip install -e .
```

**Comment by why529913** [comment]
It worked, thank you very much！

**Comment by Tausc** [comment]
hello, i met the same problem when training on kitti-MOT. But when I added this args and run:
` ns-train mars-kitti-car-depth-recon --data /data0/dataset/kitti_tracking/training/image_02/0006 --pipeline.datamanager.dataparser.car-nerf-state-dict-path /data0/user/mars/latents/KITTI-MOT/car-nerf-state-dict/epoch_670.ckpt `
It turned out that:
 Unrecognized arguments: --pipeline.datamanager.dataparser.car-nerf-state-dict-path
 
![image](https://github.com/OPEN-AIR-SUN/mars/assets/50770432/06bd4889-e091-4a81-bfed-057e3f07ec0a)
how could I revise the latens path? Thank you!

**Comment by Tausc** [comment]
> hello, i met the same problem when training on kitti-MOT. But when I added this args and run: `ns-train mars-kitti-car-depth-recon --data /data0/dataset/kitti_tracking/training/image_02/0006 --pipeline.datamanager.dataparser.car-nerf-state-dict-path /data0/user/mars/latents/KITTI-MOT/car-nerf-state-dict/epoch_670.ckpt` It turned out that: Unrecognized arguments: --pipeline.datamanager.dataparser.car-nerf-state-dict-path
> 
> ![image](https://private-user-images.githubusercontent.com/50770432/292193132-06bd4889-e091-4a81-bfed-057e3f07ec0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNjQ4MDksIm5iZiI6MTcwMzE2NDUwOSwicGF0aCI6Ii81MDc3MDQzMi8yOTIxOTMxMzItMDZiZDQ4ODktZTA5MS00YTgxLWJmZWQtMDU3ZTNmMDdlYzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDEzMTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YjhiYzNhNjIxOWFjOTgyMTk4YTEyY2YwOTZjNGMyMjQwNWJhMjhiN2EzZWIzYThmN2EyMjI5MWY0YTE5NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NV-oVEiGI8cN03I5d1NZhAuNzWzrm7SP8zBnRjhY93M) how could I revise the latens path? Thank you!

i tried` pip install -e .` and now it could work! thank you
