### ISSUE TITLE
Instance-wise Editing Codes not found

### ISSUE THREAD

**Issue by mengZhang9611** [OPEN-AIR-SUN/mars#113]
Hi Mars team,

first thanks for publishing such great work!
In your paper, the results of instance-wise editing are presented(chapter 3.2) which are quite impressive. However, when I looked into the codes to find the corresponding parts for editing I just could not find. I was wondering is this part codes released in the main branch? And if yes, could you give me some hints on under which directory could we find it? 

Thanks a lot in advance.

**Comment by xBeho1der** [comment]
Hi! @mengZhang9611 

Thanks for your interest. There are some relevant issues concerning Instance-wise editing, you can refer to #105, #35, and #40. The code is in `scripts/cicai_render.py`.
