### ISSUE TITLE
move the objects of VKITTI to a custom scene

### ISSUE THREAD

**Issue by sonnefred** [OPEN-AIR-SUN/mars#114]
Hi, I'm trying to insert a car which you trained on VKITTI to my own scene, but the result is a bit strange (like the following image). As you can see, the color of the car is too light. Do you have any suggestion about this? Thanks!
<img width="185" alt="图片" src="https://github.com/OPEN-AIR-SUN/mars/assets/66628395/04b08ae7-d655-41ef-8f0a-c20867a6a1ce">

**Comment by wuzirui** [comment]
Yes this is a known issue of NeRF-based representation that point densities are not large enough. I would suggest using some constraints on the densities inside the obj bounding boxes to be either 1 or 0. You could also try with sdf-based representations.

**Comment by sonnefred** [comment]
> Yes this is a known issue of NeRF-based representation that point densities are not large enough. I would suggest using some constraints on the densities inside the obj bounding boxes to be either 1 or 0. You could also try with sdf-based representations.

Thanks for your reply, and I will try it.

**Comment by sonnefred** [comment]
Btw, when do you plan to relaese the project of CarNeRF, since the rendered foregroud object is not good enough now and I'd like to try CarNeRF? Thanks!

**Comment by wuzirui** [comment]
Hi, I think the CarNeRF code will be available after the publish of the CarStudio project.

**Comment by sonnefred** [comment]
> Hi, I think the CarNeRF code will be available after the publish of the CarStudio project.

OK, do you have a relatively specific plan, such as an approximate date? Thanks.

**Comment by wuzirui** [comment]
> > Hi, I think the CarNeRF code will be available after the publish of the CarStudio project.
> 
> 
> 
> OK, do you have a relatively specific plan, such as an approximate date? Thanks.

Please inquire the carstudio authors thx🤣
