### ISSUE TITLE
No checkpoint directory

### ISSUE THREAD

**Issue by HCCda** [OPEN-AIR-SUN/mars#116]
Hi~When I render with your pre-trained model,I have encountered a  question that" 
 No checkpoint directory found at  outputs/kitti-recon-65-120/mars-kitti-car-depth-recon/2023-10-30_212654/nerfstudio_models",I have made new directories and put the file "step-000400000.ckpt " into it ,how can I solve this problem?Thank you for you reply.   
![Uploading 2023-12-14 17-19-47屏幕截图.png…]()

**Comment by xBeho1der** [comment]
Hi! @HCCda 

It seems like you haven't uploaded the screenshot successfully. But I propose you make a directory using the same path shown above.

**Comment by HCCda** [comment]
> Hi! @HCCda
> 
> It seems like you haven't uploaded the screenshot successfully. But I propose you make a directory using the same path shown above.

Hi,Thank you for you reply. I have made the directory like above.The path of checkpoint file is /home/a/data/outputs/kitti-recon-65-120/mars-kitti-car-depth-recon/2023-10-30_212654/nerfstudio_models/step-000400000.ckpt. It seems that the code could not find the checkpoint file correctly. How can I change the checkpoints path in the program?

**Comment by Nplace-su** [comment]
relative directory issue? Given your path of ckpt file, it works only if your code is also under /home/a/data/

**Comment by xBeho1der** [comment]
1. Maybe you can modify the `load_checkpoint` in config.yml for your checkpoint path?
2. The default option is to locate the output directory in mars repo, you can move the outputs directory in mars repository, like `mars/outputs/kitti-recon-65-120/mars-kitti-car-depth-recon/2023-10-30_212654/nerfstudio_models/step-000400000.ckpt`.

**Comment by HCCda** [comment]
> relative directory issue? Given your path of ckpt file, it works only if your code is also under /home/a/data/ I guess you might solve this by debugging deeper into this https://github.com/nerfstudio-project/nerfstudio/blob/88873ef3abac208d0fe6e90d06c044900762b01a/nerfstudio/utils/eval_utils.py#L101


That really the relative directory issue.I have solved the problem,thank you.
I meet an another question,I want to render the depth images,I change the "rgb" into "depth" as following: "the rendered_output_names: List[str] = field(default_factory=lambda: ["depth"])". But it has an error that 'str' object has no attribute 'suffix' in "data_utils.py" .What is the reason for this situation？

**Comment by xBeho1der** [comment]
Hi @HCCda 

You can try adding the following lines in `data_utils.py`.

```python
    # resolve the filepath
    if not isinstance(filepath, Path):
        filepath = Path(filepath)
```
