### ISSUE TITLE
How to create and save new latent codes?

### ISSUE THREAD

**Issue by chizhangsysu** [OPEN-AIR-SUN/mars#118]
Dear MARS team, thank you for opensourcing this awesome work! I am trying to train a new KITTI scene but encountered some problems. Can you help with my following confusions?:

- How can I create a new `latent_codes_car_van_truck.pt` for a new scene? This .pt file seems crucial for a training pipeline to function properly, but I couldn't find any logic about how to create these latent codes, except to load from a pre-existing .pt file.
 
- There are 762 latent codes in `latent_codes_car_van_truck.pt` but there are <20 objects in the 0006 scene. It looks like an object owns a latent code for each frame it appeared in. Why do we need so many latent codes for an object instead of just one?
  
I am working on the master branch (commit ID: 5d7567504220f9a8a09aa20a199954f481a26484).

Thank you!

**Comment by wuzirui** [comment]
Hi, as I responded in another issue of yours, these are the features from carnerf, for each view of the same instance, they provide a latent code. We in the parsing stage aggregate them into one.

**Comment by chizhangsysu** [comment]
I see. Thank you!

**Comment by wuzirui** [comment]
Hey guys, as a kind reminder, the CarStudio paper is accepted by RAL and their code is available now at https://github.com/lty2226262/Car_studio
