### ISSUE TITLE
the dynamic objects and the background are not separated fully？

### ISSUE THREAD

**Issue by szhang963** [OPEN-AIR-SUN/mars#120]
Hello，I am interested in your excellent work. I want to use my custom dataset to train mars for the decomposion of dynamic objects and background. I first convert my dataset to kitti format, and use the kitti dataparser. The render result is flollowing: 
![image](https://github.com/OPEN-AIR-SUN/mars/assets/38983719/9c0006a9-4c9a-42c9-9e32-bf96a35576fc)
the original image is:
![image](https://github.com/OPEN-AIR-SUN/mars/assets/38983719/d70e3fa4-441f-4dba-b2f6-848dff0be116)
.
could you give me some help?
Thanks a lot.

**Comment by xBeho1der** [comment]
Hi! @szhang963 

Thanks for your interest. Maybe you can try tuning `scale_factor`. #58

**Comment by szhang963** [comment]
Thanks for your reply. the scale_factor  in this running is setting to 1. My rendered images have the folllowing questions: 1. the background is most blur? when the dynamic objects are removed, the background is blur like rays. when the dynamic objects are not removed, the background is just not clear. 2. Dynamic objects are not removed fully. sometimes, only a object close to the camera can be removed, the far object is reserved in background? 
There exist some problem for the camera poses or object poses?  I can provide some logs if them are helpful for the analysis of question.
Thanks a lot for your any reply.
