### ISSUE TITLE
background blur in kitti 0003 data

### ISSUE THREAD

**Issue by szhang963** [OPEN-AIR-SUN/mars#122]
Hi, mars team, I train a nerf model using 0003 scene for 30~90 frames. I didn't use depth, carnerf weight and semantic mask in the training. The maximum iterations are 50000. 
I found the scene that ego car is moving is usual blur as the figure 1.
![image](https://github.com/OPEN-AIR-SUN/mars/assets/38983719/dd926804-af1e-4bf1-ba69-f0492034e661)
And I also found the dynamic object close to ego car usunaly has a ghost shadow as the following figure.
![image](https://github.com/OPEN-AIR-SUN/mars/assets/38983719/7f2f4bcd-bcdf-48ef-acb5-67f9f5940239)

The training logs are following: 
![image](https://github.com/OPEN-AIR-SUN/mars/assets/38983719/6e08e6f9-f1a5-4662-8976-121a1f656723)

Could you explain these cases?  I met the same problem in my private data.

Thank you in advance.

**Comment by xBeho1der** [comment]
Hi! @szhang963 

While the ego car is moving, maybe using depth will help with the performance. It seems that there are many shadowed areas in this scene, which will also affect the training performance.

Perhaps a longer sequence could help with decoupling the object from the background.

**Comment by szhang963** [comment]
Thanks for your reply. A longer sequence means a larger memory, could you share a solution for saving the memory? Thank you very much.

**Comment by xBeho1der** [comment]
Hi! @szhang963 

Maybe you can refer to #85.

**Comment by szhang963** [comment]
Hi, @xBeho1der 
I follow the process of generating the depth map using [monocular depth estimation model](https://github.com/theNded/mini-omnidata). However, the result is poorer than the depth map you provided, like these (my, your, and image):
![image](https://github.com/OPEN-AIR-SUN/mars/assets/38983719/bc145d28-d1bd-45fd-b7ef-ac7105003734)
![image](https://github.com/OPEN-AIR-SUN/mars/assets/38983719/a9f5f1e6-4e19-4bf4-923b-6f4cde2a02ee)
![image](https://github.com/OPEN-AIR-SUN/mars/assets/38983719/0e6873d7-47aa-4c19-90e9-e906b3d43861)

Could you provide some causes to resolve this? Thank you in advance.

**Comment by xBeho1der** [comment]
Hi! @szhang963 

Try modifying the resize part?
![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/e87cb807-7815-4d33-8956-12483cc46f3b)

**Comment by szhang963** [comment]
Hi @xBeho1der. Yes, I have fixed it. However, the rendered RGB images are still blurred using the depth loss when the ego car is moving (e.g. 006, 190-249).
![image](https://github.com/OPEN-AIR-SUN/mars/assets/38983719/d860e38f-51ef-4ca9-b50f-9f8b8f547dbf)
Could you provide a training result for the scene?
