### ISSUE TITLE
Where to get the specific parameters of an object in a  frame?

### ISSUE THREAD

**Issue by RZkiller** [OPEN-AIR-SUN/mars#125]
Thank you for your work,

I am trying to get he specific parameter information of an object in a  frame, like pose, rotation, object_id.

<img width="560" alt="截屏2024-01-11 12 00 18" src="https://github.com/OPEN-AIR-SUN/mars/assets/87565692/422a27f7-c9d7-4b51-bd96-a408310e58d3">

I noticed that the objects in the scene can be edited with the code above, but we don't know what the specific xyz, yaw, and object_id of each object are.

Could you give me some hints? Thanks a lot.

**Comment by xBeho1der** [comment]
Hi! @RZkiller 

Thanks for your reply.

The last dimension of the pose is object_id and dim. The code above means adding 0.5 in the z-direction to the vehicle with an object ID of 1. The positive direction of the z-axis is relative to the world coordinate.

**Comment by RZkiller** [comment]
@xBeho1der Thank you for your reply. Refer to issue #105, I know the meaning of each dimension of pose/rotation and how to edit an object that already exists in the scene.

The question is that when I want to add a new car in the scene, I need to set specific pose, rotation information. But I notice that in a frame, the shape of pose/rotation of an object is (375, 1242, 3) and (375, 1242) respectively.

<img width="334" alt="截屏2024-01-13 23 12 07" src="https://github.com/OPEN-AIR-SUN/mars/assets/87565692/b26dffc9-cea9-48b0-96a1-ed4777ef0746">


Does this mean if I want to add a new car, I need to provide the pose/rotation of the car with shape of (375, 1242, 3)/(375, 1242)?     P.S.  looks like pixel level parameter?
If not, how can i get or set the specific pose/rotation values of a certain car in the scene?
