### ISSUE TITLE
The viewer cannot see any results during training.

### ISSUE THREAD

**Issue by Gniniug123** [OPEN-AIR-SUN/mars#128]
Thank you so much for your outstanding open source work! But during my training process, it looked strange from the viewer's webpage. Why is it still like this after iterating 400,000 times? My modifications to cicia_config.py only include the data, weight paths, and changing the graphic sequence from 65-120 to 65-100. Can you help me find out what the problem is?
![_tmp_dingtalkgov_qt_clipbord_pic_5](https://github.com/OPEN-AIR-SUN/mars/assets/109570978/9ccb4261-4171-45c2-bb88-7ebf159a7653)

**Comment by Nplace-su** [comment]
Click on a camera image thumbnail in the viewer, you will switch to the view of the camera you clicked, then you can see a meaningful render result from that view.

**Comment by xBeho1der** [comment]
Hi! @Gniniug123 

Maybe #54 will help.

**Comment by Gniniug123** [comment]
@xBeho1der  Thank you very much for your reply, I will try it！
