### ISSUE TITLE
How to train CarNeRF on custom dataset?

### ISSUE THREAD

**Issue by tendo518** [OPEN-AIR-SUN/mars#129]
Thank you for your fantastic work!

I am trying to use mars with custom dataset, so pretrained car latent is unusable. 

It seems using `object_model_template=CarNeRFModelConfig(_target=CarNeRF)` in configuration will ask for existed car latent, however what I can get now is just your provided ones (which is trained on kitti/vkitti). 

So how can I train the CarNeRF on my custom dataset from scratch?

**Comment by xBeho1der** [comment]
Hi! @tendo518 

CarNeRF is actually another recent work of our lab ([URL](https://lty2226262.github.io/car-studio/)), please refer to their project page for more information.

**Comment by tendo518** [comment]
> Hi! @tendo518
> 
> CarNeRF is actually another recent work of our lab ([URL](https://lty2226262.github.io/car-studio/)), please refer to their project page for more information.

Thanks for your reply!

Since code of Car-stuido is not open-sourced yet, one method to train custom dataset is `object_model_template=NerfactoModelConfig()` to use bare nerf for car modeling?

Or I can use CarNeRF pretrained in kitti/vkitti, will this hurt accuracy of reconstruction results on custom scene?

Besides, sorry for duplicating, if you can point out where I can find duplicated content, it will help me a lot (apologize for my bad searching skill)

**Comment by xBeho1der** [comment]
Hi!

As for searching the duplicated content, you can search it [here](https://github.com/OPEN-AIR-SUN/mars/issues) for issues might help.

Using CarNeRF pretrained in Kitti/vkitti seems infeasible as different datasets will use different object id. If the latent code doesn't have the corresponding object id it will raise a KeyError.

Maybe you can generate a latent code randomly, then optimize and save it during the training.

**Comment by tendo518** [comment]
> Hi!
> 
> As for searching the duplicated content, you can search it [here](https://github.com/OPEN-AIR-SUN/mars/issues) for issues might help.
> 
> Using CarNeRF pretrained in Kitti/vkitti seems infeasible as different datasets will use different object id. If the latent code doesn't have the corresponding object id it will raise a KeyError.
> 
> Maybe you can generate a latent code randomly, then optimize and save it during the training.

Thanks to your help, I will try to use random latent code generation

**Comment by Yurri-hub** [comment]
> > Hi!
> > As for searching the duplicated content, you can search it [here](https://github.com/OPEN-AIR-SUN/mars/issues) for issues might help.
> > Using CarNeRF pretrained in Kitti/vkitti seems infeasible as different datasets will use different object id. If the latent code doesn't have the corresponding object id it will raise a KeyError.
> > Maybe you can generate a latent code randomly, then optimize and save it during the training.
> 
> Thanks to your help, I will try to use random latent code generation

Hi! Have you tried to use random latent code generation? Perhaps we can discuss this issue. @tendo518

**Comment by wuzirui** [comment]
Hey guys, as a kind reminder, the CarStudio paper is accepted by RAL and their code is available now at https://github.com/lty2226262/Car_studio
