### ISSUE TITLE
Pretrained models for car NeRFs

### ISSUE THREAD

**Issue by yanjh97** [OPEN-AIR-SUN/mars#131]
Hi, thanks for your great work. I downloaded pretrained models and run render scripts following README, but it outputs:
![image](https://github.com/OPEN-AIR-SUN/mars/assets/54617163/c5f94d8f-3685-4b46-aea2-11d9be3b0beb)
Where can I find pretrained models for car NeRFs and latents in the below?
![image](https://github.com/OPEN-AIR-SUN/mars/assets/54617163/24c9033b-234d-47a8-a355-f9225342c1c4)
Looking forward to your reply.

**Comment by xBeho1der** [comment]
Hi! @yanjh97 

Thanks for your reply! You can find the download link in `README.md`.

https://drive.google.com/drive/folders/1E4YjMwkDbRsF4Hb1UK0iBDkz-tFVx3Me

**Comment by xBeho1der** [comment]
<img width="887" alt="image" src="https://github.com/OPEN-AIR-SUN/mars/assets/107318439/6e5b6a60-d360-41b4-a656-9b24fea35f54">
