### ISSUE TITLE
Calib/0006.txt not found

### ISSUE THREAD

**Issue by amoghskanda** [OPEN-AIR-SUN/mars#134]
File "/app/mars/mars/data/mars_kitti_dataparser.py", line 167, in tracking_calib_from_txt
    f = open(calibration_path)
FileNotFoundError: [Errno 2] No such file or directory: '/data/kitti-MOT/training/calib/0006.txt'

I've dockerised it and structured the file system as mentioned in the documentation but I'm getting this error. Should I change any path in the config file? I tried passing absolute path as the parameter to `ns-train mars-kitti-car-depth-recon --data /data/kitti-MOT/training/image_02/0006` but did not work.

**Comment by xBeho1der** [comment]
Hi! @amoghskanda 

You can try installing the mars repo locally with `pip install -e .` such that you can train with the modification locally.

**Comment by xBeho1der** [comment]
Hi!

I'm trying to specify the dataset path locally, and I haven't encountered this issue.
