### ISSUE TITLE
KeyError: 0  

### ISSUE THREAD

**Issue by heiheishuang** [OPEN-AIR-SUN/mars#135]
Thanks for your fantastic work!

I am trying to use Mars to train the kitti-0000, but I got this error: KeyError:0

```
  File "/data/code/test-mars/mars/models/car_nerf.py", line 206, in inference_without_render
    self.car_latents[int(obj_id)].view(1, -1).to(obj_id.device),
KeyError: 0
```
I use the `latent_codes_car_van_truck.pt`，but this pt file only provides 10 obj latents, like this
<img src="https://github.com/OPEN-AIR-SUN/mars/assets/49268719/b64eacf9-0791-4bf9-b01d-29c20295aa48" width = "600"  alt="latents" align=center />
But kitti-0000 includes [array ([0.]), array ([3.]), array ([5.]), array ([4.]), array ([6.]), array ([9.])] in this scene
So how can I train the mars in kitti-0000?

Looking forward to your reply!

**Comment by xBeho1der** [comment]
Hi! @heiheishuang 

Thanks for your reply. We haven't provided the latent code for kitti-0000, you can train with nerfacto or randomize a latent code with the corresponding object id.

**Comment by heiheishuang** [comment]
Thanks for you reply!!!
May I ask if you will can provide the PSNR and other metrics for kitti-0000?
Looking forward to your reply!

**Comment by xBeho1der** [comment]
Hi! @heiheishuang 

Sorry that we haven't done any experiments on kitti-0000.
