### ISSUE TITLE
Adding a KITTI car into VKITTI scene

### ISSUE THREAD

**Issue by ChaofengWu0** [OPEN-AIR-SUN/mars#139]
Hi, thanks again for your great work, and I sincerely apologize for not knowing how to reopen issue I created before.
![image](https://github.com/OPEN-AIR-SUN/mars/assets/82070917/af784422-c704-4ffb-86a8-0e45d58080b0)
May I know how to add the KITTI car into the VKITTI scene?

**Comment by xBeho1der** [comment]
Hi! Thanks for your reply.

Maybe you can try editing the corresponding checkpoints,replace the parameters of the object model in the vkitti checkpoint with the parameters of the object model in the kitti checkpoint.
