### ISSUE TITLE
Index out of bounds while editing instances in Scene05

### ISSUE THREAD

**Issue by amoghskanda** [OPEN-AIR-SUN/mars#143]
Hey, I was editing the cars(instances) in Scene05 and I'm not able to edit the objects beyond the `obj_id` 4. Getting
IndexError: index 5 is out of bounds for dimension 2 with size 5

I checked the latent_codes for Scene05 and it contains objects with object ids >5. How do I edit those instances?
I'm well aware that the last 2 dimensions of pose are `obj_id` and `axis` and the last dimension of rotation is `obj_id`.
Passing an object id > 4 to pose and rotation is raising this error.

**Comment by xBeho1der** [comment]
Hi! @amoghskanda 

It's unrelated to the latent codes of the scene. The track_id of each object is related to both the sequence length and the objects in the scene. For instance, maybe you train a short sequence and there are only 5 cars in the whole sequence.

**Comment by amoghskanda** [comment]
alright. Thank you for the clarification.
