### ISSUE TITLE
Depth Maps generated for KITTI Scene-05 is 3-channel

### ISSUE THREAD

**Issue by amoghskanda** [OPEN-AIR-SUN/mars#152]
Hey! I went through the github issues regarding depth maps and didn't find anything conclusive. I used mini-omnidata(monocular depth estimation model) to generate depth maps for Scene-05 of KITTI dataset. However, the depth maps are not 1-channel like in Scene-06 of KITTI(completion_02). Can I train the model using the 3-channel depth maps or do I have to make changes in the code? I have the numpy arrays generated as well for the depth, incase that is needed to generated greyscale images.

**Comment by wuzirui** [comment]
Depth maps by definition are single-channel images. There's no reason from my side to allow for reading 3-channel depth maps. I would recommend changing your 3-channel images into single-channel ones via `depth_image = depth_image[..., 0]`.
#38

**Comment by amoghskanda** [comment]
Thank you for the reply. So, can the depth maps generated by mini-omnidata be directly used for training?

**Comment by wuzirui** [comment]
Not sure about the mini-omnidata format, but I believe you only need to change at most 1~2 lines of code to fix this.
