### ISSUE TITLE
ModuleNotFoundError: No module named 'nsg'

### ISSUE THREAD

**Issue by ChaofengWu0** [OPEN-AIR-SUN/mars#153]
![image](https://github.com/OPEN-AIR-SUN/mars/assets/82070917/cfbd9f9d-3d7d-4e0c-9426-df5c4193915e)
Hi, thanks for your great work. But I don't know what leads to this bug and how to fix it.

**Comment by Nplace-su** [comment]
“nsg” is something like outdated codes. Maybe you can try to update to the latest version.

**Comment by ChaofengWu0** [comment]
thank you!!!
