### ISSUE TITLE
Support required for Kitti360 dataset

### ISSUE THREAD

**Issue by gaurav00700** [OPEN-AIR-SUN/mars#154]
Hi @xBeho1der 
I am on working on training of Kitti360 dataset. 
I have developed the dataparser  for the same by following the data format suggested in the repo. 
But it seems that axis of camera and objects are not aligned when I am trying to visualize the poses of camera and object using debug visualizer . Refer below image.

It will be highly appreciated if you can suggest me any idea how to align the axis of camera and object.

![image](https://github.com/OPEN-AIR-SUN/mars/assets/108759160/6222bd49-79fd-4d6e-8557-6dc2b1051950)

**Comment by xBeho1der** [comment]
Thank you for raising this issue.
1. It appears that there might be a problem with the height, length, and width of the object bounding box. 
2. I suggest incorporating the world coordinate system orientation in the visualizer. You can see an example of how this can be implemented in [mars_pose_visualizer](https://github.com/wuzirui/mars_pose_visualizer).

**Comment by gaurav00700** [comment]
@xBeho1der  Thank you for the suggestions.
After matching yaw axis of camera poses and objects poses in world frame. Then I compared visualization result in debug visualizer between Kitti dataset and Kitti360. Axis of Kitti360 are aligned same as  Kitti but yaw angles of objects are not coming correctly in Kitti360. 
Any suggestion to fix the issue of objects yaw angle in Kitti360 ?

Here is visualization results:
 **Kitti360**
![image](https://github.com/OPEN-AIR-SUN/mars/assets/108759160/37a3744e-2f24-4e5e-a1a1-f684cb244efd)
**Kitti**
![image](https://github.com/OPEN-AIR-SUN/mars/assets/108759160/87f7fb61-771e-44c5-9dc6-1f736d4697a6)

**Comment by xBeho1der** [comment]
Hi! @gaurav00700 

Thanks for your reply! Perhaps you can refer to the following code. Different rotation axes should correspond to different rotation matrices, resulting in different outcomes.

https://github.com/OPEN-AIR-SUN/mars/blob/69b9bf9d992e6b9f4027dfdc2a741c2a33eef174/mars/data/mars_kitti_dataparser.py#L451-L456

https://github.com/OPEN-AIR-SUN/mars/blob/69b9bf9d992e6b9f4027dfdc2a741c2a33eef174/mars/data/mars_kitti_dataparser.py#L538-L556

**Comment by gaurav00700** [comment]
@xBeho1der , Thank you for the reply and support. 
Sorry, I shared the wrong image of Kitti360 is my last comment. I have updated the image in above comment.

There was problem in the yaw angle calculation. I have fixed the issue. Now camera and object poses are coming correctly.
Next, I will start training and share the results.

**Comment by dogooooo** [comment]
@gaurav00700 ，Thank you very much for sharing your process of solving it, what I am interested in knowing is if you can share the results of your training on KITTI 360?

**Comment by gaurav00700** [comment]
@dogooooo Hi... I started trained on one scene but results are not good overall. There is some bug with transformation. Z coordinates are incorrect. Unfortunately, I was not able to spend time to fix it that is why I did not post the results. I will again work on that after sometime.
