### ISSUE TITLE
training Error: latents not exist

### ISSUE THREAD

**Issue by TideQin** [OPEN-AIR-SUN/mars#156]
Do I need to train to get the .pt model file myself, or will the MARS program automatically train it?
/DATA_EDS/liuty/ckpts/pretrain/car_nerf/latent_codes_car_van_truck.pt

**Comment by TideQin** [comment]
![train_error_1](https://github.com/OPEN-AIR-SUN/mars/assets/9944313/c5cad2f2-7d31-4308-9ea8-2ed6a1ba0ced)

**Comment by TideQin** [comment]
![train_error_2](https://github.com/OPEN-AIR-SUN/mars/assets/9944313/da182874-3fe7-45af-a9ed-8cfe85e1d580)

**Comment by wuzirui** [comment]
please download the checkpoints （urls are in the readme） and modify the configs

**Comment by TideQin** [comment]
> please download the checkpoints （urls are in the readme） and modify the configs

Thank you zirui，Under your guidance, I resolved the issue after downloading the resources mentioned in the readme
![latent-1](https://github.com/OPEN-AIR-SUN/mars/assets/9944313/d52b021b-b4f5-46be-a85a-a87d0a94190a)
