### ISSUE TITLE
About the training setting.

### ISSUE THREAD

**Issue by jiangxb98** [OPEN-AIR-SUN/mars#158]
During training, are all images of a scene are fed into the training? Or break a scene into parts?

**Comment by JiantengChen** [comment]
Hi! @jiangxb98 

You can refer to the split in the data parser.
e.g. 
https://github.com/OPEN-AIR-SUN/mars/blob/69b9bf9d992e6b9f4027dfdc2a741c2a33eef174/mars/data/mars_kitti_dataparser.py#L1203-L1211
