### ISSUE TITLE
Translation and Rotation of the Actors with NVS

### ISSUE THREAD

**Issue by arda-num** [OPEN-AIR-SUN/mars#160]
![image](https://github.com/OPEN-AIR-SUN/mars/assets/78916039/6a6854f7-c6a7-4921-8ad3-63263a86ae3a)

Hello,

I am new to this field and I’m trying to understand the full pipeline for modifying actors, specifically regarding rotation and translation. I have a few questions:

  1. How can I rotate or translate actors within the code, similar to the provided image? I couldn’t find any implemented code for these modifications.
  2. Should I modify cicai.render.py and adjust the positions of each actor to achieve these changes?
  3. Alternatively, do I need to update the dataset to reflect these modifications?

Any guidance or examples would be greatly appreciated.
Thank you!

**Comment by JiantengChen** [comment]
Hi! @arda-num 

Thanks for your reply! There are some relevant issues concerning Instance-wise editing, you can refer to #105, #35, and #40. The code is in `scripts/cicai_render.py`.
