### ISSUE TITLE
Custom Dataset Preparation

### ISSUE THREAD

**Issue by VikasXitadel** [OPEN-AIR-SUN/mars#161]
Hi @JiantengChen ,
Thanks for your awesome work. I want to work on a custom dataset for reconstruction. So I am wondering how to convert the Pandaset dataset into the format which your mentioned [here](https://github.com/OPEN-AIR-SUN/mars?tab=readme-ov-file#vkitti2)

Any assistance is greatly appreciated.

**Comment by JiantengChen** [comment]
Hi! @VikasXitadel 

Thanks for your interest in our work. I suggest writing a new dataparser for PandaSet as there is a [devkit](https://github.com/scaleapi/pandaset-devkit) for data processing.
