### ISSUE TITLE
a questions about foreground rendering

### ISSUE THREAD

**Issue by xiao1874** [OPEN-AIR-SUN/mars#163]
Hello, First of all, thank you for your previous suggestion in the previous question #159 , I referred to your suggestion and used the **latent in car-studio** to reconstruct the foreground and used **NeRFacto** to reconstruct the background. It can be seen from the WANDB log that certain effects have been achieved on the foreground. 
The following image shows the foreground rendering result:
![objects_rgb_391000_ce360d09bdffb5a60621](https://github.com/OPEN-AIR-SUN/mars/assets/58030684/546c5ec1-7586-4a20-af6c-b19e73f31e72)

However, for the rendering of the final RGB image (foreground+background), the foreground pixels are too sparse, the picture shows (The red box is the foreground of the current frame)：
<img width="960" alt="00110" src="https://github.com/OPEN-AIR-SUN/mars/assets/58030684/d5398704-c03b-4c5b-ab3b-ce4f0297aa76">

 especially when editing the foreground (moving left or right),It is almost impossible to see the foreground pixels after they move . the picture shows (Foreground moves 2m to the left):
<img width="960" alt="00099" src="https://github.com/OPEN-AIR-SUN/mars/assets/58030684/7c8d487c-b366-4577-af3a-cb81ca748144">

 Can you provide some suggestions?
 Best !

**Comment by wuzirui** [comment]
Hi @xiao1874, our project does not support deformable objects (e.g. pedestrians, cyclists), but only models the rigid motion in driving scenes. To model deformable objects, I recommend OmniRe (https://ziyc.github.io/omnire) or other solutions for general dynamic scenes (e.g. K-Planes, Dynamic Gaussians, ...)

**Comment by xiao1874** [comment]
thx! 
I'll try it
