### ISSUE TITLE
pretrain model shape is different with config shape

### ISSUE THREAD

**Issue by heatMa** [OPEN-AIR-SUN/mars#17]
### input cmd
`python scripts/cicai_render.py --load-config outputs/clone/nsg-vkitti-car-depth-recon/2023-08-02_085533/config.yml --output_path renders/output-pretrain.mp4 --seconds 13`
I place the pretrained vkitti2 model below in `2023-08-02_085533`
![image](https://github.com/OPEN-AIR-SUN/mars/assets/18495380/fb04897e-a5f4-412c-a26b-7a47cb1281dd)

### output 
Loading poses from: vkitti2/Scene06/clone/pose.txt                                                                                           
Loading bbox from: vkitti2/Scene06/clone/bbox.txt
Loading info from: vkitti2/Scene06/clone/info.txt
[array([0.]), array([1.]), array([2.]), array([7.]), array([8.]), array([3.]),
array([9.]), array([4.]), array([5.]), array([12.]), array([6.]), array([10.]),
array([11.]), array([13.])] in this scene
finished data parsing
Loading poses from: vkitti2/Scene06/clone/pose.txt
Loading bbox from: vkitti2/Scene06/clone/bbox.txt
Loading info from: vkitti2/Scene06/clone/info.txt
[array([0.]), array([1.]), array([2.]), array([7.]), array([8.]), array([3.]),
array([9.]), array([4.]), array([5.]), array([12.]), array([6.]), array([10.]),
array([11.]), array([13.])] in this scene
finished data parsing
/home/rongbo.ma/anaconda3/envs/mars/lib/python3.8/site-packages/torchmetrics/utilities/prints.py:61: FutureWarning: Importing `PeakSignalNoiseRatio` from `torchmetrics` was deprecated and will be removed in 2.0. Import `PeakSignalNoiseRatio` from `torchmetrics.image` instead.
  _future_warning(
Loading latest checkpoint from load_dir
Traceback (most recent call last):
  File "scripts/cicai_render.py", line 391, in <module>
    entrypoint()
  File "scripts/cicai_render.py", line 387, in entrypoint
    tyro.cli(RenderTrajectory).main()
  File "scripts/cicai_render.py", line 311, in main
    _, pipeline, _, _ = eval_setup(
  File "/home/rongbo.ma/nerf/mars/nerfstudio/nerfstudio/utils/eval_utils.py", line 104, in eval_setup
    checkpoint_path, step = eval_load_checkpoint(config, pipeline)
  File "/home/rongbo.ma/nerf/mars/nerfstudio/nerfstudio/utils/eval_utils.py", line 61, in eval_load_checkpoint
    pipeline.load_pipeline(loaded_state["pipeline"], loaded_state["step"])
  File "/home/rongbo.ma/nerf/mars/nsg/nsg_pipeline.py", line 252, in load_pipeline
    self.load_state_dict(state, strict=True)
  File "/home/rongbo.ma/nerf/mars/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 125, in load_state_dict
    self.model.load_state_dict(model_state, strict=False)
  File "/home/rongbo.ma/anaconda3/envs/mars/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SceneGraphModel:
        **size mismatch for background_model.field.embedding_appearance.embedding.weight: copying a param with shape torch.Size([358, 32]) from checkpoint, the shape in current model is torch.Size([476, 32]).**

**Comment by AmazingRoad** [comment]
> Hi! Thanks for your feedback! If you want to render with our pre-trained model, you must ensure that your config is the same as the `config.yml` you load in.
> 
> We have already uploaded our config to Google Drive, you can visit [here](https://drive.google.com/drive/folders/1Yp-dQ7ijPpPC50SvJHfnYzxCAV9gMygX?usp=drive_link) to download our **config.yml** for each pre-trained model.

@xBeho1der Your kitti pretrain model is wrong. For task reconstruction, the size of the pretrain model' embedding_appearance in TCNNNerfactoField is [384, 32]. But for image range [5, 260], its size should be [512, 32]. I think the pretrain model for task reconstruction is in fact the model of nvs-75, since 512*0.75=384
