### ISSUE TITLE
How to generate the panoptic_maps?

### ISSUE THREAD

**Issue by rockywind** [OPEN-AIR-SUN/mars#2]
Hi, thank you for sharing the great work!
I download the kitti-step data, but I don't know how to generate the panoptic_maps?
This is the kitti step data.
![image](https://github.com/OPEN-AIR-SUN/mars/assets/14838781/4bb95f2e-9ed1-42c0-8fdd-044be5af169b)
This is the panoptic maps.
![image](https://github.com/OPEN-AIR-SUN/mars/assets/14838781/098bdd7e-03d6-4572-9e5c-a9151c2e8d5c)

**Comment by xBeho1der** [comment]
Thank you for your support and for bringing this issue to our attention. We appreciate your feedback on the project! For more information about KITTI-STEP datasets, you can refer to [here](https://github.com/google-research/deeplab2/blob/main/g3doc/setup/kitti_step.md). Below we provide an example to convert the annotation to panoptic maps.

**Comment by xBeho1der** [comment]
Thank you for your support and for bringing this issue to our attention. We appreciate your feedback on the project! For more information about KITTI-STEP dataset, you can refer to [here](https://github.com/google-research/deeplab2/blob/main/g3doc/setup/kitti_step.md). Below we provide an example of converting annotations to the full panoptic map.
```python
import cv2
import os
import numpy as np
import argparse

parsers = argparse.ArgumentParser(description="KITTI-STEP to panoptic segmentation")
parsers.add_argument("--annotation_path", type=str, default="")
parsers.add_argument("--output_path", type=str, default="")
annotation_path, output_path = parsers.parse_args().annotation_path, parsers.parse_args().output_path

colormap = np.zeros((256,3),dtype=np.uint8)

colormap[0] = [128, 64, 128]
colormap[1] = [244, 35, 232]
colormap[2] = [70, 70, 70]
colormap[3] = [102, 102, 156]
colormap[4] = [190, 153, 153]
colormap[5] = [153, 153, 153]
colormap[6] = [70, 130, 180]
colormap[7] = [220, 220, 0]
colormap[8] = [107, 142, 35]
colormap[9] = [152, 251, 152]
colormap[10] = [250, 170, 30]
colormap[11] = [220, 20, 60]
colormap[12] = [255, 0, 0]
colormap[13] = [0, 0, 142]
colormap[14] = [0, 0, 70]
colormap[15] = [0, 60, 100]
colormap[16] = [0, 80, 100]
colormap[17] = [0, 0, 230]
colormap[18] = [119, 11, 32]
colormap[255] = [0,0,0]

for filename in os.listdir(annotation_path):
    file_path = os.path.join(annotation_path, filename)
    img = cv2.imread(file_path)
    modified_img = img.copy()
    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            pixel = img[i, j]
            r, g, b = pixel[0], pixel[1], pixel[2]
            last_value = b
            modified_img[i, j] = colormap[b]

    modified_file_path = os.path.join(output_path, filename)
    cv2.imwrite(modified_file_path, modified_img)
```

**Comment by AIBUWAN** [comment]
@xBeho1der 
 I use this reference code to generate panoptic_maps, but it is different from yours, some black ones will appear, why?

![000065](https://github.com/OPEN-AIR-SUN/mars/assets/107452659/aef217e0-cae9-4cbd-aa32-3418d9eba088)

**Comment by xBeho1der** [comment]
> @xBeho1der I use this reference code to generate panoptic_maps, but it is different from yours, some black ones will appear, why?
> 
> ![000065](https://user-images.githubusercontent.com/107452659/261245701-aef217e0-cae9-4cbd-aa32-3418d9eba088.png)

Hi! Thanks for your reply. We download the annotation from [KITTI-STEP](https://www.cvlibs.net/datasets/kitti/eval_step.php) and then generate panoptic maps from the annotations. According to the [doc](https://github.com/google-research/deeplab2/blob/main/g3doc/setup/kitti_step.md), the label `void` is assigned label id `255`. So if you do nothing with the void area it will be red `[255, 0 ,0]` , while in the above script we assign it with value `[0, 0, 0]`.

You can just delete the line `colormap[255] = [0,0,0]`.
