### ISSUE TITLE
How to calculate PSNR and SSIM of this algorithm on KITTI？

### ISSUE THREAD

**Issue by jelleopard** [OPEN-AIR-SUN/mars#20]

**Comment by wuzirui** [comment]
[nerfstudio](https://nerf.studio)

**Comment by jelleopard** [comment]
I am not familiar with NeRFStudio, I did not find the code or script of eval in your code, is it not provided?

**Comment by jelleopard** [comment]
> [nerfstudio](https://nerf.studio)
I am not familiar with NeRFStudio, I did not find the code or script of eval in your code, is it not provided?

**Comment by wuzirui** [comment]
We use the nerfstudio as our general experiment framework and use all the evaluation tools in this codebase. Since your question is out of the scope of this code repository, we kindly suggest you to read the docs before opening new issues here.

**Comment by wuzirui** [comment]
Please read the following documents before creating new issues:
1. [Nerfstudio Documentation](https://nerf.studio)
2. MARS README
3. How to ask questions the smart way: [en](http://www.catb.org/~esr/faqs/smart-questions.html)/[zh-cn](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md).
