### ISSUE TITLE
How to set scale factor for depth?

### ISSUE THREAD

**Issue by AIBUWAN** [OPEN-AIR-SUN/mars#22]
`self.depth_unit_scale_factor = 0.01  # VKITTI provide depth maps in centimeters`
As mentioned in #9, depth maps for KITTI are generated with a [monocular depth estimation model](https://github.com/theNded/mini-omnidata), which leads to the unknown scale.
1. How should the depth_unit_scale_factor be set? Should it be set to 1.0?
2. If a monocular depth model is used for depth estimation, should the depth loss be set as sensor depth loss or mono depth loss?
3. During the experiment, when I switched to a different monocular depth model for estimating depth on the KITTI dataset, I observed a significant decrease in the PSNR metric. What should I pay attention to in this situation?

**Comment by xBeho1der** [comment]
Hi! Thanks for your feedback! Below are answers to your questions, you can also refer to #18 for some relative information.
-  As VKITTI-2 provides depth maps in centimeters and KITTI has no accurate scale, the `depth_unit_scale_factor` is set for VKITTI-2.
- You can refer to the supplementary of our paper and `nsg/scene_graph.py`.
![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/502f3dd4-7251-43d5-bd1c-1b3e7ae5ed2d)
