### ISSUE TITLE
Questions about the results of the experiments？

### ISSUE THREAD

**Issue by jelleopard** [OPEN-AIR-SUN/mars#23]
Hi, thanks for sharing your great work.
I have a few questions for you.
1. Experimental results using your proposed monocular depth estimation algorithm on the KITTI dataset are lower than the performance without depth maps.  What combination of modules were used to obtain the experimental results you provided on the **KITTI** dataset?
2.  When I run the render script I get the following error： 
python scripts/cicai_render.py --load-config outputs/0006/ablation-no-depth-kitti/2023-08-02_111759/config.yml --output-path renders/
Creating trajectory video
🎥 Rendering 🎥 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% ? --:--
Traceback (most recent call last):
  File "/home/*/mars/scripts/cicai_render.py", line 161, in _render_trajectory_video
    outputs = pipeline.model.get_outputs_for_camera_ray_bundle_render(camera_ray_bundle)
  File "/home/*/anaconda3/envs/SUDS/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/*/mars/nsg/models/scene_graph.py", line 844, in get_outputs_for_camera_ray_bundle_render
    outputs = self.forward(ray_bundle=ray_bundle)
  File "/home/*/mars/nerfstudio/nerfstudio/models/base_model.py", line 140, in forward
    return self.get_outputs(ray_bundle)
  File "/home/*/mars/nsg/models/scene_graph.py", line 330, in get_outputs
    obj_pose = self.batchify_object_pose(ray_bundle).to(self.device)
  File "/home/*/mars/nsg/models/scene_graph.py", line 643, in batchify_object_pose
    batch_obj_metadata = torch.index_select(obj_meta_tensor, 0, obj_idx.reshape(-1)).reshape(
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)

Could you give some suggestions about how to solve the problems?
Many thanks!

**Comment by heatMa** [comment]
For question 2，you should change File "/home/*/mars/nsg/models/scene_graph.py", line 643 as below. 
```
batch_obj_metadata = torch.index_select(obj_meta_tensor.to(obj_idx), 0, obj_idx.reshape(-1)).reshape(
 -1, obj_idx.shape[1], obj_meta_tensor.shape[1]
```
**But when traing, you shouldn't change it ,otherwise an error will be reported.**

**Comment by xBeho1der** [comment]
Here is an explanation for question 2.
![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/dbb32f4c-36d0-4e65-b955-945b5b0674a0)
