### ISSUE TITLE
how to solve this case when running render scripts

### ISSUE THREAD

**Issue by xuyanging** [OPEN-AIR-SUN/mars#24]
hi，
      when i download your pretrained model and run scripts  `python scripts/cicai_render.py --load-config outputs/nvs75fullseq/nsg-vkitti-car-depth-nvs/2023-06-21_135412/config.yml --output-path renders/`  as ReadME, I  encounter this error    

`FileNotFoundError: [Errno 2] No such file or directory: '/data22/luoly/dataset/demo/vkitti/Scene06/clone/extrinsic.txt'`

I search some keys words such as  `luoy`  but find nothing in my render code, how  could I do to get right results?

**Comment by wuzirui** [comment]
Hi! Please substitute `'/data22/luoly/dataset/demo/vkitti/'` with your own dataset path.
