### ISSUE TITLE
RuntimeError: Error writing 'renders': [NULL @ 0x5632d3584140] Unable to find a suitable output format for 'renders'

### ISSUE THREAD

**Issue by zwlvd** [OPEN-AIR-SUN/mars#26]
I meet some wrong in the rendering process.
🎥 Rendering 🎥 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% ? --:--
Traceback (most recent call last):
  File "scripts/cicai_render.py", line 210, in _render_trajectory_video
    writer.add_image(render_image)
  File "/home/liaoxin/.conda/envs/mars/lib/python3.8/site-packages/mediapy/__init__.py", line 1645, in add_image
    if self._proc.stdin.write(data) != len(data):
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/cicai_render.py", line 392, in <module>
    entrypoint()
  File "scripts/cicai_render.py", line 388, in entrypoint
    tyro.cli(RenderTrajectory).main()
  File "scripts/cicai_render.py", line 370, in main
    _render_trajectory_video(
  File "scripts/cicai_render.py", line 210, in _render_trajectory_video
    writer.add_image(render_image)
  File "/home/liaoxin/.conda/envs/mars/lib/python3.8/contextlib.py", line 525, in __exit__
    raise exc_details[1]
  File "/home/liaoxin/.conda/envs/mars/lib/python3.8/contextlib.py", line 510, in __exit__
    if cb(*exc_details):
  File "/home/liaoxin/.conda/envs/mars/lib/python3.8/site-packages/mediapy/__init__.py", line 1607, in __exit__
    self.close()
  File "/home/liaoxin/.conda/envs/mars/lib/python3.8/site-packages/mediapy/__init__.py", line 1658, in close
    raise RuntimeError(f"Error writing '{self.path}': {s}")
RuntimeError: Error writing 'renders': [NULL @ 0x5632d3584140] Unable to find a suitable output format for 'renders'
renders: Invalid argument

Someone said the ffmpeg versionis too old ,so I  updated the ffmpeg to the 6.0.0.But it still can't solve the problem.
My command is as follows.
CUDA_VISIBLE_DEVICES=0 python scripts/cicai_render.py --load-config outputs/clone/nsg-vkitti-car-depth-recon/2023-08-04_153117/config.yml --output-path renders/

**Comment by xBeho1der** [comment]
Hi! Thanks for your feedback! We have not ever met this error. Would you please provide the full text of `cicai_render.py` that you use to render?

**Comment by zwlvd** [comment]
> 

Actually,I just use the original cicai_render.py,the config.yaml is as follows.
!!python/object:nerfstudio.engine.trainer.TrainerConfig
_target: !!python/name:nerfstudio.engine.trainer.Trainer ''
data: &id003 !!python/object/apply:pathlib.PosixPath
- data
- vkitti
- Scene06
- clone
experiment_name: clone
load_checkpoint: null
load_config: null
load_dir: null
load_step: null
log_gradients: true
logging: !!python/object:nerfstudio.configs.base_config.LoggingConfig
  local_writer: !!python/object:nerfstudio.configs.base_config.LocalWriterConfig
    _target: !!python/name:nerfstudio.utils.writer.LocalWriter ''
    enable: true
    max_log_size: 10
    stats_to_track: !!python/tuple
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Train Iter (time)
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Train Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Test PSNR
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Vis Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Test Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - ETA (time)
  max_buffer_size: 20
  profiler: basic
  relative_log_dir: !!python/object/apply:pathlib.PosixPath []
  steps_per_log: 10
machine: !!python/object:nerfstudio.configs.base_config.MachineConfig
  dist_url: auto
  machine_rank: 0
  num_gpus: 1
  num_machines: 1
  seed: 42
max_num_iterations: 600000
method_name: nsg-vkitti-car-depth-recon
mixed_precision: false
optimizers:
  background_model:
    optimizer: !!python/object:nerfstudio.engine.optimizers.RAdamOptimizerConfig
      _target: &id001 !!python/name:torch.optim.radam.RAdam ''
      eps: 1.0e-15
      lr: 0.001
      max_norm: null
      weight_decay: 0
    scheduler: !!python/object:nerfstudio.engine.schedulers.ExponentialDecaySchedulerConfig
      _target: &id002 !!python/name:nerfstudio.engine.schedulers.ExponentialDecayScheduler ''
      lr_final: 1.0e-05
      lr_pre_warmup: 1.0e-08
      max_steps: 200000
      ramp: cosine
      warmup_steps: 0
  object_model:
    optimizer: !!python/object:nerfstudio.engine.optimizers.RAdamOptimizerConfig
      _target: *id001
      eps: 1.0e-15
      lr: 0.005
      max_norm: null
      weight_decay: 0
    scheduler: !!python/object:nerfstudio.engine.schedulers.ExponentialDecaySchedulerConfig
      _target: *id002
      lr_final: 1.0e-05
      lr_pre_warmup: 1.0e-08
      max_steps: 200000
      ramp: cosine
      warmup_steps: 0
output_dir: !!python/object/apply:pathlib.PosixPath
- outputs
pipeline: !!python/object:nsg.nsg_pipeline.NSGPipelineConfig
  _target: !!python/name:nsg.nsg_pipeline.NSGPipeline ''
  datamanager: !!python/object:nsg.data.nsg_datamanager.NSGkittiDataManagerConfig
    _target: !!python/name:nsg.data.nsg_datamanager.NSGkittiDataManager ''
    camera_optimizer: !!python/object:nerfstudio.cameras.camera_optimizers.CameraOptimizerConfig
      _target: !!python/name:nerfstudio.cameras.camera_optimizers.CameraOptimizer ''
      mode: 'off'
      optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
        _target: !!python/name:torch.optim.adam.Adam ''
        eps: 1.0e-15
        lr: 0.0006
        max_norm: null
        weight_decay: 0
      orientation_noise_std: 0.0
      param_group: camera_opt
      position_noise_std: 0.0
      scheduler: !!python/object:nerfstudio.engine.schedulers.ExponentialDecaySchedulerConfig
        _target: *id002
        lr_final: null
        lr_pre_warmup: 1.0e-08
        max_steps: 10000
        ramp: cosine
        warmup_steps: 0
    camera_res_scale_factor: 1.0
    data: *id003
    dataparser: !!python/object:nsg.data.nsg_vkitti_dataparser.NSGvkittiDataParserConfig
      _target: !!python/name:nsg.data.nsg_vkitti_dataparser.NSGvkitti ''
      add_input_rows: -1
      alpha_color: white
      bckg_only: false
      box_scale: 1.5
      car_nerf_state_dict_path: !!python/object/apply:pathlib.PosixPath
      - data
      - vkitti
      - car-nerf-state-dict
      - epoch_805.ckpt
      car_object_latents_path: !!python/object/apply:pathlib.PosixPath
      - data
      - vkitti
      - latents
      - latent_codes06.pt
      chunk: 32768
      data: !!python/object/apply:pathlib.PosixPath
      - /
      - data1
      - vkitti
      - Scene06
      - clone
      dataset_type: vkitti
      far_plane: 150.0
      first_frame: 0
      last_frame: 237
      max_input_objects: -1
      near_plane: 0.5
      netchunk: 65536
      novel_view: left
      obj_only: false
      obj_opaque: true
      object_setting: 0
      render_only: false
      scale_factor: 0.1
      scene_scale: 2.0
      semantic_mask_classes: []
      semantic_path: !!python/object/apply:pathlib.PosixPath []
      split_setting: reconstruction
      use_car_latents: true
      use_depth: true
      use_obj: true
      use_object_properties: true
      use_semantic: false
    eval_image_indices: !!python/tuple
    - 0
    eval_num_images_to_sample_from: -1
    eval_num_rays_per_batch: 4096
    eval_num_times_to_repeat_images: -1
    patch_size: 1
    train_num_images_to_sample_from: -1
    train_num_rays_per_batch: 4096
    train_num_times_to_repeat_images: -1
  model: !!python/object:nsg.models.scene_graph.SceneGraphModelConfig
    _target: !!python/name:nsg.models.scene_graph.SceneGraphModel ''
    background_color: black
    background_model: !!python/object:nsg.models.nerfacto.NerfactoModelConfig
      _target: !!python/name:nsg.models.nerfacto.NerfactoModel ''
      background_color: black
      collider_params:
        far_plane: 6.0
        near_plane: 2.0
      disable_scene_contraction: false
      distortion_loss_mult: 0.002
      enable_collider: true
      eval_num_rays_per_chunk: 4096
      far_plane: 150.0
      hidden_dim: 64
      hidden_dim_color: 64
      hidden_dim_transient: 64
      log2_hashmap_size: 19
      loss_coefficients:
        rgb_loss_coarse: 1.0
        rgb_loss_fine: 1.0
      max_res: 2048
      near_plane: 0.05
      num_coarse_samples: 24
      num_levels: 16
      num_nerf_samples_per_ray: 97
      num_proposal_iterations: 2
      num_proposal_samples_per_ray: !!python/tuple
      - 256
      - 128
      obj_feat_dim: 0
      orientation_loss_mult: 0.0001
      pred_normal_loss_mult: 0.001
      predict_normals: false
      proposal_net_args_list:
      - hidden_dim: 16
        log2_hashmap_size: 17
        max_res: 128
        num_levels: 5
        use_linear: false
      - hidden_dim: 16
        log2_hashmap_size: 17
        max_res: 256
        num_levels: 5
        use_linear: false
      proposal_update_every: 5
      proposal_warmup: 5000
      proposal_weights_anneal_max_num_iters: 1000
      proposal_weights_anneal_slope: 10.0
      sampler: proposal
      use_average_appearance_embedding: true
      use_gradient_scaling: false
      use_proposal_weight_anneal: true
      use_same_proposal_network: false
      use_single_jitter: true
    collider_params:
      far_plane: 6.0
      near_plane: 2.0
    debug_object_pose: false
    depth_loss_mult: 0.01
    depth_loss_type: !!python/object/apply:nerfstudio.model_components.losses.DepthLossType
    - 1
    depth_sigma: 0.05
    enable_collider: true
    eval_num_rays_per_chunk: 4096
    far_plane: 1000.0
    interlevel_loss_mult: 1.0
    is_euclidean_depth: false
    latent_size: 256
    loss_coefficients:
      rgb_loss_coarse: 1.0
      rgb_loss_fine: 1.0
    max_num_obj: -1
    mono_depth_loss_mult: 0.0
    near_plane: 0.05
    object_model_template: !!python/object:nsg.models.car_nerf.CarNeRFModelConfig
      _target: !!python/name:nsg.models.car_nerf.CarNeRF ''
      background_color: black
      collider_params:
        far_plane: 6.0
        near_plane: 2.0
      enable_collider: true
      eval_num_rays_per_chunk: 4096
      loss_coefficients:
        rgb_loss_coarse: 1.0
        rgb_loss_fine: 1.0
      num_coarse_samples: 32
      num_fine_samples: 97
      optimize_latents: false
    object_ray_sample_strategy: remove-bg
    object_representation: class-wise
    object_warmup_steps: 1000
    orientation_loss_mult: 0.0001
    pred_normal_loss_mult: 0.001
    predict_normals: false
    ray_add_input_rows: -1
    semantic_loss_mult: 1.0
    should_decay_sigma: false
    sigma_decay_rate: 0.9998
    sky_model: !!python/object:nsg.models.sky_model.SkyModelConfig
      _target: !!python/name:nsg.models.sky_model.SkyModel ''
      collider_params:
        far_plane: 6.0
        near_plane: 2.0
      enable_collider: true
      eval_num_rays_per_chunk: 4096
      hidden_dim: 128
      loss_coefficients:
        rgb_loss_coarse: 1.0
        rgb_loss_fine: 1.0
      num_layers: 5
    starting_depth_sigma: 4.0
    use_interlevel_loss: true
    use_sky_model: false
project_name: nerfstudio-project
relative_model_dir: !!python/object/apply:pathlib.PosixPath
- nerfstudio_models
save_only_latest_checkpoint: false
steps_per_eval_all_images: 5000
steps_per_eval_batch: 500
steps_per_eval_image: 500
steps_per_save: 2000
timestamp: 2023-08-04_153117
use_grad_scaler: true
viewer: !!python/object:nerfstudio.configs.base_config.ViewerConfig
  image_format: jpeg
  jpeg_quality: 90
  max_num_display_images: 512
  num_rays_per_chunk: 32768
  quit_on_train_completion: false
  relative_log_filename: viewer_log_filename.txt
  websocket_host: 0.0.0.0
  websocket_port: null
  websocket_port_default: 7007
vis: wandb

**Comment by victor-cilay** [comment]
You can render the video with the command "CUDA_VISIBLE_DEVICES=0 python scripts/cicai_render.py --load-config outputs/clone/nsg-vkitti-car-depth-recon/2023-08-04_153117/config.yml" which the output will be the default directory render/.
We are fixing the bug.

**Comment by xBeho1der** [comment]
Hi! Thanks for your detailed report. Before addressing the issue, I kindly suggest that you use code blocks (` `) when displaying relevant code to avoid confusion with the markdown formatting.
Here is your command:
`CUDA_VISIBLE_DEVICES=0 python scripts/cicai_render.py --load-config outputs/clone/nsg-vkitti-car-depth-recon/2023-08-04_153117/config.yml --output-path renders/`
The error came from the `output path` you specify. Please refer to our `cicai_render.py` for the right format of your train command. You can just run your command by in the following format:
```bash
CUDA_VISIBLE_DEVICES=0 python scripts/cicai_render.py --load-config outputs/clone/nsg-vkitti-car-depth-recon/2023-08-04_153117/config.yml
or
CUDA_VISIBLE_DEVICES=0 python scripts/cicai_render.py --load-config outputs/clone/nsg-vkitti-car-depth-recon/2023-08-04_153117/config.yml --output-path renders/output.mp4
```
![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/0dc24070-be44-4ec0-b269-afc290e09356)

**Comment by zwlvd** [comment]
> Hi! Thanks for your detailed report. Before addressing the issue, I kindly suggest that you use code blocks (` `) when displaying relevant code to avoid confusion with the markdown formatting. Here is your command: `CUDA_VISIBLE_DEVICES=0 python scripts/cicai_render.py --load-config outputs/clone/nsg-vkitti-car-depth-recon/2023-08-04_153117/config.yml --output-path renders/` The error came from the `output path` you specify. Please refer to our `cicai_render.py` for the right format of your train command. You can just run your command by in the following format:
> 
> ```shell
> CUDA_VISIBLE_DEVICES=0 python scripts/cicai_render.py --load-config outputs/clone/nsg-vkitti-car-depth-recon/2023-08-04_153117/config.yml
> or
> CUDA_VISIBLE_DEVICES=0 python scripts/cicai_render.py --load-config outputs/clone/nsg-vkitti-car-depth-recon/2023-08-04_153117/config.yml --output-path renders/output.mp4
> ```
> 
> ![image](https://user-images.githubusercontent.com/107318439/258736985-0dc24070-be44-4ec0-b269-afc290e09356.png)

Thank you so much for your valuable advice. I really appreciate your suggestion and I will implement this in my future posts.
