### ISSUE TITLE
How to edit the scene

### ISSUE THREAD

**Issue by jelleopard** [OPEN-AIR-SUN/mars#28]
Hi! Thank you for the great work! I had a few questions about edit the scene on kitti-0006.
I read the code as you suggested(mars/scripts/cicai_render.py), but did not find any code about the editing function. Could you give me same advice about of how to edit scene , e.g., change the type of the scene's car, edit the motion trajectory, etc.

Thanks a lot in advance.

**Comment by xBeho1der** [comment]
For example, you can edit objects in a scene by changing the pose and rotation of a car. Concretely, the last dimension of rotation represents `object_id`, the last 2 dimensions of pose represent `object_id` and `axis`.
![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/1c168b56-2f14-4b7e-b1e3-c3c221eabcf3)

**Comment by jelleopard** [comment]
Thanks for your detailed reply, does it support changing the car type or editing the car trajectory?

**Comment by xBeho1der** [comment]
> 

We now don't support directly editing the car type, but it can be implemented via manually modifying the car latents. But you can change the appearance of a car to an existing one in the scene.
To edit car trajectory, you can generate your own car pose and assign it to `pose` and `rotation` across the scene.

**Comment by jelleopard** [comment]
> > 
> 
> We now don't support directly editing the car type, but it can be implemented via manually modifying the car latents. But you can change the appearance of a car to an existing one in the scene. To edit car trajectory, you can generate your own car pose and assign it to `pose` and `rotation` across the scene.

Thanks for your detailed reply, May I ask how to change the appearance of the car to an existing one in the scene. 
How to change the following code to achieve scene editing, can you give some comments or example codes

pose = batch_obj_dyn[..., :3]
rotation = batch_obj_dyn[..., 3]
pose[:, :, 0, 2] = pose[:, :, 0, 2]
rotation[:, :, 0] = rotation[:, :, 0]
batch_obj_dyn[..., :3] = pose
batch_obj_dyn[..., 3] = rotation

**Comment by amoghskanda** [comment]
> For example, you can edit objects in a scene by changing the pose and rotation of a car. Concretely, the last dimension of rotation represents `object_id`, the last 2 dimensions of pose represent `object_id` and `axis`. ![image](https://private-user-images.githubusercontent.com/107318439/258739023-1c168b56-2f14-4b7e-b1e3-c3c221eabcf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MDEwNTgsIm5iZiI6MTcwNzgwMDc1OCwicGF0aCI6Ii8xMDczMTg0MzkvMjU4NzM5MDIzLTFjMTY4YjU2LTJmMTQtNGI3ZS1iMWUzLWMzYzIyMWVhYmNmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QwNTA1NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzNlYjQwNDI0MjE0OTY3ODc5OWExODQxYjIwMWYzODNhMWUzMGRlYjcyNGZlNzkyMTdkMTU5MDNiY2FiNTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EUIb4LsyfEM1SVXom2RTqWrb0EKyjGpodsRLW_4G06Q)


Hey, what do the first 2 dimensions of pose and rotation denote? How do I change the trajectory of the ego vehicle?
