### ISSUE TITLE
Where is the KITTI completion_02/03 data?

### ISSUE THREAD

**Issue by toro1818** [OPEN-AIR-SUN/mars#29]
![image](https://github.com/OPEN-AIR-SUN/mars/assets/63446843/9ccb05b2-41e7-41e8-9ff1-c9333cd9481e)
I'm confused that there is no completion data.

**Comment by wuzirui** [comment]
Hi, please see this [discussion](https://github.com/OPEN-AIR-SUN/mars/discussions/18).

**Comment by xBeho1der** [comment]
Hi! Thanks for your feedback! Please refer to #18 and #9.
