### ISSUE TITLE
Which commit of nerfstudio is this repository based on?

### ISSUE THREAD

**Issue by jingyibo123** [OPEN-AIR-SUN/mars#3]
Thanks for sharing the great work.

For convenience, is it possible to provide the version/commit ID of the nerfstudio this codebase's modification is based on?

**Comment by wuzirui** [comment]
The nerfstudio version is a [modified version](https://github.com/wuzirui/nerfstudio/commit/b924655d494bea7aae8a8a026a138d2ca4570b95) that is somewhere between 0.2.2 and 0.3. But we are currently working on to adapt to nerfstudio 0.3.x, which can be expected in early August.
