### ISSUE TITLE
The render process is killed.

### ISSUE THREAD

**Issue by zwlvd** [OPEN-AIR-SUN/mars#30]
I use the following command to render,while the process is killed.
`CUDA_VISIBLE_DEVICES=0 python scripts/cicai_render.py --load-config outputs/0006/ablation-no-depth-kitti/2023-08-07_142610/config.yml --output-path renders/kitti/06/output.mp4`
The error is 

> (mars) liaoxin@amax:~/mars$ CUDA_VISIBLE_DEVICES=0 python scripts/cicai_render.py --load-config outputs/0006/ablation-no-depth-kitti/2023-08-07_142610/config.yml --output-path renders/kitti/06/output.mp4
[18:56:42] [array([0.]), array([1.]), array([2.]), array([7.]), array([8.]), array([3.]),          nsg_dataparser.py:843
           array([4.]), array([9.]), array([5.]), array([12.]), array([6.]), array([10.]),                              
           array([11.]), array([13.]), array([14.])] in this scene.                                                     
finished data parsing
[18:56:49] [array([0.]), array([1.]), array([2.]), array([7.]), array([8.]), array([3.]),          nsg_dataparser.py:843
           array([4.]), array([9.]), array([5.]), array([12.]), array([6.]), array([10.]),                              
           array([11.]), array([13.]), array([14.])] in this scene.                                                     
Killed

I think it may be out of memory.I wander how much memory it need to render a kitti model.
The memory situation is as follows.

> liaoxin@amax:~$ free
                     total              used             free           shared    buff/cache   available
Mem:      263727240   127613456   132761136       59212     3352648   134206488
Swap:       8000508     8000508           0

**Comment by xBeho1der** [comment]
Thanks for your feedback! Below is the `free`, `top` and `gpustat` while running a render script.
![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/bdb8a18b-0c63-4cd5-aa3a-ceb346b7e489)

**Comment by zwlvd** [comment]
> Thanks for your feedback! Below is the `free`, `top` and `gpustat` while running a render script. ![image](https://user-images.githubusercontent.com/107318439/258796634-bdb8a18b-0c63-4cd5-aa3a-ceb346b7e489.png)

Thank you very much.
