### ISSUE TITLE
Multi-GPU training question

### ISSUE THREAD

**Issue by zwlvd** [OPEN-AIR-SUN/mars#32]
I wander to know if  mars support muti-GPU to train or render.
I notice that there is a TODO
`# TODO: To run cicai_render.py, add to(self.device) in the following line`
Dose it mean the render don't suppport muti-GPU to render.

**Comment by cheylong** [comment]
if u want render a video of trained model, add to(self.device) in next line.

**Comment by zwlvd** [comment]
> if u want render a video of trained model, add to(self.device) in next line.

Well,I know the way to render a video,what confuse me is whether it support muti-GPU to train or render.

**Comment by xBeho1der** [comment]
Hi! Thanks for your feedback! We now don't support multi-GPU render.
