### ISSUE TITLE
About kitti-360 nvs benchmark

### ISSUE THREAD

**Issue by DRosemei** [OPEN-AIR-SUN/mars#36]
Thanks for you great work! I want to know how you get these 5 static scenes in  KITTI-360 for evaluation [here](https://www.cvlibs.net/datasets/kitti-360/leaderboard_nvs.php?task=nvs_rgb) 
![image](https://github.com/OPEN-AIR-SUN/mars/assets/27892562/8af27791-deb5-402b-a67a-aaf020e57f31)

**Comment by wuzirui** [comment]
Hi, the details for the KITTI360 benchmarking are planned to be released in the next version.

**Comment by a4152684** [comment]
hoping to see it soon~

**Comment by gaurav00700** [comment]
@xBeho1der Is there any update on Kitti360 dataset ?

**Comment by xBeho1der** [comment]
@gaurav00700 Hi, thanks for your reply. There isn't any update on the Kitti360 datasets.

**Comment by gaurav00700** [comment]
@xBeho1der Thank you for your reply. Is there any plan to release its support in near future ?

**Comment by xBeho1der** [comment]
Hi! @gaurav00700
We currently do not have any plans to support the KITTI-360 dataset. However, you can implement it by adding a new dataparser. Pull request is welcomed.

**Comment by gaurav00700** [comment]
@xBeho1der Thank you for the update.
