### ISSUE TITLE
Config question about novel_view and split_setting

### ISSUE THREAD

**Issue by zwlvd** [OPEN-AIR-SUN/mars#37]
The config has two setting 
` split_setting: str = "reconstruction"`
` novel_view: str = "left"`
For the split_setting I notice that there are four chioces:reconstruction,nvs-75,nvs-50,nvs-25.
For the novel_view, it has four choices : left,mid,shift,right. Dose it mean change the value will be able to render from a new view, and if the  split_setting has certain connection with it.

**Comment by wuzirui** [comment]
Hi, the `novel_view` option is a deprecated one (which is from the original [neural scene graph](https://github.com/princeton-computational-imaging/neural-scene-graphs) code).
