### ISSUE TITLE
how to train a model with nerfacto using depth supervision

### ISSUE THREAD

**Issue by sonnefred** [OPEN-AIR-SUN/mars#38]
Hi, I'd like to train a model from scratch using depth supervision generated from the monocular depth estimation model, and my cicai_config.py is like this, is it right? Thanks!

**Comment by sonnefred** [comment]
Sorry for the above confusing layout, and my cicai_configs.py is like this, thanks.  
```
KITTI_Recon_NSG_Car_Depth = MethodSpecification(
    config=TrainerConfig(
        method_name="nsg-kitti-car-depth-recon",
        steps_per_eval_image=STEPS_PER_EVAL_IMAGE,
        steps_per_eval_all_images=STEPS_PER_EVAL_ALL_IMAGES,
        steps_per_save=STEPS_PER_SAVE,
        max_num_iterations=MAX_NUM_ITERATIONS,
        save_only_latest_checkpoint=False,
        mixed_precision=False,
        use_grad_scaler=True,
        log_gradients=True,
        pipeline=NSGPipelineConfig(
            datamanager=NSGkittiDataManagerConfig(
                dataparser=NSGkittiDataParserConfig(
                    use_car_latents=False,
                    use_depth=True,
                    split_setting="reconstruction",
                ),
                train_num_rays_per_batch=4096,
                eval_num_rays_per_batch=4096,
                camera_optimizer=CameraOptimizerConfig(mode="off"),
            ),
            model=SceneGraphModelConfig(
                background_model=NerfactoModelConfig(),
                object_model_template=NerfactoModelConfig(),
                object_representation="class-wise",
                object_ray_sample_strategy="remove-bg",
            ),
        ),
        optimizers={
            "background_model": {
                "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
            "learnable_global": {
                "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
            "object_model": {
                "optimizer": RAdamOptimizerConfig(lr=5e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
        },
        # viewer=ViewerConfig(num_rays_per_chunk=1 << 15),
        vis="wandb",
    ),
    description="Neural Scene Graph implementation with vanilla-NeRF model for backgruond and object models.",
)
```

**Comment by xBeho1der** [comment]
> Sorry for the above confusing layout, and my cicai_configs.py is like this, thanks.
> 
> ```
> KITTI_Recon_NSG_Car_Depth = MethodSpecification(
>     config=TrainerConfig(
>         method_name="nsg-kitti-car-depth-recon",
>         steps_per_eval_image=STEPS_PER_EVAL_IMAGE,
>         steps_per_eval_all_images=STEPS_PER_EVAL_ALL_IMAGES,
>         steps_per_save=STEPS_PER_SAVE,
>         max_num_iterations=MAX_NUM_ITERATIONS,
>         save_only_latest_checkpoint=False,
>         mixed_precision=False,
>         use_grad_scaler=True,
>         log_gradients=True,
>         pipeline=NSGPipelineConfig(
>             datamanager=NSGkittiDataManagerConfig(
>                 dataparser=NSGkittiDataParserConfig(
>                     use_car_latents=False,
>                     use_depth=True,
>                     split_setting="reconstruction",
>                 ),
>                 train_num_rays_per_batch=4096,
>                 eval_num_rays_per_batch=4096,
>                 camera_optimizer=CameraOptimizerConfig(mode="off"),
>             ),
>             model=SceneGraphModelConfig(
>                 background_model=NerfactoModelConfig(),
>                 object_model_template=NerfactoModelConfig(),
>                 object_representation="class-wise",
>                 object_ray_sample_strategy="remove-bg",
>             ),
>         ),
>         optimizers={
>             "background_model": {
>                 "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15),
>                 "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
>             },
>             "learnable_global": {
>                 "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15),
>                 "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
>             },
>             "object_model": {
>                 "optimizer": RAdamOptimizerConfig(lr=5e-3, eps=1e-15),
>                 "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
>             },
>         },
>         # viewer=ViewerConfig(num_rays_per_chunk=1 << 15),
>         vis="wandb",
>     ),
>     description="Neural Scene Graph implementation with vanilla-NeRF model for backgruond and object models.",
> )
> ```

```python
KITTI_Recon_NSG_Car_Depth = MethodSpecification(
    config=TrainerConfig(
        method_name="nsg-kitti-car-depth-recon",
        steps_per_eval_image=STEPS_PER_EVAL_IMAGE,
        steps_per_eval_all_images=STEPS_PER_EVAL_ALL_IMAGES,
        steps_per_save=STEPS_PER_SAVE,
        max_num_iterations=MAX_NUM_ITERATIONS,
        save_only_latest_checkpoint=False,
        mixed_precision=False,
        use_grad_scaler=True,
        log_gradients=True,
        pipeline=NSGPipelineConfig(
            datamanager=NSGkittiDataManagerConfig(
                dataparser=NSGkittiDataParserConfig(
                    scale_factor=0.01,
                    use_car_latents=False,
                    use_depth=True,
                    split_setting="reconstruction",
                ),
                train_num_rays_per_batch=4096,
                eval_num_rays_per_batch=4096,
                camera_optimizer=CameraOptimizerConfig(mode="off"),
            ),
            model=SceneGraphModelConfig(
                mono_depth_loss_mult=0.05,
                depth_loss_mult=0,
                background_model=NerfactoModelConfig(),
                object_model_template=NerfactoModelConfig(),
                object_representation="class-wise",
                object_ray_sample_strategy="remove-bg",
            ),
        ),
        optimizers={
            "background_model": {
                "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
            "learnable_global": {
                "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
            "object_model": {
                "optimizer": RAdamOptimizerConfig(lr=5e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
        },
        # viewer=ViewerConfig(num_rays_per_chunk=1 << 15),
        vis="wandb",
    ),
    description="Neural Scene Graph implementation with vanilla-NeRF model for backgruond and object models.",
)
```

**Comment by xBeho1der** [comment]
> Author

Hi! You can refer to #33, maybe it's helpful to you.

**Comment by xBeho1der** [comment]
> Thanks for your quick reply, and I also have a question: when I use cicai_render.py to render images or videos, what should I modify if I only want to render the background (remove the objects)? Thanks!

Hi! You can refer to #33, maybe it's helpful to you.

**Comment by sonnefred** [comment]
Ok, btw, I generated depth maps using monocular depth estimation model, and I put the visualization images, which are 3-channel, into the completion_02 folder, is there any required processing before putting them in the folder?  Thanks

**Comment by xBeho1der** [comment]
> 

Below is an example image that we generated with a [monocular depth estimation model](https://github.com/theNded/mini-omnidata).
![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/415b2310-17cb-4232-becf-d58051af58c7)

**Comment by sonnefred** [comment]
So your depth map is one-channel? Did you transfer the 3-channel depth map generated from the model to one channel?

**Comment by xBeho1der** [comment]
> So your depth map is one-channel? Did you transfer the 3-channel depth map generated from the model to one channel?

Our depth map is 3-channel.

**Comment by sonnefred** [comment]
But the depth map I generated is a color map, not black and white, should I transfer it into grayscale?

**Comment by xBeho1der** [comment]
Hi! The following code reads our depth image. And you should transfer it into grayscale.

![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/28301b8a-5d0f-4825-b670-f49c887b41c2)

**Comment by xBeho1der** [comment]
Hi! You can refer to the below code, which reads our depth from the image. And you need to transfer your image into grayscale. 
![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/194ae11c-bb2d-4fa4-b752-cf5a1c550488)

**Comment by zwlvd** [comment]
I train the kitti 0006 without depth ,and the objects in the scene  are just some shadow. Dose it mean without the depth the result will be bad .
![00106](https://github.com/OPEN-AIR-SUN/mars/assets/74552396/8110223b-a09b-4d3d-8293-ba115160a25e)

**Comment by sonnefred** [comment]
> Hi! You can refer to the below code, which reads our depth from the image. And you need to transfer your image into grayscale. ![image](https://user-images.githubusercontent.com/107318439/259688932-194ae11c-bb2d-4fa4-b752-cf5a1c550488.png)

ok, thanks a lot, i will have a look.

**Comment by xBeho1der** [comment]
> I train the kitti 0006 without depth ,and the objects in the scene are just some shadow. Dose it mean without the depth the result will be bad . ![00106](https://user-images.githubusercontent.com/74552396/259690764-8110223b-a09b-4d3d-8293-ba115160a25e.png)

You can try with our proposed category-level car model. That will help to decouple the object and background.

> Dose it mean without the depth the result will be bad

Sure.

**Comment by zwlvd** [comment]
> > I train the kitti 0006 without depth ,and the objects in the scene are just some shadow. Dose it mean without the depth the result will be bad . ![00106](https://user-images.githubusercontent.com/74552396/259690764-8110223b-a09b-4d3d-8293-ba115160a25e.png)
> 
> You can try with our proposed category-level car model. That will help to decouple the object and background.
> 
> > Dose it mean without the depth the result will be bad
> 
> Sure.

Thank you for your reply. Is the below model  the category-level car model ?

> model=SceneGraphModelConfig(
>                 background_model=NerfactoModelConfig(),
>                 object_model_template=CarNeRFModelConfig(_target=CarNeRF),
>                 object_representation="class-wise",
>                 object_ray_sample_strategy="remove-bg",
>             ),

**Comment by zwlvd** [comment]
> > 
> 
> Below is an example image that we generated with a [monocular depth estimation model](https://github.com/theNded/mini-omnidata). ![image](https://user-images.githubusercontent.com/107318439/259674700-415b2310-17cb-4232-becf-d58051af58c7.png)

I follow the omnidata to generate the depth ,and I notice the channel is setted to be 1 .While the result I got is still 3-channel.
![000151](https://github.com/OPEN-AIR-SUN/mars/assets/74552396/7387d04d-b3ba-406d-986b-57ba32bc4f7c)
What's the problem?

**Comment by xBeho1der** [comment]
> > > I train the kitti 0006 without depth ,and the objects in the scene are just some shadow. Dose it mean without the depth the result will be bad . ![00106](https://user-images.githubusercontent.com/74552396/259690764-8110223b-a09b-4d3d-8293-ba115160a25e.png)
> > 
> > 
> > You can try with our proposed category-level car model. That will help to decouple the object and background.
> > > Dose it mean without the depth the result will be bad
> > 
> > 
> > Sure.
> 
> Thank you for your reply. Is the below model the category-level car model ?
> 
> > model=SceneGraphModelConfig(
> > background_model=NerfactoModelConfig(),
> > object_model_template=CarNeRFModelConfig(_target=CarNeRF),
> > object_representation="class-wise",
> > object_ray_sample_strategy="remove-bg",
> > ),

Sure.

**Comment by xBeho1der** [comment]
@zwlvd 
Hi. Thanks for your reply. You can change as the below image and try again.
![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/9e63d87e-fd5e-4f27-bfdf-351ea6e99dc3)

**Comment by xBeho1der** [comment]
For more information about KITTI depth maps, you all can refer to #18.

**Comment by zwlvd** [comment]
> For more information about KITTI depth maps, you all can refer to #18.

Thank you for your valuable suggestions, it's very useful.

**Comment by sonnefred** [comment]
Hi, I trained the model using monocular depth, but the depth loss is like this, which didn't decrease stably, and the eval depth image is like the following. Could you please point out what the problem may be? Thanks.
![c05fcabbee9d5ee79c3d67e53](https://github.com/OPEN-AIR-SUN/mars/assets/66628395/882df39b-93c5-42fa-87bf-f1d4586f5ae0)
![91eb880b0baa6c186ba4b7fb9](https://github.com/OPEN-AIR-SUN/mars/assets/66628395/be637388-12a6-4045-86f3-569f156a6cee)

**Comment by wuzirui** [comment]
> Hi, I trained the model using monocular depth, but the depth loss is like this, which didn't decrease stably, and the eval depth image is like the following. Could you please point out what the problem may be? Thanks. ![c05fcabbee9d5ee79c3d67e53](https://user-images.githubusercontent.com/66628395/259913136-882df39b-93c5-42fa-87bf-f1d4586f5ae0.png) ![91eb880b0baa6c186ba4b7fb9](https://user-images.githubusercontent.com/66628395/259913404-be637388-12a6-4045-86f3-569f156a6cee.png)

Hi! What multipliers do you apply to the mono_depth_loss and the general depth_loss?

**Comment by sonnefred** [comment]
I trained the model using this config.


> If you want to use monocular depth estimation for KITTI, please add `mono_depth_loss_mult` in the `SceneGraphModelConfig`. You can also modify the parameters yourself.
> CLICK ME

**Comment by sonnefred** [comment]
I trained the model using this config.
```
KITTI_Recon_NSG_Car_Depth = MethodSpecification(
    config=TrainerConfig(
        method_name="nsg-kitti-car-depth-recon",
        steps_per_eval_image=STEPS_PER_EVAL_IMAGE,
        steps_per_eval_all_images=STEPS_PER_EVAL_ALL_IMAGES,
        steps_per_save=STEPS_PER_SAVE,
        max_num_iterations=MAX_NUM_ITERATIONS,
        save_only_latest_checkpoint=False,
        mixed_precision=False,
        use_grad_scaler=True,
        log_gradients=True,
        pipeline=NSGPipelineConfig(
            datamanager=NSGkittiDataManagerConfig(
                dataparser=NSGkittiDataParserConfig(
                    scale_factor=0.01,
                    use_car_latents=False,
                    use_depth=True,
                    split_setting="reconstruction",
                ),
                train_num_rays_per_batch=4096,
                eval_num_rays_per_batch=4096,
                camera_optimizer=CameraOptimizerConfig(mode="off"),
            ),
            model=SceneGraphModelConfig(
                mono_depth_loss_mult=0.05,
                depth_loss_mult=0,
                background_model=NerfactoModelConfig(),
                object_model_template=NerfactoModelConfig(),
                object_representation="class-wise",
                object_ray_sample_strategy="remove-bg",
            ),
        ),
        optimizers={
            "background_model": {
                "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
            "learnable_global": {
                "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
            "object_model": {
                "optimizer": RAdamOptimizerConfig(lr=5e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
        },
        # viewer=ViewerConfig(num_rays_per_chunk=1 << 15),
        vis="wandb",
    ),
    description="Neural Scene Graph implementation with vanilla-NeRF model for backgruond and object models.",
)
```

**Comment by sonnefred** [comment]
> > Hi, I trained the model using monocular depth, but the depth loss is like this, which didn't decrease stably, and the eval depth image is like the following. Could you please point out what the problem may be? Thanks. ![c05fcabbee9d5ee79c3d67e53](https://user-images.githubusercontent.com/66628395/259913136-882df39b-93c5-42fa-87bf-f1d4586f5ae0.png) ![91eb880b0baa6c186ba4b7fb9](https://user-images.githubusercontent.com/66628395/259913404-be637388-12a6-4045-86f3-569f156a6cee.png)
> 
> Hi! What multipliers do you apply to the mono_depth_loss and the general depth_loss?

I trained the model using this config.
```
KITTI_Recon_NSG_Car_Depth = MethodSpecification(
    config=TrainerConfig(
        method_name="nsg-kitti-car-depth-recon",
        steps_per_eval_image=STEPS_PER_EVAL_IMAGE,
        steps_per_eval_all_images=STEPS_PER_EVAL_ALL_IMAGES,
        steps_per_save=STEPS_PER_SAVE,
        max_num_iterations=MAX_NUM_ITERATIONS,
        save_only_latest_checkpoint=False,
        mixed_precision=False,
        use_grad_scaler=True,
        log_gradients=True,
        pipeline=NSGPipelineConfig(
            datamanager=NSGkittiDataManagerConfig(
                dataparser=NSGkittiDataParserConfig(
                    scale_factor=0.01,
                    use_car_latents=False,
                    use_depth=True,
                    split_setting="reconstruction",
                ),
                train_num_rays_per_batch=4096,
                eval_num_rays_per_batch=4096,
                camera_optimizer=CameraOptimizerConfig(mode="off"),
            ),
            model=SceneGraphModelConfig(
                mono_depth_loss_mult=0.05,
                depth_loss_mult=0,
                background_model=NerfactoModelConfig(),
                object_model_template=NerfactoModelConfig(),
                object_representation="class-wise",
                object_ray_sample_strategy="remove-bg",
            ),
        ),
        optimizers={
            "background_model": {
                "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
            "learnable_global": {
                "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
            "object_model": {
                "optimizer": RAdamOptimizerConfig(lr=5e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
        },
        # viewer=ViewerConfig(num_rays_per_chunk=1 << 15),
        vis="wandb",
    ),
    description="Neural Scene Graph implementation with vanilla-NeRF model for backgruond and object models.",
)
```

**Comment by sonnefred** [comment]
> > > Hi, I trained the model using monocular depth, but the depth loss is like this, which didn't decrease stably, and the eval depth image is like the following. Could you please point out what the problem may be? Thanks. ![c05fcabbee9d5ee79c3d67e53](https://user-images.githubusercontent.com/66628395/259913136-882df39b-93c5-42fa-87bf-f1d4586f5ae0.png) ![91eb880b0baa6c186ba4b7fb9](https://user-images.githubusercontent.com/66628395/259913404-be637388-12a6-4045-86f3-569f156a6cee.png)
> > 
> > 
> > Hi! What multipliers do you apply to the mono_depth_loss and the general depth_loss?
> 
> I trained the model using this config.
> 
> ```
> KITTI_Recon_NSG_Car_Depth = MethodSpecification(
>     config=TrainerConfig(
>         method_name="nsg-kitti-car-depth-recon",
>         steps_per_eval_image=STEPS_PER_EVAL_IMAGE,
>         steps_per_eval_all_images=STEPS_PER_EVAL_ALL_IMAGES,
>         steps_per_save=STEPS_PER_SAVE,
>         max_num_iterations=MAX_NUM_ITERATIONS,
>         save_only_latest_checkpoint=False,
>         mixed_precision=False,
>         use_grad_scaler=True,
>         log_gradients=True,
>         pipeline=NSGPipelineConfig(
>             datamanager=NSGkittiDataManagerConfig(
>                 dataparser=NSGkittiDataParserConfig(
>                     scale_factor=0.01,
>                     use_car_latents=False,
>                     use_depth=True,
>                     split_setting="reconstruction",
>                 ),
>                 train_num_rays_per_batch=4096,
>                 eval_num_rays_per_batch=4096,
>                 camera_optimizer=CameraOptimizerConfig(mode="off"),
>             ),
>             model=SceneGraphModelConfig(
>                 mono_depth_loss_mult=0.05,
>                 depth_loss_mult=0,
>                 background_model=NerfactoModelConfig(),
>                 object_model_template=NerfactoModelConfig(),
>                 object_representation="class-wise",
>                 object_ray_sample_strategy="remove-bg",
>             ),
>         ),
>         optimizers={
>             "background_model": {
>                 "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15),
>                 "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
>             },
>             "learnable_global": {
>                 "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15),
>                 "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
>             },
>             "object_model": {
>                 "optimizer": RAdamOptimizerConfig(lr=5e-3, eps=1e-15),
>                 "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
>             },
>         },
>         # viewer=ViewerConfig(num_rays_per_chunk=1 << 15),
>         vis="wandb",
>     ),
>     description="Neural Scene Graph implementation with vanilla-NeRF model for backgruond and object models.",
> )
> ```

Hi, do you have any suggestion about this problem, I'm a bit confused. When I used monocular depth loss, the training result is even worse than without depth supervision ... Thanks in advance.

**Comment by wuzirui** [comment]
Hi, we think there's a visualization problem with the depth colormap. Could you please check the values of the predicted depths?

**Comment by sonnefred** [comment]
> Hi, we think there's a visualization problem with the depth colormap. Could you please check the values of the predicted depths?

Hi, I checked the values of the predicted depths. I generated the depth map following these codes, and the generated map is a 3-channel black-and-white picture and the pixel value is between 0-255. Is it right?
![depth_gen](https://github.com/OPEN-AIR-SUN/mars/assets/66628395/a70ca14b-9027-48e4-a38f-5c70937e7bb9)

**Comment by xuyanging** [comment]
> > 
> 
> Below is an example image that we generated with a [monocular depth estimation model](https://github.com/theNded/mini-omnidata). ![image](https://user-images.githubusercontent.com/107318439/259674700-415b2310-17cb-4232-becf-d58051af58c7.png)

**Comment by sonnefred** [comment]
Hi, I saw this part in the code, does this mean the depth image should be a one-channel image? And what range of the pixel values should be? Thanks.
![图片](https://github.com/OPEN-AIR-SUN/mars/assets/66628395/6e795b39-cd9d-48d5-8296-31c10f0873c8)

**Comment by wuzirui** [comment]
> Hi, I saw this part in the code, does this mean the depth image should be a one-channel image? And what range of the pixel values should be? Thanks. ![图片](https://user-images.githubusercontent.com/66628395/260617443-6e795b39-cd9d-48d5-8296-31c10f0873c8.png)

whatever format the depth maps you load will be transformed into a single-channel float tensor

**Comment by sonnefred** [comment]
Hi, I'm trying to reproduce the result on Kitti, but the loss curve is like this, the depth loss decreased at first, but it kept increasing later. Do you have any idea about this weird phenomenon? Thanks. 
![图片](https://github.com/OPEN-AIR-SUN/mars/assets/66628395/af55cb98-5dad-4472-8bfa-3c9d6c2eeb43)

**Comment by AIBUWAN** [comment]
![2023-09-01-10:54](https://github.com/OPEN-AIR-SUN/mars/assets/107452659/f75e366c-5d82-49ac-8b2f-8133f813a472)
@sonnefred Hi,  I loaded the depth map as a single-channel float tensor, but I still have the same problem, the mono depth loss won't go down, do you have any solution for this?

**Comment by amoghskanda** [comment]
> > > 
> > 
> > 
> > Below is an example image that we generated with a [monocular depth estimation model](https://github.com/theNded/mini-omnidata). ![image](https://user-images.githubusercontent.com/107318439/259674700-415b2310-17cb-4232-becf-d58051af58c7.png)
> 
> I follow the omnidata to generate the depth ,and I notice the channel is setted to be 1 .While the result I got is still 3-channel. ![000151](https://private-user-images.githubusercontent.com/74552396/259723879-7387d04d-b3ba-406d-986b-57ba32bc4f7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjQxNjUsIm5iZiI6MTcxMDgyMzg2NSwicGF0aCI6Ii83NDU1MjM5Ni8yNTk3MjM4NzktNzM4N2QwNGQtYjNiYS00MDZkLTk4NmItNTdiYTMyYmM0ZjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA0NTEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwOTA5YWY0OTk3MDQyOThlNjJkZTk0Y2QzYmRlNTAxMmIyMDNiYTE1NmVkMjJiNWE4OTU3NjFjMWMzM2RjYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IBKugodQNomCCOkfOu0fl2-Vdbwzy2y47txkCj1wAxg) What's the problem?

Same case here. My depth maps are 3-channel as well. Should you change the code anywhere or can you start training with depth maps being 3-channel?
