### ISSUE TITLE
Why the dataparser execute twice?

### ISSUE THREAD

**Issue by zwlvd** [OPEN-AIR-SUN/mars#39]
I notice that the dataparser execute twice with the same results. Why the function execute twice? It confuses me a lot.

> def _generate_dataparser_outputs(self, split="train"):

**Comment by wuzirui** [comment]
(to the best of our knowledges) all nerfstudio models process the dataparser twice~

**Comment by zwlvd** [comment]
Thank you very much. I will learn more about nerfstudio.
