### ISSUE TITLE
Poor edit performance

### ISSUE THREAD

**Issue by zwlvd** [OPEN-AIR-SUN/mars#40]
I try to edit the location of the car , and find the result is not very good. I make a little change of the x of the first car. I wonder if there are some tricks to edit.
![00002](https://github.com/OPEN-AIR-SUN/mars/assets/74552396/f64e4c8a-39f8-4293-bb48-fda836f785da)

> if camera_idx%237 in range(0, 8):
    pose[:, :, 0, 0] *= 1.5
                       
![rgb_00002](https://github.com/OPEN-AIR-SUN/mars/assets/74552396/d4bc3490-7809-4976-8094-145861e5e986)

**Comment by xBeho1der** [comment]
Please refer to issue #35 and #28, you should know what each dimension means in the pose and rotation tensor before editing the scene.

**Comment by xBeho1der** [comment]
Hi! As you can see, when you change the code with `pose[:, :, 0, 0] *= 1.5`, the performance of editing isn't good.

Generally, we just modify the last two dimensions of pose and the last dimension of rotation. For example:
```python
pose[:, :, 0, 2] = pose[:, :, 0, 2] + 1
rotation[:, :, 0] = rotation[:, :, 0] + 0.3
```
The above code changes the object with track id `0` in the last dimension of the pose(the concrete orientation depends on the dataset) and yaw.

But if we change with the following code, you can imagine that you are scaling the object in one dimension.
```python
pose[:, :, 0, 0] *= 1.5
```

I suggest that you render without any change as the control group instead of using the dataset image. In this way it's more convenient to observe the changes that you modify.

By the way, if we modify the car to a pose that we have never seen in the scene, the performance might be poor too.

I hope this is helpful to you!

**Comment by zwlvd** [comment]
> Hi! As you can see, when you change the code with `pose[:, :, 0, 0] *= 1.5`, the performance of editing isn't good.
> 
> Generally, we just modify the last two dimensions of pose and the last dimension of rotation. For example:
> 
> ```python
> pose[:, :, 0, 2] = pose[:, :, 0, 2] + 1
> rotation[:, :, 0] = rotation[:, :, 0] + 0.3
> ```
> 
> The above code changes the object with track id `0` in the dimension `2` of the pose(the concrete orientation depends on the dataset) and yaw.
> 
> But if we change with the following code, you can imagine that you are scaling the object in one dimension and changing the pose of dimension `0`. So the car will be stretched and shifted.
> 
> ```python
> pose[:, :, 0, 0] *= 1.5
> ```
> 
> I suggest that you render without any change as the control group instead of using the dataset image. In this way it's more convenient to observe the changes that you modify.
> 
> By the way, if we modify the car to a pose that we have never seen in the scene, the performance might be poor too.
> 
> I hope this is helpful to you!

Thank you for your detailed suggestions .It's of great help.

**Comment by Gniniug123** [comment]
> Hi! As you can see, when you change the code with `pose[:, :, 0, 0] *= 1.5`, the performance of editing isn't good.
> 
> Generally, we just modify the last two dimensions of pose and the last dimension of rotation. For example:
> 
> ```python
> pose[:, :, 0, 2] = pose[:, :, 0, 2] + 1
> rotation[:, :, 0] = rotation[:, :, 0] + 0.3
> ```
> 
> The above code changes the object with track id `0` in the dimension `2` of the pose(the concrete orientation depends on the dataset) and yaw.
> 
> But if we change with the following code, you can imagine that you are scaling the object in one dimension and changing the pose of dimension `0`. So the car will be stretched and shifted.
> 
> ```python
> pose[:, :, 0, 0] *= 1.5
> ```
> 
> I suggest that you render without any change as the control group instead of using the dataset image. In this way it's more convenient to observe the changes that you modify.
> 
> By the way, if we modify the car to a pose that we have never seen in the scene, the performance might be poor too.
> 
> I hope this is helpful to you!

@xBeho1der Thanks for your  detailed suggestions!But I want to know why this change will only be effective for objects with idx=0 in the future, instead of all objects will be changed?

**Comment by xBeho1der** [comment]
Hi! @Gniniug123 

The second-to-last dimension of the `pose` tensor selects the corresponding object.
