### ISSUE TITLE
Problem using custom dataset: camera poses and visible objects poses cannot be aligned properly

### ISSUE THREAD

**Issue by GimpelZhang** [OPEN-AIR-SUN/mars#42]
Hi all!

MARS is a great project which works well on kitti and vkitti dataset. But I would like to implement it on other datasets, like nuScenes, so multi cam images can be used in the model. 

However, after I tried to line up the nuScenes data with the "poses" and "visible_objects_" variables [L1044-1046](https://github.com/OPEN-AIR-SUN/mars/blob/1380b0881a7eb054de8acb20a2d5cb5f3aba7874/nsg/data/nsg_dataparser.py#L1046), the cam poses and the object bounding boxes seemed not to match. 

I concluded the mismatch from the following observation: 

During training, several eval images are saved, so we can see the rough bouding box positions in the "objects_depth_xxxxx.png" image ( at least in the early iterations, or maybe I was wrong ... ). Here are some samples of the eval images I got when training with nuScenes dataset (scene 0106). 

iter 500：

![img_500_647ef572ef50e7677631](https://github.com/OPEN-AIR-SUN/mars/assets/17154358/815254ab-af86-4eae-bd89-760e4abd1f84)
![objects_depth_500_bd587bbad1524bd8e658](https://github.com/OPEN-AIR-SUN/mars/assets/17154358/fda223ce-b085-44e9-b926-35da6278c1bc)

iter 2000:

![img_2000_26137c500c4b22c6b896](https://github.com/OPEN-AIR-SUN/mars/assets/17154358/3423fe1e-a206-4f0a-af30-cdc95980b32c)
![objects_depth_2000_7293bd957da773b57787](https://github.com/OPEN-AIR-SUN/mars/assets/17154358/0a74651e-362f-42f2-9828-7bf2e3faab9e)

iter 3000:

![img_3000_8e64a025b822d2ecb28a](https://github.com/OPEN-AIR-SUN/mars/assets/17154358/adccfaa7-7f0f-44b5-89d1-425c05fff965)
![objects_depth_3000_1588276b10c99438f7b2](https://github.com/OPEN-AIR-SUN/mars/assets/17154358/04fdf2b3-dd97-414b-931c-1af97ee6db03)

It seems to me that there is a certain translation or rotation "gap" between my object bbox poses and the correct ones. 

Is there any way that we can easily debug the camera poses and the visible objects poses? Or is there any special treatment on the kitti dataset we must pay extra attention on? 

Thanks a lot!

**Comment by wuzirui** [comment]
Hi, I am sorry that we don't have a silver bullet that can easily align camera and object poses. This is still one of the most tricky problems before we can train a perfect model. 

We have tried MARS on the NuScenes dataset, and we found that the camera & object pose from the dataset are extremely noisy. One potential fix is to run a SLAM method to refine all the poses, but we haven't tried that yet.

Hope this answer helps :)

**Comment by GimpelZhang** [comment]
Thanks a lot for the instructions! 

The problem is solved now.

**Comment by AmazingRoad** [comment]
@GimpelZhang Could you share your solution?

**Comment by AmazingRoad** [comment]
@GimpelZhang hello, did you train your data without latent-codes of car-model?

**Comment by GimpelZhang** [comment]
> @GimpelZhang Could you share your solution?

To sum up: 

1. We use the coordinate transformation from the nerfstudio nuScenes dataparser.
2. We use the pose "center" method from the nerfstudio nuScenes dataparser instead of the method from cam_util.

**Comment by GimpelZhang** [comment]
> @GimpelZhang hello, did you train your data without latent-codes of car-model?

The answer is yes, since I cannot use the [car nerf](https://github.com/lty2226262/Car_studio) model to train the latent-codes of nuScenes scenes.

**Comment by Sylvia6** [comment]
@GimpelZhang hello, I wonder how you align the obj pose, meeting some problems with it, can you give some suggestions

**Comment by GimpelZhang** [comment]
> @GimpelZhang hello, I wonder how you align the obj pose, meeting some problems with it, can you give some suggestions

Please make sure that obj poses are transfered by the same method using on cam poses. And for debugging, I suggest to plot the obj poses and cam poses at different stages to make sure they are in the same coord system.

**Comment by MaRongbo** [comment]
hello, I meet the same coordinate system problem. Could you explain the transform about the below code in `nerfstudio/nerfstudio/data/dataparsers/nuscenes_dataparser.py`?Many thanks!!!
```python
        transform1 = np.array(
            [
                [0, -1, 0, 0],
                [0, 0, -1, 0],
                [1, 0, 0, 0],
                [0, 0, 0, 1],
            ]
        )
        transform2 = np.array(
            [
                [0, 0, 1, 0],
                [0, 1, 0, 0],
                [-1, 0, 0, 0],
                [0, 0, 0, 1],
            ]
          ........
          pose = ego_pose @ cam_pose

          # 1 rotate to opencv frame
          pose = transform1 @ pose

          # 2 convert from opencv camera to nerfstudio camera 
          pose[0:3, 1:3] *= -1
          pose = pose[np.array([1, 0, 2, 3]), :]
          pose[2, :] *= -1

          # 3 rotate to z-up in viewer 
          pose = transform2 @ pose
```
As we can see in the code, the transform consist 3 step.
# Step 1:  rotate to opencv frame
I have no quesion
# Step2: convert from opencv camera to nerfstudio camera. 
The question is what's the nerfstudio camera coordinate system? As far as I know, the nerfstudio camera coordinate system is same as OpenGL, whose direction is 
![image](https://github.com/OPEN-AIR-SUN/mars/assets/96866008/f8f925f8-fa9e-4c8b-b512-379309253242)
the opencv  coordinate system is 
![image](https://github.com/OPEN-AIR-SUN/mars/assets/96866008/4aa0af8a-047e-40d3-96a7-64623732b486)
so the transform should be
```
X_opengl=X_opencv,
Y_opengl=-Y_opencv,
Z_opengl=-Z_opencv
```
it is not same with the step2 code.
# Step3:  
What's the meaning of rotate to z-up in viewer?

**Comment by MaRongbo** [comment]
> hello, I meet the same coordinate system problem. Could you explain the transform about the below code in `nerfstudio/nerfstudio/data/dataparsers/nuscenes_dataparser.py`?Many thanks!!!
> 
> ```python
>         transform1 = np.array(
>             [
>                 [0, -1, 0, 0],
>                 [0, 0, -1, 0],
>                 [1, 0, 0, 0],
>                 [0, 0, 0, 1],
>             ]
>         )
>         transform2 = np.array(
>             [
>                 [0, 0, 1, 0],
>                 [0, 1, 0, 0],
>                 [-1, 0, 0, 0],
>                 [0, 0, 0, 1],
>             ]
>           ........
>           pose = ego_pose @ cam_pose
> 
>           # 1 rotate to opencv frame
>           pose = transform1 @ pose
> 
>           # 2 convert from opencv camera to nerfstudio camera 
>           pose[0:3, 1:3] *= -1
>           pose = pose[np.array([1, 0, 2, 3]), :]
>           pose[2, :] *= -1
> 
>           # 3 rotate to z-up in viewer 
>           pose = transform2 @ pose
> ```
> 
> As we can see in the code, the transform consist 3 step.
> 
> # Step 1: rotate to opencv frame
> I have no quesion
> 
> # Step2: convert from opencv camera to nerfstudio camera.
> The question is what's the nerfstudio camera coordinate system? As far as I know, the nerfstudio camera coordinate system is same as OpenGL, whose direction is ![image](https://user-images.githubusercontent.com/96866008/261957479-f8f925f8-fa9e-4c8b-b512-379309253242.png) the opencv coordinate system is ![image](https://user-images.githubusercontent.com/96866008/261957582-4aa0af8a-047e-40d3-96a7-64623732b486.png) so the transform should be
> 
> ```
> X_opengl=X_opencv,
> Y_opengl=-Y_opencv,
> Z_opengl=-Z_opencv
> ```
> 
> it is not same with the step2 code.
> 
> # Step3:
> What's the meaning of rotate to z-up in viewer?

@GimpelZhang Could you give some advise?

**Comment by GimpelZhang** [comment]
> > hello, I meet the same coordinate system problem. Could you explain the transform about the below code in `nerfstudio/nerfstudio/data/dataparsers/nuscenes_dataparser.py`?Many thanks!!!
> > ```python
> >         transform1 = np.array(
> >             [
> >                 [0, -1, 0, 0],
> >                 [0, 0, -1, 0],
> >                 [1, 0, 0, 0],
> >                 [0, 0, 0, 1],
> >             ]
> >         )
> >         transform2 = np.array(
> >             [
> >                 [0, 0, 1, 0],
> >                 [0, 1, 0, 0],
> >                 [-1, 0, 0, 0],
> >                 [0, 0, 0, 1],
> >             ]
> >           ........
> >           pose = ego_pose @ cam_pose
> > 
> >           # 1 rotate to opencv frame
> >           pose = transform1 @ pose
> > 
> >           # 2 convert from opencv camera to nerfstudio camera 
> >           pose[0:3, 1:3] *= -1
> >           pose = pose[np.array([1, 0, 2, 3]), :]
> >           pose[2, :] *= -1
> > 
> >           # 3 rotate to z-up in viewer 
> >           pose = transform2 @ pose
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > As we can see in the code, the transform consist 3 step.
> > # Step 1: rotate to opencv frame
> > I have no quesion
> > # Step2: convert from opencv camera to nerfstudio camera.
> > The question is what's the nerfstudio camera coordinate system? As far as I know, the nerfstudio camera coordinate system is same as OpenGL, whose direction is ![image](https://user-images.githubusercontent.com/96866008/261957479-f8f925f8-fa9e-4c8b-b512-379309253242.png) the opencv coordinate system is ![image](https://user-images.githubusercontent.com/96866008/261957582-4aa0af8a-047e-40d3-96a7-64623732b486.png) so the transform should be
> > ```
> > X_opengl=X_opencv,
> > Y_opengl=-Y_opencv,
> > Z_opengl=-Z_opencv
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it is not same with the step2 code.
> > # Step3:
> > What's the meaning of rotate to z-up in viewer?
> 
> @GimpelZhang Could you give some advise?

To tell you the truth, I just take the coord transform in nerfstudio code for granted. So I didn't check every step of the transformation.

**Comment by GimpelZhang** [comment]
> @GimpelZhang
> 
> the dim we get from Nuscenes is wlh, and did you change it to (lenght, height, width) for obj_pose?

Yes, we must make the dims correct.

**Comment by AmazingRoad** [comment]
> > @GimpelZhang
> > the dim we get from Nuscenes is wlh, and did you change it to (lenght, height, width) for obj_pose?
> 
> Yes, we must make the dims correct.

For nuscenes, I have some ideas to share. I understand the dims should be corresponding to the order of position. Since the order of position is xyz,  so the order of dims should be lwh. At the same time, you should change the functions （ rotate_yaw and world2object） , becasue z is up, and postion is the center of 3DBox in nuscenes

![image](https://github.com/OPEN-AIR-SUN/mars/assets/53403532/fd1126eb-41ca-4597-aecf-2ca046979d70)

![image](https://github.com/OPEN-AIR-SUN/mars/assets/53403532/31dff3d6-de0a-40c6-b941-d308729369d0)

**Comment by AmazingRoad** [comment]
> > @GimpelZhang
> > the dim we get from Nuscenes is wlh, and did you change it to (lenght, height, width) for obj_pose?
> 
> Yes, we must make the dims correct.

@GimpelZhang  @wuzirui Another question, the fps of nuscenes is 2Hz for key frame, and the reconstruction effect is poor. What your solution for this question?

**Comment by AmazingRoad** [comment]
> > > > @GimpelZhang
> > > > the dim we get from Nuscenes is wlh, and did you change it to (lenght, height, width) for obj_pose?
> > > 
> > > 
> > > Yes, we must make the dims correct.
> > 
> > 
> > @GimpelZhang @wuzirui Another question, the fps of nuscenes is 2Hz for key frame, and the reconstruction effect is poor. What your solution for this question?
> 
> 1. There must be some open source methods dealing with the annotation interpolation between samples for the nuScenes dataset (not sure).
> 2. According to [this paper](https://arxiv.org/abs/2308.04413), depth map supervision can improve the model performance in this sparse view problem. However, I didn't see much difference in the rgb image reconstruction results after I use the monocular depth prediction.

@GimpelZhang My reconstruction‘s effect on Nuscenes is poor.  Only in scene0400, the background reconstruction is ok, and I think it is beacuse that the ego-car is static. How about you?

**Comment by szhang963** [comment]
@GimpelZhang hi, I'd greatly appreciate your help with something about nuScene. I have a question I'd like to ask you. Did you use the 6v cameras in nuScene dataset for mars? Is it possible for me to request  code of nuScene dataparser? This is my e-mail szhang5566@gmail.com.

**Comment by szhang963** [comment]
@GimpelZhang  hi, I'd greatly appreciate your help with something about nuScene. I have a question I'd like to ask you. Did you use the 6v cameras in nuScene dataset for mars? Is it possible for me to request code of nuScene dataparser? This is my e-mail szhang5566@gmail.com.
Thank you very much in advance.
