### ISSUE TITLE
Adapt custom dataset error: No inf checks were recorded for this optimizer.

### ISSUE THREAD

**Issue by MaRongbo** [OPEN-AIR-SUN/mars#43]
hi, I'm debugging the cam pose on my own dataset, I just change this line as below
replace `poses = (kitti2vkitti @ cam_poses_tracking).astype(np.float32)`  with 
`poses = np.copy(cam_poses_tracking).astype(np.float32)`  
![image](https://github.com/OPEN-AIR-SUN/mars/assets/96866008/26ce3a03-6377-4e79-8c75-224ba7c77a97)
then I encounter an error
![image](https://github.com/OPEN-AIR-SUN/mars/assets/96866008/f5e6c1d1-8e0a-4315-98a2-e4999dd96910)
Have you ever encountered this problem? 
Many thanks!

**Comment by wuzirui** [comment]
this is probably an issue with nerfstudio & tiny-cuda-nn, reference: [1](https://github.com/nerfstudio-project/nerfstudio/issues/1684), [2](https://github.com/nerfstudio-project/nerfstudio/issues/1694), [3](https://github.com/nerfstudio-project/nerfstudio/pull/1919)

**Comment by wuzirui** [comment]
this problem is common when you have wrong coordinate axes (which eventually cause numerical over/underflows). Generally, we require a world coordinate whose y-axis is vertical and an OpenGL camera coordinate.
