### ISSUE TITLE
A question about VRAM and training time

### ISSUE THREAD

**Issue by chuanshuogushi** [OPEN-AIR-SUN/mars#45]
I want to know if it's normal to only have around 3GB of VRAM usage when training on the KITTI dataset scene 0005. It's taking around 5 days on a 3090 GPU. Are there any parameters that can be configured to speed up the training? Thanks.

**Comment by xBeho1der** [comment]
Hi! Thanks for your reply!

> I want to know if it's normal to only have around 3GB of VRAM usage when training on the KITTI dataset scene 0005. 

It's abnormal. All of our model is trained with a single NVIDIA A4000/2080 Ti graphic card and using VRAM around 10G~15G. Maybe you should check the batch size and parameters of the model that you selected.

> It's taking around 5 days on a 3090 GPU. Are there any parameters that can be configured to speed up the training? 

To speed up the training, you can do as following:
- Reducing the training sequence by modifying `first_frame` and `last_frame` in dataparser.
- Modifying `max_num_iterations` in your training config. 
- Modifying `steps_per_eval_image` and `steps_per_eval_all_images` as it will take a long time while evaluating a long training sequence.

**Comment by chuanshuogushi** [comment]
Thank you for your reply! 
I haven't used depth information and panoptic information. Parameters are default values and haven't been changed. I'd like know your processing speed. Mine is about **1.8k rays/sec.** I'm not sure where the issue lies.
![截屏2023-08-18 19 13 12](https://github.com/OPEN-AIR-SUN/mars/assets/49110711/06247493-2a4c-4757-9368-3339000a6ee8)

**Comment by xBeho1der** [comment]
Here is an example that I train on KITTI 0005 on NVIDIA RTX A4000 without depth and panoptic information, using nerfacto as both background and object model, and it allocates 10G VRAM.

![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/9939a1dd-d073-479b-b95a-9973df52aeb2)

**Comment by chuanshuogushi** [comment]
> Here is an example that I train on KITTI 0005 on NVIDIA RTX A4000 without depth and panoptic information, using nerfacto as both background and object model, it allocates around 10G VRAM.
> 
But I saw in **cicai_config.py**, **Carnerf** is used as object model in `method_name="nsg-kitti-car-depth-recon"`.Does that mean Carnerf = Nerfacto?

**Comment by wuzirui** [comment]
the config for mem consumption is provided **just to be specific**. the differences in mem consumptions are minimal.
