### ISSUE TITLE
A huge tensor appeared while train on the kitti-MOT dataset.

### ISSUE THREAD

**Issue by Zazexy** [OPEN-AIR-SUN/mars#47]
I met the problem when I running ns-train using kitti dataset. It showed that a memory-boom tensor appears in `/mars/nsg/data/nsg_dataparser.py`. Actually, this single tensor takes about 40GB memory.  I found that this tensor was built in this code blocks:
``` 
       input_size = 0

        obj_nodes_tensor = torch.from_numpy(obj_nodes)
        # if self.config.fast_loading:
        #     obj_nodes_tensor = obj_nodes_tensor.cuda()
        print(obj_nodes_tensor.shape)
        obj_nodes_tensor = obj_nodes_tensor[:, :, None, ...].repeat_interleave(image_width, dim=2)
        print(obj_nodes_tensor.shape)
        print(image_width,'*',image_height)
        obj_nodes_tensor = obj_nodes_tensor[:, :, None, ...].repeat_interleave(image_height, dim=2)

        obj_size = self.max_input_objects * add_input_rows
        input_size += obj_size
```
The console log(I make some outputs about the `obj_nodes_tensor`):
![image](https://github.com/OPEN-AIR-SUN/mars/assets/68093830/436ff8a0-86e1-4f6c-b543-bc3c9fa0a551)

I caculated it as follow( I'm not actually sure):
`512 * 14 * 1242 * 3 * 375 * 4(dtype)=40061952000Bytes(40g)`
So, were there any error operations I have made? If not, how can I deal with the highly-cost tensor since that I haven't enough cpu or gpu resource to put it in? I look forward to hearing from you soon.

**Comment by xBeho1der** [comment]
Hi! Thanks for your reply! You haven't made any error operations. Maybe you can reduce the number of frames that you choose to train with and try again.

**Comment by Zazexy** [comment]
Thanks! I'll try it!
