### ISSUE TITLE
Why does rendered video show a black screen when playing?

### ISSUE THREAD

**Issue by gaga0714** [OPEN-AIR-SUN/mars#48]
With the command
```python
python /root/autodl-fs/tiny-cuda-nn/mars/scripts/cicai_render.py --load-config /root/autodl-fs/outputs/clone/nsg-vkitti-car-depth-recon/2023-08-19_174218/config.yml --output-path /root/autodl-fs/renders/output.mp4
```
I get the rendered video:
https://github.com/OPEN-AIR-SUN/mars/assets/140368447/bcc18bd8-79a3-4865-8c07-ec784371eb97

Why does it only play properly on iOS devices but show a black screen when playing on other devices?

**Comment by xBeho1der** [comment]
Hi! That's confusing as the video can be played on the web. I kindly suggest you set the render result to `images` instead of `video` and then you can compose the rendered images into a video. In this way, you can check whether the video has some problems and you can modify the `fps` more conveniently.

**Comment by gaga0714** [comment]
> Hi! That's confusing as the video can be played on the web. I kindly suggest you set the render result to `images` instead of `video` and then you can compose the rendered images into a video. In this way, you can check whether the video has some problems and you can modify the `fps` more conveniently.

Thanks for your reply. The rendered images are normal and the video can be played on the web. But when I download the video file, it just shows a black screen on the computer. I will try to compose the rendered images into a video.
