### ISSUE TITLE
The interlevel loss is increasing

### ISSUE THREAD

**Issue by sonnefred** [OPEN-AIR-SUN/mars#49]
Hi, I'm trying to reproduce the result on KITTI, but I find the interlevel loss is increasing during the training process, is this normal? Could you explain a bit about the usage of this loss function? Can I just set its weight to zero? Thanks.

**Comment by wuzirui** [comment]
It is normal to have an increasing interlevel loss, as long as it keeps a low value. The interlevel loss is for nerfacto, you can see MipNeRF-360 or ZipNeRF for more details.
