### ISSUE TITLE
Error: latents not exist

### ISSUE THREAD

**Issue by rockywind** [OPEN-AIR-SUN/mars#5]
I met the error below.
````
           Saving config to: outputs/0006/ablation-no-depth-kitti/2023-07-31_015043/config.yml  experiment_config.py:128
[01:50:44] Saving checkpoints to:                                                                         trainer.py:138
           outputs/0006/ablation-no-depth-kitti/2023-07-31_015043/nerfstudio_models                                     
[01:50:45] [array([0.]), array([1.]), array([2.]), array([7.]), array([8.]), array([3.]),          nsg_dataparser.py:843
           array([4.]), array([9.]), array([5.]), array([12.]), array([6.]), array([10.]),                              
           array([11.]), array([13.]), array([14.])] in this scene.                                                     
Error: latents not exist
````
The running script is below.
````
python nerfstudio/nerfstudio/scripts/train.py ablation-no-depth-kitti --data /rockywin.wang/NeRF/mars/data/kitti_tracking/training/image_02/0006
````

**Comment by xBeho1der** [comment]
> I met the error below.
> 
> ```
>            Saving config to: outputs/0006/ablation-no-depth-kitti/2023-07-31_015043/config.yml  experiment_config.py:128
> [01:50:44] Saving checkpoints to:                                                                         trainer.py:138
>            outputs/0006/ablation-no-depth-kitti/2023-07-31_015043/nerfstudio_models                                     
> [01:50:45] [array([0.]), array([1.]), array([2.]), array([7.]), array([8.]), array([3.]),          nsg_dataparser.py:843
>            array([4.]), array([9.]), array([5.]), array([12.]), array([6.]), array([10.]),                              
>            array([11.]), array([13.]), array([14.])] in this scene.                                                     
> Error: latents not exist
> ```
> 
> The running script is below.
> 
> ```
> python nerfstudio/nerfstudio/scripts/train.py ablation-no-depth-kitti --data /rockywin.wang/NeRF/mars/data/kitti_tracking/training/image_02/0006
> ```

If you use the category-level object model, please ensure that the use_car_latents=True and the latent codes exist. We provide latent codes of some sequences on KITTI-MOT and vKITTI2 datasets [here](https://drive.google.com/drive/folders/1E4YjMwkDbRsF4Hb1UK0iBDkz-tFVx3Me?usp=sharing).

**Comment by rockywind** [comment]
Thanks a lot!

**Comment by wuzirui** [comment]
Hi @rockywind, sorry for the inconvenience, but we just confirmed that there's an issue in loading the car model's checkpoint. The `use_car_latents` is expected to load a pre-trained [CarNeRF](https://lty2226262.github.io/car-studio/) model. This logic works in training a complete MARS model from scratch but may cause significant performance loss in loading a trained MARS model since the `use_car_latents` config tells the model to overwrite the model weight of the CarNeRF model (which is optimized through the MARS training loops). On the other hand, this performance drop can be temporally solved by continuing training the model for additional steps ([wandb](https://wandb.ai/yexy/nerfstudio-project/runs/cm49qleq)).

We will fix this issue asap.

**Comment by rockywind** [comment]
Hi, thanks for reply!
How to run the code ,without depth completion dir and no car_latents dir?

**Comment by wuzirui** [comment]
You can train a MARS model without depth supervision and select other object representations other than the CarNeRF (e.g. Nerfacto).

**Comment by rockywind** [comment]
Hi, 
I confused about that the nerfacto in mars is different the nerfacto in nerfstudio.

**Comment by wuzirui** [comment]
There are slight differences that are necessary before plugging in Mars. E.g., we also support using category-level nerfacto with instance-wise latent codes used in the forward pass.

**Comment by rockywind** [comment]
Hi,
I met the error below.
````
[02:59:06] Saving checkpoints to: outputs/0006/nerfacto/2023-07-31_025905/nerfstudio_models               trainer.py:138
Traceback (most recent call last):
  File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/scripts/train.py", line 269, in <module>
    entrypoint()
  File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/scripts/train.py", line 260, in entrypoint
    main(
  File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/scripts/train.py", line 246, in main
    launch(
  File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/scripts/train.py", line 185, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/engine/trainer.py", line 151, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/configs/base_config.py", line 58, in setup
    return self._target(self, **kwargs)
  File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 243, in __init__
    self.datamanager: VanillaDataManager = config.datamanager.setup(
  File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/configs/base_config.py", line 58, in setup
    return self._target(self, **kwargs)
  File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 374, in __init__
    self.train_dataparser_outputs = self.dataparser.get_dataparser_outputs(split="train")
  File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/data/dataparsers/base_dataparser.py", line 162, in get_dataparser_outputs
    dataparser_outputs = self._generate_dataparser_outputs(split)
  File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/data/dataparsers/nerfstudio_dataparser.py", line 83, in _generate_dataparser_outputs
    meta = load_from_json(self.config.data / "transforms.json")
  File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/utils/io.py", line 30, in load_from_json
    with open(filename, encoding="UTF-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/rockywin.wang/NeRF/mars/data/kitti_tracking/training/image_02/0006/transforms.json'
````
The running script is below.
````
python nerfstudio/nerfstudio/scripts/train.py nerfacto --data /rockywin.wang/NeRF/mars/data/kitti_tracking/training/image_02/0006

````

**Comment by xBeho1der** [comment]
Thank you for your feedback! Here is an example config without depth completion dir and car latent codes dir.
```python
Ablation_no_depth_kitti = MethodSpecification(
    config=TrainerConfig(
        method_name="ablation-no-depth-kitti",
        steps_per_eval_image=STEPS_PER_EVAL_IMAGE,
        steps_per_eval_all_images=STEPS_PER_EVAL_ALL_IMAGES,
        steps_per_save=STEPS_PER_SAVE,
        max_num_iterations=MAX_NUM_ITERATIONS,
        save_only_latest_checkpoint=False,
        mixed_precision=False,
        use_grad_scaler=True,
        log_gradients=True,
        pipeline=NSGPipelineConfig(
            datamanager=NSGkittiDataManagerConfig(
                dataparser=NSGkittiDataParserConfig(
                    use_car_latents=False,
                    use_depth=False,
                    split_setting="reconstruction",
                ),
                train_num_rays_per_batch=4096,
                eval_num_rays_per_batch=4096,
                camera_optimizer=CameraOptimizerConfig(mode="off"),
            ),
            model=SceneGraphModelConfig(
                background_model=NerfactoModelConfig(),
                object_model_template=NerfactoModelConfig(),
                object_representation="class-wise",
                object_ray_sample_strategy="remove-bg",
            ),
        ),
        optimizers={
            "background_model": {
                "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
            "learnable_global": {
                "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
            "object_model": {
                "optimizer": RAdamOptimizerConfig(lr=5e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
        },
        # viewer=ViewerConfig(num_rays_per_chunk=1 << 15),
        vis="wandb",
    ),
    description="Neural Scene Graph implementation with vanilla-NeRF model for backgruond and object models.",
)
```

> Hi, thanks for reply! How to run the code ,without depth completion dir and no car_latents dir?

**Comment by wuzirui** [comment]
> Hi, I met the error below.
> 
> ```
> [02:59:06] Saving checkpoints to: outputs/0006/nerfacto/2023-07-31_025905/nerfstudio_models               trainer.py:138
> Traceback (most recent call last):
>   File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/scripts/train.py", line 269, in <module>
>     entrypoint()
>   File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/scripts/train.py", line 260, in entrypoint
>     main(
>   File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/scripts/train.py", line 246, in main
>     launch(
>   File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/scripts/train.py", line 185, in launch
>     main_func(local_rank=0, world_size=world_size, config=config)
>   File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/scripts/train.py", line 99, in train_loop
>     trainer.setup()
>   File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/engine/trainer.py", line 151, in setup
>     self.pipeline = self.config.pipeline.setup(
>   File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/configs/base_config.py", line 58, in setup
>     return self._target(self, **kwargs)
>   File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 243, in __init__
>     self.datamanager: VanillaDataManager = config.datamanager.setup(
>   File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/configs/base_config.py", line 58, in setup
>     return self._target(self, **kwargs)
>   File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 374, in __init__
>     self.train_dataparser_outputs = self.dataparser.get_dataparser_outputs(split="train")
>   File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/data/dataparsers/base_dataparser.py", line 162, in get_dataparser_outputs
>     dataparser_outputs = self._generate_dataparser_outputs(split)
>   File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/data/dataparsers/nerfstudio_dataparser.py", line 83, in _generate_dataparser_outputs
>     meta = load_from_json(self.config.data / "transforms.json")
>   File "/rockywin.wang/NeRF/mars/nerfstudio/nerfstudio/utils/io.py", line 30, in load_from_json
>     with open(filename, encoding="UTF-8") as file:
> FileNotFoundError: [Errno 2] No such file or directory: '/rockywin.wang/NeRF/mars/data/kitti_tracking/training/image_02/0006/transforms.json'
> ```
> 
> The running script is below.
> 
> ```
> python nerfstudio/nerfstudio/scripts/train.py nerfacto --data /rockywin.wang/NeRF/mars/data/kitti_tracking/training/image_02/0006
> ```

It seems that you are trying to train a Nerfacto on the KITTI-MOT dataset. If you want to use our KITTI-dataparser only, you may need to modify configs manually.

**Comment by wutongtong** [comment]
> Hi @rockywind, sorry for the inconvenience, but we just confirmed that there's an issue in loading the car model's checkpoint. The `use_car_latents` is expected to load a pre-trained [CarNeRF](https://lty2226262.github.io/car-studio/) model. This logic works in training a complete MARS model from scratch but may cause significant performance loss in loading a trained MARS model since the `use_car_latents` config tells the model to overwrite the model weight of the CarNeRF model (which is optimized through the MARS training loops). On the other hand, this performance drop can be temporally solved by continuing training the model for additional steps ([wandb](https://wandb.ai/yexy/nerfstudio-project/runs/cm49qleq)).
> 
> We will fix this issue asap.

Hi, Can you tell me how to fix the CarNeRF model in the MARS training loops, many thanks.

**Comment by why529913** [comment]
latents path changed under mars/cicai_configs.py?

**Comment by xBeho1der** [comment]
> latents path changed under mars/cicai_configs.py?

@why529913 Yes. But you need to install `mars-nerfstudio` locally, or you ought to modify the code in your python lib.

**Comment by amoghskanda** [comment]
> You can train a MARS model without depth supervision and select other object representations other than the CarNeRF (e.g. Nerfacto). Later I will provide a runnable config here, sorry for the inconvenience.

hey, any updates? I was planning on using Nerfacto instead of CarNeRF

**Comment by Akash-Kumbar** [comment]
> Thank you for your feedback! Here is an example config without depth completion dir and car latent codes dir.
> 
> ```python
> Ablation_no_depth_kitti = MethodSpecification(
>     config=TrainerConfig(
>         method_name="ablation-no-depth-kitti",
>         steps_per_eval_image=STEPS_PER_EVAL_IMAGE,
>         steps_per_eval_all_images=STEPS_PER_EVAL_ALL_IMAGES,
>         steps_per_save=STEPS_PER_SAVE,
>         max_num_iterations=MAX_NUM_ITERATIONS,
>         save_only_latest_checkpoint=False,
>         mixed_precision=False,
>         use_grad_scaler=True,
>         log_gradients=True,
>         pipeline=NSGPipelineConfig(
>             datamanager=NSGkittiDataManagerConfig(
>                 dataparser=NSGkittiDataParserConfig(
>                     use_car_latents=False,
>                     use_depth=False,
>                     split_setting="reconstruction",
>                 ),
>                 train_num_rays_per_batch=4096,
>                 eval_num_rays_per_batch=4096,
>                 camera_optimizer=CameraOptimizerConfig(mode="off"),
>             ),
>             model=SceneGraphModelConfig(
>                 background_model=NerfactoModelConfig(),
>                 object_model_template=NerfactoModelConfig(),
>                 object_representation="class-wise",
>                 object_ray_sample_strategy="remove-bg",
>             ),
>         ),
>         optimizers={
>             "background_model": {
>                 "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15),
>                 "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
>             },
>             "learnable_global": {
>                 "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15),
>                 "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
>             },
>             "object_model": {
>                 "optimizer": RAdamOptimizerConfig(lr=5e-3, eps=1e-15),
>                 "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
>             },
>         },
>         # viewer=ViewerConfig(num_rays_per_chunk=1 << 15),
>         vis="wandb",
>     ),
>     description="Neural Scene Graph implementation with vanilla-NeRF model for backgruond and object models.",
> )
> ```
> 
> > Hi, thanks for reply! How to run the code ,without depth completion dir and no car_latents dir?

Did you get a solution for this?
