### ISSUE TITLE
how many cameras used in DAIR-V2X dataset

### ISSUE THREAD

**Issue by wutongtong** [OPEN-AIR-SUN/mars#50]
As KITTI dataset has left and right cameras, how many cameras has been used for training in DAIR-V2X dataset?

**Comment by wuzirui** [comment]
Hi, the DAIRV2X dataset is not intended to design for reconstruction, thus the pose are a bit noisy to use. We only use the roadside views in our exps.

**Comment by wutongtong** [comment]
thank you for your relpy, I have another question, how to get the track id information in DAIR-V2X dataset?
