### ISSUE TITLE
About Edit the Scene

### ISSUE THREAD

**Issue by loyris** [OPEN-AIR-SUN/mars#51]
Excellent work!!!
Can you specifically describe how to 
1. perform vehicle addition and removal 
2. change the camera Angle 
3. know the vehicle id in the scene. 
in the cicai_render.py?
Thank you very much

**Comment by AmazingRoad** [comment]
the same question as #35  ?

**Comment by wuzirui** [comment]
> the same question as #35  ?

yes, thx

**Comment by xBeho1der** [comment]
#40

**Comment by wuzirui** [comment]
adding/removing is basically the same, can be done by manipulating obj info
