### ISSUE TITLE
depth map of completion_02&completion_03

### ISSUE THREAD

**Issue by gallenszl** [OPEN-AIR-SUN/mars#53]
Hello, I have read the issue and notice the used depth is acquired by a monocular depth estimation method. Could you just give us the generated depth map of the 0006 sequence so that we can directly reproduce your result? Besides, how about the performance of using the raw lidar depth provided by KITTI?

**Comment by xBeho1der** [comment]
Hi! Thanks for your reply!

>  Could you just give us the generated depth map of the 0006 sequence so that we can directly reproduce your result?

[Here](https://drive.google.com/drive/folders/1Y-41OMCzDkdJ2P-YZHtCI-5YR9jAIKS2?usp=sharing) is the estimation result of 0006 sequence of KITTI datasets generated by [mini-omnidata](https://github.com/theNded/mini-omnidata).

> Besides, how about the performance of using the raw lidar depth provided by KITTI?

Please refer to #2.

![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/6d6d6ddc-f8c9-40af-a92a-88340161f711)
