### ISSUE TITLE
How to obtain intuitive 3D results.

### ISSUE THREAD

**Issue by Zazexy** [OPEN-AIR-SUN/mars#54]
Dear author,
Hello. I encountered an issue when using the command` ns-render` to render my model results. Even though I changed the file name of the output file to `.mp4` extension, the result is still a bunch of rendered images in my folder. Then, when I opened the Nerf Studio webpage using the command `ns-viewer`, I got an unordered green screen and a stack of overlapping photos instead of a 3D scene generation. This prevents me from confirming the 3D scene generated by my model from any perspective.

I used approximately **30** photos (_lastframe_-_firstframe_=30), trained for about **60000** iterations, and the _PSNR_ convergence value is **24.25**( The rendered pictures performance very well ). I would like to know if this issue is related to the small number of my train-set or if there may be some other problems.

 Furthermore, I would like to ask if there are **any other good methods** to obtain visualized results of 3D scenes apart from `ns-viewer`. I look forward to your reply.

**Comment by xBeho1der** [comment]
Hi! Thanks for your reply!

> I encountered an issue when using the command ns-render to render my model results. Even though I changed the file name of the output file to .mp4 extension, the result is still a bunch of rendered images in my folder.

We kindly suggest using `scripts/cicai_render.py` to render your result. In this script you can easily modify the output format.

![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/27b9dcb3-8f88-4c81-9bd6-59590e30aaf6)

> Then, when I opened the Nerf Studio webpage using the command ns-viewer, I got an unordered green screen and a stack of overlapping photos instead of a 3D scene generation. This prevents me from confirming the 3D scene generated by my model from any perspective.

You need to manually modify the output channel in niewer.

![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/2543d10e-9781-45c5-a77e-4ade227450bd)

> I used approximately 30 photos (lastframe-firstframe=30), trained for about 60000 iterations, and the PSNR convergence value is 24.25( The rendered pictures performance very well ). I would like to know if this issue is related to the small number of my train-set or if there may be some other problems.

The rendered results are not directly strongly correlated with the number of training images. But if you train with a longer sequence, the PSNR might be affected.

> Furthermore, I would like to ask if there are any other good methods to obtain visualized results of 3D scenes apart from ns-viewer. I look forward to your reply.

We currently only support obtaining 3D visualization results through ns-viewer.

**Comment by Zazexy** [comment]
Thanks a lot for your work and reply!

**Comment by Zazexy** [comment]
Sorry for reopen the issue. I tried to solve problems following your reply, but I didn't success.

I set the ns-viewer like what you show in comment, but I still get the under result:
![render_result](https://github.com/OPEN-AIR-SUN/mars/assets/68093830/2ef66d38-4f79-4003-b023-cc89ddf8cd48)
And I get a very little size video file ( about 300KB ) when I fix the `output_format = "video"` ( btw , input_frames=30, times about 60000). It's abnormal since the size of each picture I used to train from kitti image 0006 takes more than 500KB.

 I'm waiting for your reply.

**Comment by xBeho1der** [comment]
Hi! Thanks for your reply!

> I set the ns-viewer like what you show in comment, but I still get the under result:

To obtain visualization results of the reconstructed 3D scene, you should set `Output Render` to `rgb`. For different output channels, you should modify it to corresponding options.

> And I get a very little size and unplay video file ( about 300KB ) when I fix the output_format = "video" ( btw , input_frames=30, times about 60000). It's abnormal since each picture I used to train from kitti image 0006 takes more than 500KB.

Please have a try with `scripts/cicai_render.py`.

**Comment by gallenszl** [comment]
@xBeho1der 
hello, i met the similar issue. According the latest suggestion, i have changed the ourput render to rgb. However, i sill don't get any reasonable visualization.
![image](https://github.com/OPEN-AIR-SUN/mars/assets/57089550/b747b191-a867-4a4d-993e-31e978383da9)

**Comment by xBeho1der** [comment]
Hi! @gallenszl 

1. Maybe resetting the up direction might help you better observe the scene. Click `SCENE` and you will find the button.
2. You should click one image after resetting up direction, and then you can change the viewport following the guidance. Below is an example image.

![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/1011dfc2-118d-49a0-a7c3-4b13f6f42f41)

<img width="960" alt="f0d7f9c8581e4ed131445db6b6efb9d" src="https://github.com/OPEN-AIR-SUN/mars/assets/107318439/5b60683a-3d34-402b-83b2-f5e8d0ce0798">

**Comment by Zazexy** [comment]
> Hi! Thanks for your reply!
> 
> > I set the ns-viewer like what you show in comment, but I still get the under result:
> 
> To obtain visualization results of the reconstructed 3D scene, you should set `Output Render` to `rgb`. For different output channels, you should modify it to corresponding options.
> 
> > And I get a very little size and unplay video file ( about 300KB ) when I fix the output_format = "video" ( btw , input_frames=30, times about 60000). It's abnormal since each picture I used to train from kitti image 0006 takes more than 500KB.
> 
> Please have a try with `scripts/cicai_render.py`.

I do use command `python scripts/cicai_render.py --load-config outputs/0006/nsg-kitti-car-depth-recon/2023-08-24_182319/config.yml --output-path renders/output_recon03.mp4` to render video,  and it generate output_recon03.mp4 which is a little unplay video, my cicai_render config is as follow:
![image](https://github.com/OPEN-AIR-SUN/mars/assets/68093830/89905c42-5415-4e53-8965-00d7ed00e378)

As to the viwer problem, I tried the latest comment you reply and it works. However,  the scene looks a little ambiguilty and the angular is a little weired ( can I ask how to fix it btw? ). 
![image](https://github.com/OPEN-AIR-SUN/mars/assets/68093830/c4163cc4-3b23-4edd-ab62-b7ba0506f49c)

Thanks for your all help!
