### ISSUE TITLE
How to adapt to DAIR V2X dataset?

### ISSUE THREAD

**Issue by wutongtong** [OPEN-AIR-SUN/mars#55]
Hi, I tried to adapt MARS to DAIR V2X roadside dataset , but I got some problems. In the training phase, I set  use_depth=False and use_car_latents=False , to prevent overwrite the model weight of the CarNeRF model. In the rendering phase, I set use car_latents=True, to render the cars. I save the output, "objects_rgb", as below, is my process wrong？
![截屏2023-08-28 10 46 57](https://github.com/OPEN-AIR-SUN/mars/assets/13852651/29b07c00-54bf-4469-85c7-c8efbe38716f)

**Comment by wuzirui** [comment]
looks like you got your object poses wrong, please check the axes directions. ref: #42

**Comment by wutongtong** [comment]
Sorry to bother you again，I used [dair2kitti.py](https://github.com/AIR-THU/DAIR-V2X/blob/main/tools/dataset_converter/dair2kitti.py) to convert the DAIR-V2X to kitti format，I think the axes directions should be right，is there any other advice to use the DAIR-V2X  dataset correctly？

**Comment by wutongtong** [comment]
I think the object poses are  correct, the car object are just blur, below is the ground truth.
![截屏2023-08-28 16 49 46](https://github.com/OPEN-AIR-SUN/mars/assets/13852651/4c01b38a-1803-4a9e-b0e7-9db028ead4a3)

**Comment by wutongtong** [comment]
@wuzirui please help me checkout the problem, many thanks!!!

**Comment by wuzirui** [comment]
why do you change use_car_latents False->True in train/eval?

**Comment by wuzirui** [comment]
try using Nerfacto as object representations? The provided checkpoints for the CarNeRF are not trained on DAIR-V2X.

**Comment by wutongtong** [comment]
thank you, I will have a try

**Comment by wutongtong** [comment]
sorry, I did used Nerfacto as object representations, the config as below:
`Ablation_no_depth_kitti = MethodSpecification(
    config=TrainerConfig(
        method_name="ablation-no-depth-kitti",
        steps_per_eval_image=STEPS_PER_EVAL_IMAGE,
        steps_per_eval_all_images=STEPS_PER_EVAL_ALL_IMAGES,
        steps_per_save=STEPS_PER_SAVE,
        max_num_iterations=MAX_NUM_ITERATIONS,
        save_only_latest_checkpoint=False,
        mixed_precision=False,
        use_grad_scaler=True,
        log_gradients=True,
        pipeline=NSGPipelineConfig(
            datamanager=NSGkittiDataManagerConfig( 
                dataparser=NSGkittiDataParserConfig(
                    use_car_latents=False, #wutong
                    use_depth=False,
                    split_setting="reconstruction",
                ),
                train_num_rays_per_batch=4096,
                eval_num_rays_per_batch=4096,
                camera_optimizer=CameraOptimizerConfig(mode="off"),
            ),
            model=SceneGraphModelConfig(
                background_model=NerfactoModelConfig(),
                object_model_template=NerfactoModelConfig(), #wutong
                object_representation="class-wise",
                object_ray_sample_strategy="remove-bg",
            ),
        ),
        optimizers={
            "background_model": {
                "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
            "learnable_global": {
                "optimizer": RAdamOptimizerConfig(lr=1e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
            "object_model": {
                "optimizer": RAdamOptimizerConfig(lr=5e-3, eps=1e-15),
                "scheduler": ExponentialDecaySchedulerConfig(lr_final=1e-5, max_steps=200000),
            },
        },
        # viewer=ViewerConfig(num_rays_per_chunk=1 << 15),
        vis="wandb",
    ),
    description="Neural Scene Graph implementation with vanilla-NeRF model for backgruond and object models.",
)
`

**Comment by wuzirui** [comment]
1. you can try using object-wise over class-wise (some small cars in your rendered image seems like trucks)
2. we have not tested the dair2kitti script but rather create another dataparser. there might be some issue directly using the script.

**Comment by wutongtong** [comment]
Thank you, I will have a try

**Comment by wutongtong** [comment]
Sorry，I have another question，can I use the provided checkpoints of CarNeRF which is trained on kitti/vkitti dataset to render foreground objects upon DARI V2X scene？And how to fix the CarNeRF model from KITTI/VKITTI dataset and use a randomized car latents initialization in the testing phase？
