### ISSUE TITLE
What is scale factor used for?

### ISSUE THREAD

**Issue by sonnefred** [OPEN-AIR-SUN/mars#58]
Hi, in the NSGkittiDataParserConfig, there is a parameter named scale_factor, what is this param used for? Should I change it according to different datasets? Thanks!
![11111111111](https://github.com/OPEN-AIR-SUN/mars/assets/66628395/5152b02a-928c-46f5-8dc4-b523076309cf)

**Comment by wuzirui** [comment]
The scale factor is used to scale the scene. Basically, you want to make sure all the scene contents are in [-1,1].

**Comment by sonnefred** [comment]
Thanks for your reply. If I want to train a model on a custom dataset, how should I change it? Can I just set it to 1? Thanks.

**Comment by wuzirui** [comment]
you can manually adjust the scale based on experimental results, as it is vital for the performances.

**Comment by sonnefred** [comment]
ok, thanks a lot.

**Comment by AmazingRoad** [comment]
> you can manually adjust the scale based on experimental results, as it is vital for the performances.

@wuzirui Should the objects' pose also be in [-1,1]?
