### ISSUE TITLE
nerfstudio/engine/optimizers.py modification wolud influence the training phase?

### ISSUE THREAD

**Issue by Alexanderisgod** [OPEN-AIR-SUN/mars#60]
hi, dear author,
firstly, i use your repo but found " no inf check" error, according  to  
```https://github.com/nerfstudio-project/nerfstudio/pull/1919/commits/386af409cec4ab742439789ac96ee0e88ed71094```
i change the func
```
    def optimizer_scaler_step_all(self, grad_scaler: GradScaler) -> None:
        """Take an optimizer step using a grad scaler.

        Args:
            grad_scaler: GradScaler to use
        """
        for param_group, optimizer in self.optimizers.items():
            max_norm = self.config[param_group]["optimizer"].max_norm
            if max_norm is not None:
                grad_scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(self.parameters[param_group], max_norm)
            if any(any(p.grad is not None for p in g["params"]) for g in optimizer.param_groups):
                grad_scaler.step(optimizer)
```
during training, it seems that it actually influence the final performance. and 
It's not a pipeline problem:  https://github.com/OPEN-AIR-SUN/mars/issues/56 
![image](https://github.com/OPEN-AIR-SUN/mars/assets/41862202/47648a03-d295-4cf8-9623-c443cbed7864)

**Comment by xBeho1der** [comment]
Hi! Thanks for your reply! Could you please provide your training config and wandb report link?

**Comment by Alexanderisgod** [comment]
> Hi! Thanks for your reply! Could you please provide your training config and wandb report link?

maybe it's  caused by the wrong change (i remember the reason why i change it  is to render the video),
so during training parse, it shouldn't be changed. and the previous error "no inf check" maybe also caused by it:
```
        batch_obj_metadata = torch.index_select(obj_meta_tensor, 0, obj_idx.reshape(-1)).reshape(
            -1, obj_idx.shape[1], obj_meta_tensor.shape[1]
        )  # n_rays * n_obj * 5: [track_id, x,y,z, class_id(type)]
        ---------------------->>>>>>>>>>>>>>
        batch_obj_metadata = torch.index_select(obj_meta_tensor.to(obj_idx), 0, obj_idx.reshape(-1)).reshape(
            -1, obj_idx.shape[1], obj_meta_tensor.shape[1]
        )
```

**Comment by Alexanderisgod** [comment]
> > Hi! Thanks for your reply! Could you please provide your training config and wandb report link?
> 
> maybe it's caused by the wrong change (i remember the reason why i change it is to render the video), so during training parse, it shouldn't be changed. and the previous error "no inf check" maybe also caused by it:
> 
> ```
>         batch_obj_metadata = torch.index_select(obj_meta_tensor, 0, obj_idx.reshape(-1)).reshape(
>             -1, obj_idx.shape[1], obj_meta_tensor.shape[1]
>         )  # n_rays * n_obj * 5: [track_id, x,y,z, class_id(type)]
>         ---------------------->>>>>>>>>>>>>>
>         batch_obj_metadata = torch.index_select(obj_meta_tensor.to(obj_idx), 0, obj_idx.reshape(-1)).reshape(
>             -1, obj_idx.shape[1], obj_meta_tensor.shape[1]
>         )
> ```

finally, i found ```obj_meta_tensor.to(obj_idx)``` will change the dtype to int64, so return all 0 values.

**Comment by xBeho1der** [comment]
Good to hear that. But please follow the annotation in `scene_graph.py` to render a video. Please refer to issue #33.

![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/400fd957-add0-445d-81e1-9f369bef3b6b)
