### ISSUE TITLE
Questions about Car-latent code

### ISSUE THREAD

**Issue by jelleopard** [OPEN-AIR-SUN/mars#61]
Thanks for your great work. 
The image patch corresponding to each car ID is cropped according to the GT 2D boundingbox, and it is encoded into a vector of 512 by resnet as car-latent-code. But the quality of the reconstruction has deteriorated（PSNR=28.9 -->26.02）, can you give me some advice.
Question: 
The current id of the car generated rays may from different images, how do I choose the right patch to generate latent-code.
Can car-latent-code be trained on custom data by this way?

**Comment by xBeho1der** [comment]
Hi, our car latent code is generated by CarNeRF([URL](https://lty2226262.github.io/car-studio/)), please refer to their project page for more information.

**Comment by jelleopard** [comment]
Thanks for your reply, I have checked the information, but did not get any valuable information.
 Since car-nerf is not open source, I want to train on a custom data set. Is it possible to generate latent-code through resnet with image patch? Can car-latent-code be trained on custom data by this way?
Thanks again.

**Comment by wuzirui** [comment]
Hi, CarStudio will be open sourced once is accepted. We are sorry but we cannot provide more details since these are separate projects.

**Comment by wuzirui** [comment]
Hey guys, as a kind reminder, the CarStudio paper is accepted by RAL and their code is available now at https://github.com/lty2226262/Car_studio
