### ISSUE TITLE
custom dataset problem: correct monocular results, incorrect binocular results

### ISSUE THREAD

**Issue by MaRongbo** [OPEN-AIR-SUN/mars#67]
When I use left camera only and right camera only, the result is correct. But when I use both left camera and right camera, the result is wrong.
**As you can see in the picture, the render image has 2 lanes.
It seems like the calibration problem, but I check the left and right camera calib and I confirm the calib has no problem.**
![image](https://github.com/OPEN-AIR-SUN/mars/assets/96866008/1990a0a6-741b-463c-942c-a88c15a4885d)

I would like to ask if you have ever encountered this problem, or is there any other code that needs to be modified？
Many thanks!

**Comment by wuzirui** [comment]
that's strange since binocular images should provide more info for the model to converge, we haven't met such issue so far. Maybe a pose visualization will help?

**Comment by AmazingRoad** [comment]
@MaRongbo Did you use the wrong pose for right camera, which make left and right images have the same pose?

**Comment by wuzirui** [comment]
I am closing this issue, but feel free to reopen :)
