### ISSUE TITLE
How can we get the car-object-latents and car-nerf-state-dict at the first place?

### ISSUE THREAD

**Issue by GimpelZhang** [OPEN-AIR-SUN/mars#7]
Hi MARS team, the project is a great work in the NERF simulator area!

I noticed in issue #5 that you provided the car-object-latents and car-nerf-state-dict for some scenes in KITTI-MOT and vKITTI. 

My question is that how we can get the car-object-latents and car-nerf-state-dict from scratch, like if we want to use your default car-nerf foreground model on our own dataset? 

Thanks!

**Comment by wuzirui** [comment]
Hi, the CarNeRF is actually another recent work of our lab ([URL](https://lty2226262.github.io/car-studio/)), please refer to their project page for more information.

**Comment by GimpelZhang** [comment]
> Hi, the CarNeRF is actually another recent work of our lab ([URL](https://lty2226262.github.io/car-studio/)), please refer to their project page for more information.

Thank you!

**Comment by wuzirui** [comment]
Hey guys, as a kind reminder, the CarStudio paper is accepted by RAL and their code is available now at https://github.com/lty2226262/Car_studio
