### ISSUE TITLE
completion depth map for kitti

### ISSUE THREAD

**Issue by rajatmodi62** [OPEN-AIR-SUN/mars#70]
hi , 
i was trying to generate monocular depth maps for kitti 0006. 
i am using the https://github.com/theNded/mini-omnidata repo, but still the depth maps i get are looking pretty bad (nowhere near the quality in the original depth maps authors shared on the google drive)

i directly ran this command:
```
python run.py --task depth --image_path /path/to/image.png --plt_vis --output_npy depth_npy --output_vis depth_vis

```
could someone please help me understand if there is anything i am doing wrong/additional postprocessing that needs to be done , eg. monosdf for rescaling etc...... if so, will appreciate if someone could share how to do that....

my output:
![oot](https://github.com/OPEN-AIR-SUN/mars/assets/10061840/e17ac29c-4917-4ad0-823b-fd594bc052e4)

what i should get:
![000000](https://github.com/OPEN-AIR-SUN/mars/assets/10061840/b0222327-119f-4e0b-98cd-4a95f7afe53a)

thanks

**Comment by xBeho1der** [comment]
Hi! Thanks for your reply! You can try modify as below image in `run.py`

![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/a8312258-7a4b-4f1a-9ae9-e757ac555f8c)

![image](https://github.com/OPEN-AIR-SUN/mars/assets/107318439/8a501aa7-75d3-47eb-97c3-552f4473213a)

**Comment by rajatmodi62** [comment]
hi, 
thanks so much , 
this works now, so closing this issue

**Comment by rajatmodi62** [comment]
it was resizing issue..... fixed now

**Comment by codeman-24** [comment]
> nowhere near the quality in the original depth maps authors shared on the google drive

can you share the link, thank you~

**Comment by cxzhou35** [comment]
> > nowhere near the quality in the original depth maps authors shared on the google drive
> 
> can you share the link, thank you~

Here is the link for the depth maps generated by omnidata tool: https://drive.google.com/drive/folders/1Y-41OMCzDkdJ2P-YZHtCI-5YR9jAIKS2

**Comment by szhang963** [comment]
@rajatmodi62 hi, have you got a performance improvement using a depth loss? And, did it mitigate the background blur for the ego car moving?
