### ISSUE TITLE
request for help with some baselines and papers

### ISSUE THREAD

**Issue by rajatmodi62** [OPEN-AIR-SUN/mars#71]
hi, 
i am grateful for this amazing work and the efforts the authors have made to open source this repo, 
i am a small beginner on nerfs, and would be grateful if someone could please help me out, 

[1] is there a way to reproduce the results on nerf, nerf+time, mip, nsg and suds in this repo.......
if not, will be grateful if someone could please guide me on how i could go about settings these baselines for kitti view synthesis task?

[2] clarifications on sequence ids, 0001,0002,0006,
the author of suds and nsg confirmed that there results are average of these 3 sequences..... in this repo, is there a plan to also share models for these other sequences. 

[3] i have trouble wrapping my hand around how unbounded nerfs work... if the camera trajectory is free moving... how are the renderings done.... will be grateful for some paper references.....
best, 
rajat

**Comment by wuzirui** [comment]
1. you could try using out kitti dataparser and using the models from nerfstudio
2. our results are averaged, but we currently are not planning to release more checkpoints
3. I don't quite get your point here, what's the problem about free camera trajectories?

**Comment by rajatmodi62** [comment]
hi , 
thank you so much, i will look at nerfstudio 

[3] for unbounded scenes, i just wanted to ask about the pose matrix. 
i know that a pose matrix is four by four, and there is world origin, 
i had a q for real world datasets like kitti, 
what is the meaning of pose matrix there, 
the car is moving in the real world, so where is the origin assumed to exist?

**Comment by wuzirui** [comment]
the object pose consists of the xyz positions and rotation angles in a series of frame timestamps. Based on these info, we can compute the relative transformations between rays and objects.
