### ISSUE TITLE
cannot render Faraway moving object

### ISSUE THREAD

**Issue by wutongtong** [OPEN-AIR-SUN/mars#73]
hi，dear all，I have tried trainning model on DAIRV2X dataset，I found that cars in faraway can not be rendered，while nearby cars can be rendered successfully，the rendered rgb and the object rgb result as shown below，could you give me some advice，thanks in advance
![img_2500_c962706f71997b442236](https://github.com/OPEN-AIR-SUN/mars/assets/13852651/e7ed0391-2cdf-4640-b795-82acd1ce2358)
![media_images_Eval Images_objects_rgb_2500_6d1eb5c542a2542d3a9b](https://github.com/OPEN-AIR-SUN/mars/assets/13852651/be189513-e025-4f1c-b743-4404383b8d67)

**Comment by wuzirui** [comment]
there's bunch of problems with the object poses, e.g. inconsistency, ID changes, missing objects...

**Comment by wutongtong** [comment]
sorry, what is the meaning of inconsistency of the object pose?

**Comment by wuzirui** [comment]
including: same car different ID, different relative bbox position to the car, different bbox size, etc.

**Comment by wutongtong** [comment]
sorry, I uploaded a random objects_rgb image, which is not related to the ground truth image, and I have checked the bbox position to the car is correct。
