### ISSUE TITLE
ripples on the rendered image

### ISSUE THREAD

**Issue by wutongtong** [OPEN-AIR-SUN/mars#74]
Hi，dear author，I have trained a model on the DAIR-V2X dataset，when I enlarged the rendered image，I found that there are some ripples on the picture，the ground truth and rendered image as shown bellow，could you give me some adivce？
![media_images_Eval Images_img_6500_c054f77fd41bdbc09ce7](https://github.com/OPEN-AIR-SUN/mars/assets/13852651/fdf53d1a-3bad-4ef9-a3ce-97ba9293e489)

**Comment by wuzirui** [comment]
seems to be a typical type of artifact of nerfacto, no good insight on that so far to improve the rendering quality. However, you can further optimize the NeRF rendered images with post-optimizers like NeRFLiX or so.

**Comment by wutongtong** [comment]
thank you，I will have a try at it
