### ISSUE TITLE
where is car_object_latents pretrained model?

### ISSUE THREAD

**Issue by a4152684** [OPEN-AIR-SUN/mars#78]
hello, i wonder know where is car_object_latents pretrained model

**Comment by xBeho1der** [comment]
Hi! You can find it in our README

If you choose to use the category-level object model, please make sure that the use_car_latents=True and the latent codes exists. We provide latent codes of some sequences on KITTI-MOT and vKITTI2 datasets [here](https://drive.google.com/drive/folders/1E4YjMwkDbRsF4Hb1UK0iBDkz-tFVx3Me?usp=sharing).

**Comment by wuzirui** [comment]
Hey guys, as a kind reminder, the CarStudio paper is accepted by RAL and their code is available now at https://github.com/lty2226262/Car_studio
