### ISSUE TITLE
how can I change the view of camera for rendering

### ISSUE THREAD

**Issue by loyris** [OPEN-AIR-SUN/mars#80]
I want to know how can I change the view of camera for rendering

**Comment by saythe17** [comment]
You can modify the camera_to_worlds matrix in the cicai_render.py to change the view of camera for rendering

        camera_to_worlds = pipeline.datamanager.train_dataset.cameras.camera_to_worlds

        cameras_a = Cameras(
            fx=camera_path.fx[select_frame],
            fy=camera_path.fy[select_frame],
            cx=camera_path.image_width[select_frame] / 2,
            cy=camera_path.image_height[select_frame] / 2,
            camera_to_worlds=camera_to_worlds[select_frame],
            camera_type=camera_type,
            # times=times,
        )
        _render_trajectory_video(
            pipeline,
            cameras_a,
            output_filename=self.output_path,
            rendered_output_names=self.rendered_output_names,
            rendered_resolution_scaling_factor=1.0 / self.downscale_factor,
            seconds=seconds,
            output_format="images",
            camera_type=camera_type,
            render_width=render_width,
            render_height=render_height,
        )

**Comment by wuzirui** [comment]
Yeah, just use the nerfstudio functionalities~

I am closing this issue, feel free to reopen.
