### ISSUE TITLE
bugfix in dataparser 

### ISSUE THREAD

**Issue by zjcs** [OPEN-AIR-SUN/mars#84]
The origin dataparser in the mars/nsg/data folder is:
NSGkittiDataParserConfigSpecification = DataParserSpecification(config=NSGkittiDataParserConfig)
NSGvkittiDataParserConfigSpecification = DataParserSpecification(config=NSGvkittiDataParserConfig)

When run ns-train -h, the warning occurs:
`/usr/local/lib/python3.8/site-packages/tyro/_resolver.py:305: UserWarning: <class 'nsg.data.nsg_vkitti_dataparser.NSGvkittiDataParserConfig'> does not match any type in Union: [<class 'nerfstudio.data.dataparsers.nerfstudio_dataparser.NerfstudioDataParserConfig'>, <class 'nerfstudio.data.dataparsers.minimal_dataparser.MinimalDataParserConfig'>, <class 'nerfstudio.data.dataparsers.arkitscenes_dataparser.ARKitScenesDataParserConfig'>, <class 'nerfstudio.data.dataparsers.blender_dataparser.BlenderDataParserConfig'>, <class 'nerfstudio.data.dataparsers.instant_ngp_dataparser.InstantNGPDataParserConfig'>, <class 'nerfstudio.data.dataparsers.nuscenes_dataparser.NuScenesDataParserConfig'>, <class 'nerfstudio.data.dataparsers.dnerf_dataparser.DNeRFDataParserConfig'>, <class 'nerfstudio.data.dataparsers.phototourism_dataparser.PhototourismDataParserConfig'>, <class 'nerfstudio.data.dataparsers.dycheck_dataparser.DycheckDataParserConfig'>, <class 'nerfstudio.data.dataparsers.scannet_dataparser.ScanNetDataParserConfig'>, <class 'nerfstudio.data.dataparsers.sdfstudio_dataparser.SDFStudioDataParserConfig'>, <class 'nerfstudio.data.dataparsers.nerfosr_dataparser.NeRFOSRDataParserConfig'>, <class 'nerfstudio.data.dataparsers.sitcoms3d_dataparser.Sitcoms3DDataParserConfig'>, <class 'type'>, <class 'type'>]
  warnings.warn(
/usr/local/lib/python3.8/site-packages/tyro/_resolver.py:305: UserWarning: <class 'nsg.data.nsg_dataparser.NSGkittiDataParserConfig'> does not match any type in Union: [<class 'nerfstudio.data.dataparsers.nerfstudio_dataparser.NerfstudioDataParserConfig'>, <class 'nerfstudio.data.dataparsers.minimal_dataparser.MinimalDataParserConfig'>, <class 'nerfstudio.data.dataparsers.arkitscenes_dataparser.ARKitScenesDataParserConfig'>, <class 'nerfstudio.data.dataparsers.blender_dataparser.BlenderDataParserConfig'>, <class 'nerfstudio.data.dataparsers.instant_ngp_dataparser.InstantNGPDataParserConfig'>, <class 'nerfstudio.data.dataparsers.nuscenes_dataparser.NuScenesDataParserConfig'>, <class 'nerfstudio.data.dataparsers.dnerf_dataparser.DNeRFDataParserConfig'>, <class 'nerfstudio.data.dataparsers.phototourism_dataparser.PhototourismDataParserConfig'>, <class 'nerfstudio.data.dataparsers.dycheck_dataparser.DycheckDataParserConfig'>, <class 'nerfstudio.data.dataparsers.scannet_dataparser.ScanNetDataParserConfig'>, <class 'nerfstudio.data.dataparsers.sdfstudio_dataparser.SDFStudioDataParserConfig'>, <class 'nerfstudio.data.dataparsers.nerfosr_dataparser.NeRFOSRDataParserConfig'>, <class 'nerfstudio.data.dataparsers.sitcoms3d_dataparser.Sitcoms3DDataParserConfig'>, <class 'type'>, <class 'type'>]
  warnings.warn(
usage: ns-train [-h]`

The correct usage is:
NSGkittiDataParserConfigSpecification = DataParserSpecification(config=NSGkittiDataParserConfig())
NSGvkittiDataParserConfigSpecification = DataParserSpecification(config=NSGvkittiDataParserConfig())

**Comment by xBeho1der** [comment]
Hi! Thanks for your feedback! We will fix it as soon as possible.
