### ISSUE TITLE
change the view of the camera

### ISSUE THREAD

**Issue by sonnefred** [OPEN-AIR-SUN/mars#87]
Hi, I'm trying to render images using novel camera poses. When I rotate the camera, the rendered result is still acceptable; but when I shift the position of the camera, the result is very blurry, especially the region near the camera(e.g. the road and the lanelines). Could you give me any hint about this? Thanks.

**Comment by wuzirui** [comment]
which sequence are you using? This largely depends on the background nerf and the sequence you use. For example, the KITTI-06 sequence has almost no ego-motion, so that the learned scene representation may be wrong.

**Comment by sonnefred** [comment]
> which sequence are you using? This largely depends on the background nerf and the sequence you use. For example, the KITTI-06 sequence has almost no ego-motion, so that the learned scene representation may be wrong.

I'm doing experiments on my custom dataset, and in this scene, the ego vehicle is always moving forward. The following images are the result, the upper one is the original view and the lower one is the shifted view. You can see when the camera is shifted to the left side, the road (including the lane lines) is very blurry. Do you have any suggestion about this? Thanks.
![00010](https://github.com/OPEN-AIR-SUN/mars/assets/66628395/5dc6a844-406f-4b41-a4ee-2f3a35b0470b)
![00010-1](https://github.com/OPEN-AIR-SUN/mars/assets/66628395/4a1e7daa-f86b-4761-a6c6-ea7771fee119)

**Comment by wuzirui** [comment]
This type of scene is challenging since they are kinda like the sparse view setting. I would suggest you try nerfacto-big/huge with proper regularization terms, or methods that are designed for AD/free trajectory scenes, such as LocalNeRF, F2-NeRF, StreetSurf, etc. However, the latter methods have no nerfstudio implementation so far (to the best of my knowledge).

**Comment by amoghskanda** [comment]
@sonnefred how did you change the ego's trajectory?
