### ISSUE TITLE
mask = (bg_samples_z_vals > z_vals_in_o.unsqueeze(-1)) & (bg_samples_z_vals < z_vals_out_o.unsqueeze(-1))

### ISSUE THREAD

**Issue by qaqaqaaaa** [OPEN-AIR-SUN/mars#89]
Thanks for your excellent work! But I have some problems when I read the code. It is about  the code 
![image](https://github.com/OPEN-AIR-SUN/mars/assets/54053095/ebe5023e-d260-4a5e-b2bd-e28378ad2145)

"mask = (bg_samples_z_vals > z_vals_in_o.unsqueeze(-1)) & (bg_samples_z_vals < z_vals_out_o.unsqueeze(-1))" in the /mars/nsg/models/scene_graph.py. 

I think bg_samples_z_vals is a variable in the world coordinate, while z_vals_out_o is a variable in the camera coordinate. Why can they compare? I have been confused for a long time, and I would be very grateful if you could help me solve it

**Comment by wuzirui** [comment]
Noted, will look into that. Thank you very much and I will get back to you asap!

**Comment by wuzirui** [comment]
Hi, I think we indeed made some mistakes here, the correct version should use `z_vals_in/out_w` instead of the `_o` version. We will update the code after some experiments. Thank you very much!

**Comment by xBeho1der** [comment]
Hi! The bug has been fixed in this [commit](https://github.com/OPEN-AIR-SUN/mars/commit/99e4a036bc717ea3db0c5d3b6e8888244172e23b).
