### ISSUE TITLE
How to get the result of depth completion？

### ISSUE THREAD

**Issue by jelleopard** [OPEN-AIR-SUN/mars#9]
Hi, thanks for sharing your great work.
May I ask how you get the results of depth completion. 
Can you provide a link to download the panoptic maps from the kitti dataset? The official website is a bit difficult to access.
Thanks

**Comment by xBeho1der** [comment]
Thanks for your feedback!
The depth maps we use are actually generated with a [monocular depth estimation model](https://github.com/theNded/mini-omnidata). Sorry for the misleading names.
For panoptic maps, you can refer to #2 for some information.
