### ISSUE TITLE
no foreground

### ISSUE THREAD

**Issue by 1839283900** [OPEN-AIR-SUN/mars#90]
Hello, I use the KITTI dataset to train and render, the background can be displayed normally, but there is no foreground display, there will be a left turn effect. May I ask what is the reason for this

**Comment by wuzirui** [comment]
Hi, please provide more information so that we can see what happens, e.g. the sequence you trained on, the background and foreground model you used, the configs, ... Thanks!

**Comment by 1839283900** [comment]
![1698419573189](https://github.com/OPEN-AIR-SUN/mars/assets/86339563/81a34c29-b7b7-4d2c-82ad-209ac0d2d5cd)
I'm sorry, I'm a beginner, this is my config, using the nsg-kitti-car-depth-repon method, I just followed the readme to set up the environment, only modified the position of the dataset, and then started training, but did not render the vehicle

like this
![1698420130589](https://github.com/OPEN-AIR-SUN/mars/assets/86339563/a94d33d9-98dc-4b04-9ab3-d06a9b2ada12)

**Comment by 1839283900** [comment]
Thank you for your prompt answer, I will give it a try

**Comment by 1839283900** [comment]
Thank you for your prompt reply, I will have a try.
