### ISSUE TITLE
question about load car_latents

### ISSUE THREAD

**Issue by qaqaqaaaa** [OPEN-AIR-SUN/mars#94]
hi, author. why track_car_latents_mean get the last one track_car_latents latent, not the mean(sum them then div)?
![image](https://github.com/OPEN-AIR-SUN/mars/assets/54053095/c2a1540e-0948-4645-b167-048a2ab96146)

**Comment by wuzirui** [comment]
Hi @qaqaqaaaa, thank you for the question. This is kind of like the first version of the dataloader, which uses the last latent to represent the whole car. We have tried some other variants, e.g. mean, but the performances are just similar.
