### ISSUE TITLE
Question on rendering script

### ISSUE THREAD

**Issue by Francis777** [OPEN-AIR-SUN/mars#98]
First of all congrats on your great work!

1. Is there any reason why we don't want to always move `obj_meta_tensor` to `self.device` here? 
https://github.com/OPEN-AIR-SUN/mars/blob/4bcb305b2462f0b2613c7a3186b8fcc818844315/mars/models/scene_graph.py#L641

3. Besides rendering the entire scene, I'd also like to render an individual instance not as part of the scene but in their object space: so far I'm using the pretrained CarNeRF model and kitti latent you kindly provided, but I haven't been able to get reasonable rendered outputs. I wonder if you've done something similar? 

Thanks!

**Comment by wuzirui** [comment]
Hi @Francis777! Thank you for your questions.

1. It seems if we add this line while training, there will be some device problems, we are working on this. Please stay tuned~
2. Does the 'object_rgb' work? Or do you only want one car? If that is the case, you may need to stretch the car bounding box from [-1,1]^3 to its real scale. We haven't try anything like that yet, maybe you can show some images here so that we can have some more insights.

**Comment by xBeho1der** [comment]
Hi @Francis777! #100 fix render bug, no longer requiring manual specification of the device during rendering.

**Comment by Francis777** [comment]
Thanks for your response! 
@wuzirui I'm not sure what is `object_rgb` referring to, but yes here I'm interested in only one car. It turns out that previously I forgot to set the `aabb_box` bound when generating rays. Now I'm able to get ok-ish result with the pretrained `CarNeRF` model and the kitti object latent. Does the quality look reasonable to you? Also could you point me to the code where "stretch the car bounding box from [-1,1]^3 to its real scale" happens? 
https://github.com/OPEN-AIR-SUN/mars/assets/25652281/a61ce6cc-2570-423e-a2f7-2dcf1d6d1597

@xBeho1der thanks for pushing the fix! Could you also do a new release in https://pypi.org/project/mars-nerfstudio/? Alternatively it'd be also great if you could add your `setup.py` so that it can be installed locally!

**Comment by xBeho1der** [comment]
@Francis777 Hi!

Thanks for your feedback. We have already published a new [release](https://pypi.org/project/mars-nerfstudio/0.3.3.post1/) of mars-nerfstudio and that's the latest version. By the way, what exactly do you mean by `setup.py` that you mentioned? If you want to install it locally, you can try `pip install -e .` in mars directory.

**Comment by Francis777** [comment]
@xBeho1der I meant installing the package with `python setup.py install`, but the way you recommended seems better, thanks for your help!
