### ISSUE TITLE
number of images load in viewer

### ISSUE THREAD

**Issue by pierremerriaux-leddartech** [OPEN-AIR-SUN/mars#99]
Hi,
I am testing the last master after the refactorisation, probably I am wrong somewhere, but with the same dataset 2 days ago I saw all the camera in the web viewer, and now with the new version, only one couple left and right appear:

new version runing, with this CLI:
`ns-train mars-kitti-car-depth-recon --data ~/data/kitti-MOT/training/image_02/0006 --viewer.websocket-port 7008  --pipeline.datamanager.dataparser.car-object-latents-path ~/data/mars-nerf/latents/latent_codes_car_van_truck.pt --pipeline.datamanager.dataparser.car-nerf-state-dict-path ~/data/mars-nerf/latents/KITTI-MOT/car-nerf-state-dict/epoch_670.ckpt --vis viewer`
![image](https://github.com/OPEN-AIR-SUN/mars/assets/42007976/cc09a7cd-d96d-4218-a290-e66fa1f1e2e6)

and prevous master with this CLI:
```
ns-train nsg-kitti-car-depth-recon --data ~/data/kitti-MOT/training/image_02/0006 --viewer.websocket-port 7008  --pipeline.datamanager.dataparser.car-object-latents-path ~/data/mars-nerf/latents/latent_codes_car_van_truck.pt --pipeline.datamanager.dataparser.car-nerf-state-dict-path ~/data/mars-nerf/latents/KITTI-MOT/car-nerf-state-dict/epoch_670.ckpt --vis viewer 
```
![image](https://github.com/OPEN-AIR-SUN/mars/assets/42007976/4545d9ff-a6af-4201-b1f5-4bb3fc034960)

thanks

**Comment by pierremerriaux-leddartech** [comment]
after a deeper look, all the camera are here, but probably with the same pose ? so I see only one
![image](https://github.com/OPEN-AIR-SUN/mars/assets/42007976/cc8a8958-6766-409f-8c28-838ac00c9976)

**Comment by pierremerriaux-leddartech** [comment]
forget all off that please, it is just the MarsVKittiDataParserConfig last_frame default value changed ! and as in sequences 6 the ego vehicle is stopped at the begining...
thanks

**Comment by wuzirui** [comment]
btw It seems like my email failed to reach you, have you got my latest one? XD @pierremerriaux-leddartech
